### ISSUE TITLE
Problem with skimage.__0.13.x__ and __0.14.x__.morphology.convex_hull.py 

### ISSUE THREAD

**Issue by shenlinyao** [scikit-image/scikit-image#3277] opened 2018-07-20 07:29 UTC
## Description
I use the function: convex_hull_image in convex_hull (skimage.__0.14.x__) and it returns 

AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
hull = ConvexHull(coords)
File "qhull.pyx", line 2335, in scipy.spatial.qhull.ConvexHull.__init__
File "qhull.pyx", line 266, in scipy.spatial.qhull._Qhull.__init__

But I run the same code using convex_hull_image in convex_hull (skimage.__0.13.x__)
It worked well!
The difference between two version is that 0.13.x use scipy.spatial.Delaunay, while the 0.14.x use scipy.spatial.ConvexHull.
I want to know why the new version cannot work! Thank you!
## Way to reproduce
Here is my code
```
def process_mask(mask):
    convex_mask = np.copy(mask)
    for i_layer in range(convex_mask.shape[0]):
        mask1  = np.ascontiguousarray(mask[i_layer])
        if np.sum(mask1)>0:
            mask2 = convex_hull_image(mask1)
            if np.sum(mask2)>1.5*np.sum(mask1):
                mask2 = mask1
        else:
            mask2 = mask1
        convex_mask[i_layer] = mask2
    struct = generate_binary_structure(3,1)  
    dilatedMask = binary_dilation(convex_mask,structure=struct,iterations=10) 
    return dilatedMask
```

**Comment by stefanv** [comment] 2018-07-20 18:12
Please provide us with a fully reproducible code snippet: i.e., that we can run in Python directly, along with a test image, that reproduces your error.  Thanks!

**Comment by jni** [comment] 2018-07-22 08:44
@shenlinyao what version of scipy are you using? The following code, together with your definition, works for me:

```python
import numpy as np
from skimage import data
from skimage.morphology import convex_hull_image
from scipy.ndimage import generate_binary_structure, binary_dilation

def process_mask(mask):
    ...

mask = np.stack([data.horse()] * 3, axis=0)
dmask = process_mask(mask)
```

**Comment by sciunto** [comment] 2018-10-12 15:46
As we do not have replies for precisions, I close this issue. If this happens again and you get more details, please reopen.

**Closed by sciunto** 2018-10-12 15:46 UTC

**Comment by yxdragon** [comment] 2019-03-20 10:35
I encounter it too, And I use the same version of python and scipy, skimage in 500+ computers, but only meet one case. So it depends on the system.

```bash
 File "D:\ImagePy\programs\lib\site-packages\skimage\measure\_regionprops.py", line 162, in convex_image
    return convex_hull_image(self.image)
  File "D:\ImagePy\programs\lib\site-packages\skimage\morphology\convex_hull.py", line 79, in convex_hull_image
    hull = ConvexHull(coords)
  File "qhull.pyx", line 2359, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 266, in scipy.spatial.qhull._Qhull.__init__
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
OSError: Failed to open file b'C:\\Users\\\xe7\x94\xb5\xe8\x84\x91\xe3\x80\x81\xe3\x80\x81\\AppData\\Local\\Temp\\scipy-31i75js9'
```

**Comment by stefanv** [comment] 2019-03-20 17:16
This looks like a problem with your SciPy installation.

**Comment by papr** [comment] 2019-11-14 16:21
The issue seems to be related to Windows user names that include non-ascii charecters. I would like to reopen the issue since this seems to be still present in the current version of scipy.

This error should be reproducible by executing this code on an user account like `Tést`:
```py
import numpy as np
from scipy.spatial import ConvexHull

data = np.random.RandomState(42).rand(3, 2)
ConvexHull(daat)
```

**Comment by jni** [comment] 2019-11-16 00:17
Ah! Thanks for tracking it down, @papr! Either way though, this issue should be raised with SciPy, not here.

**Comment by papr** [comment] 2019-11-16 14:09
Correct. This is the existing scipy issue: https://github.com/scipy/scipy/issues/8850
