### ISSUE TITLE
no module named skimage

### ISSUE THREAD

**Issue by doaa90** [scikit-image/scikit-image#3275] opened 2018-07-18 14:44 UTC
Hello guys, 
I try to import "skimage" module but an error says no module named "skimage", I have all requirements and I downloaded the "scikit- image ".
I am using  Python 64 bit version 3.6.4
windows 10
I tried a lot of solution but no one works for me.
I hope you can help me.
Thank you :)

**Comment by JDWarner** [comment] 2018-07-18 20:59
We need more information.  What Python are you using?  Where did you download scikit-image from?  After downloading it, did you install it - manually or via pip/package manager?  If it was installed, was it successful?  I'd not, we need the traceback.

This sort of issue is almost always due to misunderstandings on package installation or misconfiguration of virtual environments.

**Comment by doaa90** [comment] 2018-07-20 11:29
@JDWarner 
Thank you for your reply.
Python version 3.6.4  , 64 bit , install it by using many ways: conda, pip, manually, from the source and   every time when I download it  was successful and when I want to run " import skimage " the same error  then, I delete it and try by another way and till now nothing change.

**Comment by stefanv** [comment] 2018-07-20 18:09
Please show us the output of each installation attempt, as well as the output of the failed usage attempt.

**Comment by doaa90** [comment] 2018-07-22 12:40
@stefanv 
Thank you for your reply.
everything is ok now, The solution was to copy the libraries to the sit-packages in the environment that I worked on it.
Thank you all

**Comment by soupault** [comment] 2018-07-24 12:56
I assume the issue is already solved. Closing...

**Closed by soupault** 2018-07-24 12:56 UTC
Labels: support
