### ISSUE TITLE
import error with numpy 0.16 and scikit-image 0.14

### ISSUE THREAD

**Issue by pandagre** [scikit-image/scikit-image#3867] opened 2019-04-27 21:06 UTC
Previous subject: ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Users\basant\Anaconda3\lib\site-packages\numpy\lib\arraypad.py)

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by pandagre** [comment] 2019-04-27 21:08
this error comes when i run this line, from skimage.measure  import data, io, filters

**Comment by hmaarrfk** [comment] 2019-04-27 21:22
Please include the version information requested. The sample code to generate it is provided to you in the Issue template.....

was there a particular reason you thought we didn't need the small amount of information we requested?

**Comment by pandagre** [comment] 2019-04-27 23:36
It's numpy 1.6.2 and scikit 0.14 version in my anaconda library

**Comment by hmaarrfk** [comment] 2019-04-27 23:56
my guess is that you are running 0.14.1, which doesn't support numpy 1.16.

Please update to 0.14.2 or 0.15.0

That should help you resolve your issue.

Otherwise, please give the output of 

```
pip list
```
or 
```
conda list
```

**Comment by jni** [comment] 2019-04-28 01:22
This appears to be a duplicate of #3551. I'm going to close it as such, but @pandagre please reopen if updating scikit-image does not fix your problem. If you have NumPy>=1.16, scikit-image needs to be >=0.14.2 or >=0.15.0.

**Closed by jni** 2019-04-28 01:22 UTC
Labels: status: needs info, type: support

**Comment by hmaarrfk** [comment] 2019-04-28 18:44
I know it can be challenging to keep all packages inline. Let us know if you have any more trouble installing the correct version.
