### ISSUE TITLE
invalid colour conversion raises error rather than warning

### ISSUE THREAD

**Issue by marcusmchale** [scikit-image/scikit-image#7105] opened 2023-08-21 15:20 UTC
This seems like a bug in colour conversion.
```python
lab2rgb([0, 0,  28.0])
```
raises `TypeError: 'numpy.float64' object does not support item assignment`

while:
```python
lab2rgb([0, 0,  27.0])
```
works fine.

This difference is because the former results in a negative z-value in _lab2xyz conversion. The intended behaviour seems to be to assign this to 0 and return the n_invalid count back to the caller for warnings to be raised.

However, the attempt to reassign is performed by indexing on the z value (a numpy.float64 object) which raises the type error in the last line here.

https://github.com/scikit-image/scikit-image/blob/2336565966acdcf2bfd6e6a7322c6f1f477fca8e/skimage/color/colorconv.py#L1173C1-L1182C23

A simple fix is for this last line to read z=0 rather than z[invalid] = 0

Should I submit a pull request for this?

**Comment by lagru** [comment] 2023-08-23 13:42
Thanks for the report! I can reproduce and this indeed looks like something we should fix. But I don't think `z=0` is the correct fix as `z` can be an array. E.g. `array([[0.09734016, 0.        , 0.        ]])` passes "fine" and should continue to do so. So I think the solution is to ensure that `z` is always an array that can be assigned to. I'd be supper happy to review a PR if you want to submit one! :D Let me know if you need clarification or help with that.

**Comment by lagru** [comment] 2023-08-31 12:00
Hey, I labeled this as a good first issue, in case someone else wants to pick this up. ;)

**Closed** 2023-09-08 01:27 UTC
Labels: :beginner: Good first issue
