### ISSUE TITLE
Interpolation: fast code path may yield different results

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1035] opened 2014-06-23 09:40 UTC
In `skimage.transform._geometric`, a fast code path is implemented to speed up interpolation for certain spline orders and input types.  The results may differ from those given by SciPy's spline interpolation, though.  We should verify that the two code paths return the same results.

Notes:
- Spline pre-filtering not done by current implementation?
- skimage cubic interpolation formula: http://www.paulinternet.nl/?page=bicubic

**Comment by zym1010** [comment] 2016-05-25 03:38
Hi,

just wonder if this issue has been solved. I have been recently using bicubic (order=3) to do rescale and resize (for shrinking imaegs, not enlargement), and found the result to be quite different from those produced by MATLAB or PIL. In particular, the result produced by skimage looks sharper, and less smooth than MATLAB or PIL. Does this imply that there's a pre smoothing operation done in MATLAB and PIL, or there's still some problem with scikit-image's bicubic interpolation? I'm using skimage `0.12.3` from Miniconda. Thanks.

**Comment by ahojnnes** [comment] 2016-05-25 06:41
@zym1010 Our bi-cubic interpolation should be correct. Can you post short code snippets for Matlab and PIL to reproduce?

**Comment by zym1010** [comment] 2016-05-25 13:08
@ahojnnes After some testing, I believe the implementation in skimage is correct. The difference may lie in the **antialiasing** filtering, which is probably mandatory in Pillow and optional in MATLAB.

the snippets are as follows.

First, I generated scaled down versions of `astronaut` using Pillow and skimage.

~~~python
image = astronaut()
image_processed_1 = Image.fromarray(astronaut())
image_processed_1 = image_processed_1.resize((128, 128), resample=Image.BICUBIC)
image_processed_2 = rescale(image, 0.25, order=3, mode='nearest')
imsave('astronaut.png',image)
imsave('astronaut_PIL.png',image_processed_1)
imsave('astronaut_skimage.png',img_as_ubyte(image_processed_2))
~~~

Then I downloaded the three saved `png` files and ran the following MATLAB script to do resizing in MATLAB and compare the images produced.

~~~matlab
im = imread('astronaut.png');
im_rescaled_aa = double(imresize(im, 0.25, 'bicubic'));
im_rescaled_noaa = double(imresize(im, 0.25, 'bicubic', 'Antialiasing', false));

im_pil = double(imread('astronaut_PIL.png'));
im_skimage = double(imread('astronaut_skimage.png'));

diff_aa_pil = im_pil(:)-im_rescaled_aa(:);
diff_aa_skimage = im_skimage(:)-im_rescaled_aa(:);
diff_noaa_skimage = im_skimage(:)-im_rescaled_noaa(:);

fprintf('diff mean between matlab aa and pil: %f, std: %f\n', mean(diff_aa_pil), std(diff_aa_pil));
fprintf('diff mean between matlab aa and skimage: %f, std: %f\n', mean(diff_aa_skimage), std(diff_aa_skimage));
fprintf('diff mean between matlab no aa and skimage: %f, std: %f\n', mean(diff_noaa_skimage), std(diff_noaa_skimage));
~~~

and I get the following result.

~~~
>> output_matlab_version
diff mean between matlab aa and pil: 0.001567, std: 0.485866
diff mean between matlab aa and skimage: 0.007202, std: 9.993774
diff mean between matlab no aa and skimage: -0.063883, std: 0.426613
~~~

Since these images are saved in lossy `unit8`, and the difference between matlab no aa and skimage is so close, I believe the implementation is correct and they differ in some minor details.

But I have two questions in general.

1. What's the recommended interpolation order when shrinking images using skimage?  `skimage`'s bicubic interpolation give aliasing, which is undesired. Maybe I should simply stick to bilinear? <http://nickyguides.digital-digest.com/bilinear-vs-bicubic.htm> recommends bilinear for shrinking, and bicubic for enlargement. BTW, while it's possible, I don't want to bother filtering the image myself before shrinking the images, as this is not my task at hand, and I just want a decent image shrinking function.
2. Why is this issue still open?

Thanks.

**Comment by ahojnnes** [comment] 2016-05-25 15:08
1) I would recommend using http://scikit-image.org/docs/dev/api/skimage.transform.html#downscale-local-mean for downsampling, but you should check which method gives you the most satisfactory results.
2) It is bi-quadratic filtering that is inconsistent with scipy and not bi-cubic, hence this issue is still open.

**Comment by zym1010** [comment] 2016-05-25 15:38
@ahojnnes thanks. I just tried `downscale-local-mean`. It looks nice, but I think it's kind of tricky to use if I try to shrink my image into some arbitrary size, since the parameter `factors` is in block size, and not the final output size. Also, won't such downscale method give some blocky effect?

**Comment by niallmacq** [comment] 2016-11-21 18:20
I agree, image j is doing some sort of bicubic interpolation even when the average when downsizing box is checked. using the scipy.misc.imresize almost gets the same answer as imagej, but not quite.

**Comment by stefanv** [comment] 2018-12-03 18:44
@zym1010 @niallmacq FWIW, we now do anti-aliasing for downsampling, which may help for your use cases.

**Comment by rfezzani** [comment] 2020-02-19 17:09
@stefanv, here is the output of your previous experimentation:
```python
io.imsave('down4_resize.png', transform.resize(res_chart, (222,320), order=3))
io.imsave('down4_rescale.png', transform.rescale(res_chart, (0.25,0.25), order=3))
io.imsave('down4_avg.png', transform.downscale_local_mean(res_chart, (4,4)))
```
![down4_resize](https://user-images.githubusercontent.com/3438227/74856693-d2ee4900-5342-11ea-942b-a662d148c40a.png)
![down4_rescale](https://user-images.githubusercontent.com/3438227/74856701-d4b80c80-5342-11ea-86e1-5aacdd787983.png)
![down4_avg](https://user-images.githubusercontent.com/3438227/74856702-d681d000-5342-11ea-9b5c-f8f01ab2acc2.png)

Can't we consider that the issue is solved? ;-)

**Comment by rfezzani** [comment] 2020-10-05 08:30
I am closing this one, but of course feel free to reopen :wink:

**Closed by rfezzani** 2020-10-05 08:30 UTC
