### ISSUE TITLE
Swirl artefacts ?

### ISSUE THREAD

**Issue by rougier** [scikit-image/scikit-image#1669] opened 2015-08-28 19:59 UTC
The image from the swirl example at http://scikit-image.org/docs/dev/auto_examples/plot_swirl.html seems to have black artefacts on the border. As if one side of the image has been shifted to the other side. Is that the expected behavior ? If yes, maybe it's worth writing it.

![](http://scikit-image.org/docs/dev/_images/plot_swirl_1.png)

**Comment by jni** [comment] 2015-08-28 20:05
I know that we've seen this before, but I don't remember the outcome of that discussion. @ahojnnes?

**Comment by TrishaMittal** [comment] 2015-11-05 13:14
Hi,

I am new to scikit-image and I want to contribute. I have worked in image processing in matlab and openCV.  I was familiarising myself with the scikit-image codes and I sort of followed up this issue about swirl.
This issue had come up in 2013. 

The explanation given at that time was that the swirl requires information beyond the borders of the current image. So, skimage.transform.swirl pads before transforming. The padding is done with zeros which causes what we see in the demo.

It was also stated that changing modes rescue the behaviour. The change suggested in the code was in this particular line:

im = skimage.transform.swirl(im, mode='reflect')

I tried to run my code changing the line. And, I could see the difference. I hope this was useful.
I would like to contribute and will be grateful if somebody could give me a few starting pointers.

**Comment by stefanv** [comment] 2015-11-06 00:33
I suspect the issue here is that the swirl effect is not quite "faded out" by the time it reaches the edge of the image, so what you see there is, as @TrishaMittal mentions, interpolation that includes values outside the image.  We could change the example to have a quicker exponential dropoff, if you think this is a big enough problem (it's not a bug).

**Comment by jni** [comment] 2015-11-06 06:04
@stefanv it's not a bug, but perhaps `reflect` is a more sensible default for the mode?

**Comment by rougier** [comment] 2015-11-06 06:20
Yes, reflect might be a better default option.

**Comment by soupault** [comment] 2016-10-28 09:23
Closed via #2331.

**Closed by soupault** 2016-10-28 09:23 UTC
Labels: difficulty: novice
