### ISSUE TITLE
scikit-image build fail on "Cython not found"

### ISSUE THREAD

**Issue by lumpofcole** [scikit-image/scikit-image#2373] opened 2016-11-10 23:02 UTC
At work I have a redhat blade that is managed by IT, so I don't have any root access. Also, pip doesn't work due to firewall issues, so my workaround has been to build everything from source using 2 commands...
python setup.py build
python setup.py install --user

The second puts everything into /home/.local

Problem is, I downloaded scikit-image-master because it has some routines that I need that aren't in v. 12, and the build fails. Below is the output from "python setup.py config". I installed Cython in the same way that I installed other modules. Any ideas?

Cython not found; falling back to pre-built geometry.c
Cython not found; falling back to pre-built transform.c
Cython not found; falling back to pre-built interpolation.c
non-existing path in 'skimage/_shared': 'geometry.c'
non-existing path in 'skimage/_shared': 'transform.c'
non-existing path in 'skimage/_shared': 'interpolation.c'
Cython not found; falling back to pre-built _draw.c
non-existing path in 'skimage/draw': '_draw.c'
Cython not found; falling back to pre-built corner_cy.c
Cython not found; falling back to pre-built censure_cy.c
Cython not found; falling back to pre-built orb_cy.c
Cython not found; falling back to pre-built brief_cy.c
Cython not found; falling back to pre-built _texture.c
Cython not found; falling back to pre-built _hessian_det_appx.c
Cython not found; falling back to pre-built _hoghistogram.c
non-existing path in 'skimage/feature': 'corner_cy.c'
non-existing path in 'skimage/feature': 'censure_cy.c'
non-existing path in 'skimage/feature': 'orb_cy.c'
non-existing path in 'skimage/feature': 'brief_cy.c'
non-existing path in 'skimage/feature': '_texture.c'
non-existing path in 'skimage/feature': '_hessian_det_appx.c'
non-existing path in 'skimage/feature': '_hoghistogram.c'
Cython not found; falling back to pre-built _unwrap_1d.c
Cython not found; falling back to pre-built _unwrap_2d.c
Cython not found; falling back to pre-built _unwrap_3d.c
Cython not found; falling back to pre-built _denoise_cy.c
Cython not found; falling back to pre-built _nl_means_denoising.c
non-existing path in 'skimage/restoration': '_unwrap_1d.c'
non-existing path in 'skimage/restoration': '_unwrap_2d.c'
non-existing path in 'skimage/restoration': '_unwrap_3d.c'
non-existing path in 'skimage/restoration': '_denoise_cy.c'
non-existing path in 'skimage/restoration': '_nl_means_denoising.c'
Cython not found; falling back to pre-built _ctmf.c
Cython not found; falling back to pre-built rank/core_cy.c
Cython not found; falling back to pre-built rank/generic_cy.c
Cython not found; falling back to pre-built rank/percentile_cy.c
Cython not found; falling back to pre-built rank/bilateral_cy.c
non-existing path in 'skimage/filters': '_ctmf.c'
non-existing path in 'skimage/filters': 'rank/core_cy.c'
non-existing path in 'skimage/filters': 'rank/generic_cy.c'
non-existing path in 'skimage/filters': 'rank/percentile_cy.c'
non-existing path in 'skimage/filters': 'rank/bilateral_cy.c'
Cython not found; falling back to pre-built _ncut_cy.c
non-existing path in 'skimage/future/graph': '_ncut_cy.c'
Cython not found; falling back to pre-built _spath.c
Cython not found; falling back to pre-built _mcp.c
Cython not found; falling back to pre-built heap.c
non-existing path in 'skimage/graph': '_spath.c'
non-existing path in 'skimage/graph': '_mcp.c'
non-existing path in 'skimage/graph': 'heap.c'
Cython not found; falling back to pre-built _plugins/_colormixer.c _plugins/_histograms.c
non-existing path in 'skimage/io': '_plugins/_colormixer.c'
non-existing path in 'skimage/io': '_plugins/_histograms.c'
Cython not found; falling back to pre-built _ccomp.c
Cython not found; falling back to pre-built _find_contours_cy.c
Cython not found; falling back to pre-built _moments_cy.c
Cython not found; falling back to pre-built _marching_cubes_classic_cy.c
Cython not found; falling back to pre-built _marching_cubes_lewiner_cy.c
Cython not found; falling back to pre-built _pnpoly.c
non-existing path in 'skimage/measure': '_ccomp.c'
non-existing path in 'skimage/measure': '_find_contours_cy.c'
non-existing path in 'skimage/measure': '_moments_cy.c'
non-existing path in 'skimage/measure': '_marching_cubes_classic_cy.c'
non-existing path in 'skimage/measure': '_marching_cubes_lewiner_cy.c'
non-existing path in 'skimage/measure': '_pnpoly.c'
Cython not found; falling back to pre-built _watershed.c
Cython not found; falling back to pre-built _skeletonize_cy.c
Cython not found; falling back to pre-built _convex_hull.c
Cython not found; falling back to pre-built _greyreconstruct.c
Cython not found; falling back to pre-built _skeletonize_3d_cyc
non-existing path in 'skimage/morphology': '_watershed.c'
non-existing path in 'skimage/morphology': '_skeletonize_cy.c'
non-existing path in 'skimage/morphology': '_convex_hull.c'
non-existing path in 'skimage/morphology': '_greyreconstruct.c'
non-existing path in 'skimage/morphology': '_skeletonize_3d_cy.c'
Cython not found; falling back to pre-built _hough_transform.c
Cython not found; falling back to pre-built _warps_cy.c
Cython not found; falling back to pre-built _radon_transform.c
Cython not found; falling back to pre-built _seam_carving.c
non-existing path in 'skimage/transform': '_hough_transform.c'
non-existing path in 'skimage/transform': '_warps_cy.c'
non-existing path in 'skimage/transform': '_radon_transform.c'
non-existing path in 'skimage/transform': '_seam_carving.c'
Cython not found; falling back to pre-built _felzenszwalb_cy.c
non-existing path in 'skimage/segmentation': '_felzenszwalb_cy.c'
Cython not found; falling back to pre-built _quickshift_cy.c
non-existing path in 'skimage/segmentation': '_quickshift_cy.c'
Cython not found; falling back to pre-built _slic.c
non-existing path in 'skimage/segmentation': '_slic.c'
running config

**Comment by jni** [comment] 2016-11-13 01:40
Hi @lumpofcole!

It looks to me like there might be some issues with the way you installed Cython. Sometimes Python can't find locally installed libraries, and you have to manually set up various environment variables, such as PYTHONPATH, to point Python to them.

The first thing I would say is that you can install local files with pip, and probably should. Instead of `python setup.py build; python setup.py install --user`, do `pip install --user .`. You can even use this for binary wheels downloaded directly from PyPI.

Secondly, I recommend working with an environment manager, which should make things like dealing with Python paths less painful. See the Python Packaging user guide:
https://packaging.python.org/

I personally use [conda](http://conda.pydata.org/miniconda.html), but many use virtualenv or venv (these are, confusingly, two different tools) (see Python Packaging, above). The point of these is that they allow user-space install, while correctly setting up PYTHONPATH, LD_LIBRARY_PATH, and other environment variables for you.

I don't know exactly where your install is going wrong, but I hope the above tools and links will help. Please report back here if any of the above tools solved your problem! Or ask again if they didn't.

**Comment by lumpofcole** [comment] 2016-11-16 18:21
I can't use pip due to firewall issues. The only workaround I and others have found is to do the local install like I described it. I have to work within that context unfortunately.

**Comment by jni** [comment] 2016-11-16 22:53
@lumpofcole pip can work without internet access, using files downloaded manually from PyPI or elsewhere. `pip install --user --no-deps <dirname>` installs the Python package in the `<dirname>` directory (use `.` for current working directory), *without accessing the internet*. Similarly, if you download a `.whl` file from [Cython's PyPI page](https://pypi.python.org/pypi/Cython/), you can do `pip install --user --no-deps <.whl>` to install that file (I think, haven't tried this).

**Comment by soupault** [comment] 2017-04-09 08:14
Closing as not a bug. Feel free to cotinue the discussion here.

**Closed by soupault** 2017-04-09 08:14 UTC

**Comment by tutu-kang** [comment] 2021-09-10 18:50
I meet this problem again and solved this problem.  python setup didn't compile the related files. You need to manually compile these missed files again. 

Solution:

cd skimage/_shared 
cython geometry.pyx
cython transform.pyx
cython interpolation.pyx

python setup build_ext -i 

After that,  Recompile and install again. Thanks.
