### ISSUE TITLE
peak_local_max does not find all local maxima

### ISSUE THREAD

**Issue by funkey** [scikit-image/scikit-image#1832] opened 2015-12-16 15:33 UTC
When running `peak_local_max` on the following image (distance transform of binary image, isolines in same color):
![fn_distance](https://cloud.githubusercontent.com/assets/776708/11845026/05fb546c-a412-11e5-96c5-749f64525540.png)
via

``` python
maxima = master_peak_local_max(distance, min_distance=10, threshold_abs=0, threshold_rel=0, indices=False)
```

I get the following result:
![fn_maxima](https://cloud.githubusercontent.com/assets/776708/11845052/2be21d78-a412-11e5-8a31-08a6e22b02f4.png)

The local maximum in the center was not found. They are further away from each other than `2*min_distance+1` (21) pixels.

Example image to reproduce: https://www.dropbox.com/s/2e7yfnuiirms36w/distance.tif?dl=0

**Comment by soupault** [comment] 2016-02-06 11:54
Code to reproduce with region specified above:

```
import matplotlib
import matplotlib.pyplot as plt

import skimage
from skimage import io
from skimage.feature import peak_local_max

distance = io.imread('./distance.tif')
distance = distance[730:800, 440:561]  # Issue #1832

maxima = peak_local_max(distance, min_distance=10, threshold_abs=0, threshold_rel=0, indices=False)

fig, axes = plt.subplots(nrows=1, ncols=2)
axes[0].imshow(distance, interpolation='none',cmap='coolwarm')
axes[1].imshow(maxima, interpolation='none', cmap='gray')
plt.tight_layout()
plt.savefig('test_img.png')
plt.close()
```
![test_img_1832](https://cloud.githubusercontent.com/assets/1315589/12866513/73c3b3b6-cce1-11e5-8923-25bb7ad47e82.png)

**Comment by ahojnnes** [comment] 2016-02-06 11:57
What happens when you do `exclude_border=False`?

**Comment by soupault** [comment] 2016-02-06 12:01
@ahojnnes 
![test_img_1832_exclude](https://cloud.githubusercontent.com/assets/1315589/12866550/838c7b10-cce2-11e5-8256-8ea771dc4e19.png)

**Comment by ahojnnes** [comment] 2016-02-06 12:15
Seems to be doing the right thing?

**Comment by soupault** [comment] 2016-02-06 12:29
I'd expect as @funkey does the "inner island" peak to be detected, as it is really >21 pixels further from any marked one:
![test_img](https://cloud.githubusercontent.com/assets/1315589/12866647/70107f06-cce6-11e5-8f45-02077fbdddb9.png)

**Comment by ahojnnes** [comment] 2016-02-06 12:41
You are right. Note sure why this is happening...

**Comment by soupault** [comment] 2016-02-06 12:50
Ok, I think this case is really not a bug. Here is 21px rectangle:
![figure_1](https://cloud.githubusercontent.com/assets/1315589/12866715/3acac858-cce9-11e5-9cc0-f33274d956eb.png)
Please, close the issue if you're agree.

**Comment by ahojnnes** [comment] 2016-02-06 12:56
You need to draw the 10px box around the smaller corner. If any other pixel in that box has a greater value, then it is not a peak. This seems to be the case here, when looking at the zoomed-in version. I would close this issue as the function seems to behave correctly.

**Comment by soupault** [comment] 2016-02-06 13:04
True, that "island peak" and upperleft pixel in corresponding bounding frame have the same value:
![figure_1](https://cloud.githubusercontent.com/assets/1315589/12866769/2d9c7850-cceb-11e5-829b-bbc950873448.png)

**Comment by ahojnnes** [comment] 2016-02-06 13:22
I'll close this issue for now, @funkey feel free to reopen if you disagree!

**Comment by soupault** [comment] 2016-02-06 13:27
@ahojnnes , enough said :+1: :
![1832](https://cloud.githubusercontent.com/assets/1315589/12866871/763c4a42-ccee-11e5-89f0-532daa2bb4dc.png)

**Comment by jni** [comment] 2016-02-07 05:42
@ahojnnes @soupault If this is truly the expected behavior, then the docstring needs updating. Just like @funkey, I expected that *peaks* should be > 21 pixels apart, not some random slope. The docstring is very unclear about this.

**Comment by soupault** [comment] 2016-02-07 08:42
@jni the algorithm is quite simple itself, but is hard really to give it a short description which covers all presented cases without going into the details.
As it was said above, firstly I really expected the same behaviour as @funkey , but once I had a look at the code - the expectation did get changed.
We're trying to address #1831 and this issue in https://github.com/scikit-image/scikit-image/pull/1932 , feel free to join the discussion there.

**Comment by ahojnnes** [comment] 2016-02-07 10:48
@jni @soupault I agree that the doc string is unclear. You are welcome to join the discussion there.

**Comment by rfezzani** [comment] 2020-02-20 13:42
#3600 fixes this issue. Closing ;-)

**Closed by rfezzani** 2020-02-20 13:42 UTC
Labels: type: bug
