### ISSUE TITLE
 module 'skimage.future.graph' has no attribute 'show_rag'

### ISSUE THREAD

**Issue by franktoffel** [scikit-image/scikit-image#2363] opened 2016-10-31 19:43 UTC
I am trying to follow [this example](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_rag_boundary.html#sphx-glr-auto-examples-segmentation-plot-rag-boundary-py):

```python
from skimage.future import graph
from skimage import data, segmentation, color, filters, io
from matplotlib import pyplot as plt


img = data.coffee()
gimg = color.rgb2gray(img)

labels = segmentation.slic(img, compactness=30, n_segments=400)
edges = filters.sobel(gimg)
edges_rgb = color.gray2rgb(edges)

g = graph.rag_boundary(labels, edges)
lc = graph.show_rag(labels, g, edges_rgb, img_cmap=None, edge_cmap='viridis',
                    edge_width=1.2)

plt.colorbar(lc, fraction=0.03)
io.show()
```

But I get this error when executing it:

`AttributeError: module 'skimage.future.graph' has no attribute 'show_rag'`

I am running scikit image 0.12.3 installed via conda on a windows 7 machine.

Is this example only working for the dev version?

Thanks

**Comment by JDWarner** [comment] 2016-10-31 19:48
This function had its name changed in #1872, from draw_rag to show_rag, after 0.12.3 was released.

You could try substituting draw_rag, though I'm not sure if that was shipped in 0.12.3 either.  Don't have the time to follow things further back.

**Comment by franktoffel** [comment] 2016-10-31 20:32
show_rag is available in this version but removing key arguments (since they differ) and running now:

`lc = graph.draw_rag(labels, g, edges_rgb)`

It returns the following error while plotting:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-975366e4c63f> in <module>()
     14 lc = graph.draw_rag(labels, g, edges_rgb)
     15 
---> 16 plt.colorbar(lc, fraction=0.03)
     17 io.show()

C:\Users\...\Miniconda3\lib\site-packages\matplotlib\pyplot.py in colorbar(mappable, cax, ax, **kw)
   2242         ax = gca()
   2243 
-> 2244     ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
   2245     return ret
   2246 colorbar.__doc__ = matplotlib.colorbar.colorbar_doc

C:\Users\...\Miniconda3\lib\site-packages\matplotlib\figure.py in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   1591                 cax, kw = cbar.make_axes(ax, **kw)
   1592         cax.hold(True)
-> 1593         cb = cbar.colorbar_factory(cax, mappable, **kw)
   1594 
   1595         self.sca(current_ax)

C:\Users\...\Miniconda3\lib\site-packages\matplotlib\colorbar.py in colorbar_factory(cax, mappable, **kwargs)
   1328         cb = ColorbarPatch(cax, mappable, **kwargs)
   1329     else:
-> 1330         cb = Colorbar(cax, mappable, **kwargs)
   1331 
   1332     cid = mappable.callbacksSM.connect('changed', cb.on_mappable_changed)

C:\Users\...\Miniconda3\lib\site-packages\matplotlib\colorbar.py in __init__(self, ax, mappable, **kw)
    878         # Ensure the given mappable's norm has appropriate vmin and vmax set
    879         # even if mappable.draw has not yet been called.
--> 880         mappable.autoscale_None()
    881 
    882         self.mappable = mappable

AttributeError: 'numpy.ndarray' object has no attribute 'autoscale_None'
```

I'll try to find out a solution tomorrow.

**Comment by JDWarner** [comment] 2016-10-31 20:49
Ah, the old draw_rag drew (as in, burned in an overlay) into the input and returned that as a new image.  The show_rag on master now uses Matplotlib to plot over top of the raw data, and returns a Matplotlib linecollection object after making the plot which can be modified further by the user.

Different approach (new is better), but that's why this is failing.  That colorbar call expects lc to be a figure or axis. 

As an aside, I think this function should be further improved to return three outputs: the Matplotlib figure, axis, and the linecollection rather than just the linecollection.

**Comment by franktoffel** [comment] 2016-11-01 18:02
Ok, for what is worth, I found the code for the current stable release in the branch [v0.12.x](https://github.com/scikit-image/scikit-image/blob/v0.12.x/doc/examples/segmentation/plot_rag_boundary.py):

I leave it here in case someone else finds this issue in the meantime:
```python
from skimage.future import graph
from skimage import data, segmentation, color, filters, io
from skimage.util.colormap import viridis


img = data.coffee()
gimg = color.rgb2gray(img)

labels = segmentation.slic(img, compactness=30, n_segments=400)
edges = filters.sobel(gimg)
edges_rgb = color.gray2rgb(edges)

g = graph.rag_boundary(labels, edges)

out = graph.draw_rag(labels, g, edges_rgb, node_color="#999999",
                     colormap=viridis)

io.imshow(out)
io.show()

```

**Comment by soupault** [comment] 2016-11-01 18:13
@franktoffel good! I suppose that solves the issue for you.
Closing as not a bug.

**Closed by soupault** 2016-11-01 18:13 UTC
Labels: status: invalid
