### ISSUE TITLE
convert binary image back to original image

### ISSUE THREAD

**Issue by singhsugandha3** [scikit-image/scikit-image#6423] opened 2022-06-20 09:30 UTC
how to convert binary image into an original image using python?

**Comment by mkcor** [comment] 2022-07-11 07:35
Dear @singhsugandha3,

It seems that your question would belong rather in the user forum: https://forum.image.sc/tag/scikit-image

PS : It would be helpful if you could specify what you mean exactly by 'original image' and 'binary image.'

**Comment by soupault** [comment] 2022-07-28 13:32
Hi @singhsugandha3,

If you have any questions on using the library, please post them to the forum above. Please, also provide there more details on your setting (example input/output data), what is the expected behaviour, what you have already tried, etc. This GitHub repo is primarily intended for the library development.

I am closing the issue, but feel free to reopen if you think you have found a bug or have a proposal to discuss.

**Closed by soupault** 2022-07-28 13:32 UTC
