### ISSUE TITLE
ImportError: cannot import name shape_index

### ISSUE THREAD

**Issue by fayazr** [scikit-image/scikit-image#2336] opened 2016-10-09 13:56 UTC
Cannot import  shape_index from feature (from skimage.feature import shape_index), when running the example.

**Comment by soupault** [comment] 2016-10-09 14:09
Hi @fayazr! This feature is new and hasn't yet been released (i.e. `skimage` 0.12.3 doesn't have it). Are you sure that you are using 0.13dev?

**Comment by fayazr** [comment] 2016-10-09 15:16
Oh ok, how do I install 0.13dev in enthought canopy environment. Thanks.

**Comment by soupault** [comment] 2016-10-09 15:25
@fayazr I don't think you can do this in Canopy. You might follow the traditional approach (http://scikit-image.org/docs/dev/install.html#running-the-development-version) though and Canopy will probably figure everything out.

Closing as not a bug. Feel free to continue discussion here.

**Closed by soupault** 2016-10-09 15:25 UTC
