### ISSUE TITLE
local_minima output wrong with numpy 2.0.2

### ISSUE THREAD

**Issue by haesleinhuepf** [scikit-image/scikit-image#7530] opened 2024-09-06 10:17 UTC
### Description:

I all, I just saw a regression in some code I maintain. In [this notebook](https://github.com/haesleinhuepf/human-eval-bia/blob/b64f34e5ad0330695337bbe7b6f5176ef83dcb0f/test_cases/workflow_watershed_segmentation_correction_measurement.ipynb) we use skimage.morphology.local_minima . Depending on installed numpy-version, the output is different. 

### Way to reproduce:

I think an environment with scikit-image and numpy should be sufficient. I was using [this conda environment](https://github.com/haesleinhuepf/human-eval-bia/blob/main/environment.yml) for testing.

Execute this code:
```python
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')

import skimage
import numpy as np
image = np.asarray([
 [1,1,1,1],
 [1,0,0,1],
 [1,0,0,1],
 [1,1,1,1],    
])

blurred = skimage.filters.gaussian(image, sigma=1)
minima = skimage.morphology.local_minima(blurred)
print(minima)
```

When numpy 1.26.4 was installed, that's the output:
```
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
scikit-image version: 0.24.0
numpy version: 1.26.4
[[False False False False]
 [False  True  True False]
 [False  True  True False]
 [False False False False]]
```

With numpy 2.0.2, the output changes, local_minima doesn't work anymore as described in its docstring ("The local minima are defined as connected sets of pixels with equal gray level (plateaus) strictly smaller than the gray levels of all pixels in the neighborhood.").

```
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
scikit-image version: 0.24.0
numpy version: 2.0.2
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
```

### Version information:

```Shell
see above
```

**Comment by lagru** [comment] 2024-09-06 11:12
Thanks for the report @haesleinhuepf! While I can easily reproduce the second output that returns `minima` that's `False` everywhere, I can't reproduce the first one. Even when using the exact Python, NumPy and scikit-image version from your snippet I get:

```
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Linux-6.10.7-arch1-1-x86_64-with-glibc2.40
scikit-image version: 0.24.0
numpy version: 1.26.4
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
```

Some investigation leads me to believe, `skimage.filters.gaussian` might be the actual culprit here. You are passing in an integer array which get's rescaled to a float array with near zero values. Could you confirm that the input dtype of `image` in the example is actually `np.int64` and what you are seeing in your notebook environment as well?

**Comment by haesleinhuepf** [comment] 2024-09-06 12:42
Confirmed @lagru ! The image dtype is `int32` in the one and `int64` in the other case. And Gaussian-blur has different output too.

I would argue though that the inner 4 pixels are surrounded by higher values. Thus, `local_minima` should return True in these four. See outputs below.

Code:
```python
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')

import skimage
import numpy as np
image = np.asarray([
 [1,1,1,1],
 [1,0,0,1],
 [1,0,0,1],
 [1,1,1,1],    
])

print("image", image.dtype)

blurred = skimage.filters.gaussian(image, sigma=1)
print("blurred", blurred, blurred.dtype)

minima = skimage.morphology.local_minima(blurred)
print("minima", minima, minima.dtype)
```

Output using numpy 1.26.4: 
```
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
scikit-image version: 0.24.0
numpy version: 1.26.4
image int32
blurred [[4.24872225e-10 3.77331475e-10 3.77331475e-10 4.24872225e-10]
 [3.77331475e-10 2.74380703e-10 2.74380703e-10 3.77331475e-10]
 [3.77331475e-10 2.74380703e-10 2.74380703e-10 3.77331475e-10]
 [4.24872225e-10 3.77331475e-10 3.77331475e-10 4.24872225e-10]] float64
minima [[False False False False]
 [False  True  True False]
 [False  True  True False]
 [False False False False]] bool
```

Output using numpy 2.0.2: 
```
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
scikit-image version: 0.24.0
numpy version: 2.0.2
image int64
blurred [[9.89232736e-20 8.78543302e-20 8.78543302e-20 9.89232736e-20]
 [8.78543302e-20 6.38842355e-20 6.38842355e-20 8.78543302e-20]
 [8.78543302e-20 6.38842355e-20 6.38842355e-20 8.78543302e-20]
 [9.89232736e-20 8.78543302e-20 8.78543302e-20 9.89232736e-20]] float64
minima [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]] bool
```

**Comment by michaelbratsch** [comment] 2024-09-07 13:43
The `local_minima` routine dispatches to `local_maxima` with the inverted image
https://github.com/scikit-image/scikit-image/blob/37de01c9b1c4baa7fd85035d534fe28f7a4fb539/skimage/morphology/extrema.py#L543

The inversion itself
https://github.com/scikit-image/scikit-image/blob/37de01c9b1c4baa7fd85035d534fe28f7a4fb539/skimage/util/_invert.py#L73
returns an array of exact ones for the `int64` because it falls under the rounding precision for floating point due to the subtraction with one.

The inversion we need is to just flip the sign, that is numerically stable and we should still be able to use the dispatching to `local_maxima`:
https://github.com/scikit-image/scikit-image/blob/37de01c9b1c4baa7fd85035d534fe28f7a4fb539/skimage/util/_invert.py#L71

Using `signed_float=True` for 
https://github.com/scikit-image/scikit-image/blob/37de01c9b1c4baa7fd85035d534fe28f7a4fb539/skimage/morphology/extrema.py#L544
does the trick.

I can open a pull-request to provide this simple fix.

**Comment by lagru** [comment] 2024-09-28 16:37
Fixed in https://github.com/scikit-image/scikit-image/pull/7534.

**Closed by lagru** 2024-09-28 16:37 UTC
Labels: :bug: Bug
