### ISSUE TITLE
pytest.importorskip breaks skimage.lookfor

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#6548] opened 2022-09-28 04:47 UTC
## Description

It looks like `skimage.lookfor` fails when we don't have all optional dependencies installed:

```pytb
In [43]: skimage.lookfor('peak_local_max')
---------------------------------------------------------------------------
Skipped                                   Traceback (most recent call last)
Input In [43], in <cell line: 1>()
----> 1 skimage.lookfor('peak_local_max')

File ~/conda/envs/all/lib/python3.10/site-packages/skimage/util/lookfor.py:24, in lookfor(what)
      5 def lookfor(what):
      6     """Do a keyword search on scikit-image docstrings.
      7
      8     Parameters
   (...)
     22         Find `n_points` regularly spaced along `ar_shape`.
     23     """
---> 24     return np.lookfor(what, sys.modules[__name__.split('.')[0]])

File ~/conda/envs/all/lib/python3.10/site-packages/numpy/lib/utils.py:738, in lookfor(what, module, import_modules, regenerate, output)
    735 import pydoc
    737 # Cache
--> 738 cache = _lookfor_generate_cache(module, import_modules, regenerate)
    740 # Search
    741 # XXX: maybe using a real stemming search engine would be better?
    742 found = []

File ~/conda/envs/all/lib/python3.10/site-packages/numpy/lib/utils.py:900, in _lookfor_generate_cache(module, import_modules, regenerate)
    898     sys.stdout = StringIO()
    899     sys.stderr = StringIO()
--> 900     __import__("%s.%s" % (name, to_import))
    901 finally:
    902     sys.stdout = old_stdout

File ~/conda/envs/all/lib/python3.10/site-packages/skimage/io/tests/test_fits.py:5, in <module>
      2 import skimage.io as io
      3 from skimage._shared import testing
----> 5 testing.pytest.importorskip('astropy')
      6 from astropy.io import fits
      7 import skimage.io._plugins.fits_plugin as fplug

File ~/conda/envs/all/lib/python3.10/site-packages/_pytest/outcomes.py:292, in importorskip(modname, minversion, reason)
    290         if reason is None:
    291             reason = f"could not import {modname!r}: {exc}"
--> 292         raise Skipped(reason, allow_module_level=True) from None
    293 mod = sys.modules[modname]
    294 if minversion is None:

Skipped: could not import 'astropy': No module named 'astropy'
```

**Comment by lagru** [comment] 2022-09-28 09:19
Thanks, I can reproduce although in my case with a different missing dependency 

```python
  ...
  File ".../scikit-image/skimage/io/tests/test_simpleitk.py", line 11, in <module>
    importorskip('SimpleITK')
  File ".../miniconda3/envs/scikit-image-dev/lib/python3.10/site-packages/_pytest/outcomes.py", line 292, in importorskip
    raise Skipped(reason, allow_module_level=True) from None
Skipped: could not import 'SimpleITK': No module named 'SimpleITK'
```
Not sure where this should be addressed but I think this happens because the underlying [`numpy.lookfor`](https://numpy.org/doc/stable/reference/generated/numpy.lookfor.html) only [anticipates `Exception` and `SystemExit`](https://github.com/numpy/numpy/blob/main/numpy/lib/utils.py#L965-L977). But because pytest's `Skipped` is not a subclass of either it is not caught:

```python
from _pytest.outcomes import Skipped
assert issubclass(Skipped, Exception) is False
assert issubclass(Skipped, BaseException) is True
```

I'll open an issue over at NumPy to see whether this should be addressed there.

**Comment by lagru** [comment] 2022-09-28 17:44
Hmm, note that this only happens if pytest is installed. Otherwise a `ModuleNotFoundError` is raised for pytest which numpy's lookfor can deal with.

> can we filter away the "tests" subdirectories?

I don't see a non-hacky or non-convoluted way to do that. Maybe we could use our own patched version of `importorskip` which raises an Exception that inherits from both Exception and pytest's `Skipped`. Still investigating.

**Comment by lagru** [comment] 2022-10-03 16:40
Fixed in https://github.com/numpy/numpy/pull/22356 but may take a little while until it is available for us. Note that their are also considering deprecating that function alltogether...

**Closed by lagru** 2022-10-03 16:40 UTC
Labels: :bug: Bug, :arrow_up: Upstream
