### ISSUE TITLE
skimage.resize bug with ints

### ISSUE THREAD

**Issue by vanpact** [scikit-image/scikit-image#2702] opened 2017-07-13 08:27 UTC
Hi,
Enlarging a 3d numpy array with dtype=np.int using skimage.resize (mode='edge') gives me a float output with all the values close to 0. This is a weird behaviour. 

workaround: convert the image to float before calling the function and convert back to int after the function call

proposal: make this conversion internally?

Software version:
Windows 10 x64
python 3.5 x64
skimage version: 0.13
numpy 1.13

**Comment by soupault** [comment] 2017-07-13 10:52
@vanpact could you give us an example of array you are trying to resize? The behaviour might depend on dtype and value range of the input.

**Comment by vanpact** [comment] 2017-07-13 11:55
`import numpy as np`
`from skimage.transform import resize`
`vec = np.ones((480, 480, 3), dtype=np.int)*40`
`vec2 = resize(vec, (736, 736, 3), mode='edge')`
`print(np.max(v2))`

result: 6.98491...e-10

**Comment by emmanuelle** [comment] 2017-07-13 21:57
Thank you, this is bad :-(. Hope we have time to address this bug during the sprint.

**Comment by jni** [comment] 2017-07-14 08:10
I'm not sure this is a bug, but rather unexpected behaviour in conversion to float because of our [dtype ranges](http://scikit-image.org/docs/dev/user_guide/data_types.html):

```python
In [1]: from skimage import img_as_float

In [2]: img_as_float(np.array([[40, 40], [40, 40]], dtype=int))
/Users/jni/projects/scikit-image/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from int64 to float64
  .format(dtypeobj_in, dtypeobj_out))
Out[2]:
array([[  4.39101880e-18,   4.39101880e-18],
       [  4.39101880e-18,   4.39101880e-18]])

In [3]: 40 / 2**63
Out[3]: 4.336808689942018e-18

In [4]: 40 / 2**31
Out[4]: 1.862645149230957e-08
```

Overhauling the dtype conventions is a good idea (we get lots of questions and bug reports related to it), but probably too ambitious a goal for the sprint. ;)

**Comment by jni** [comment] 2017-07-14 08:12
Incidentally, we have a workaround in place: use the keyword argument `preserve_range=True`. See the documentation here:
http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize

**Comment by soupault** [comment] 2018-05-07 17:04
I'm closing this issue as the provided behaviour is inline with our dtype conventions. If you have any improvement suggestions, feel free to contribute to the discussion in https://github.com/scikit-image/scikit-image/issues/3009 .

**Closed by soupault** 2018-05-07 17:04 UTC
Labels: type: bug

**Comment by jni** [comment] 2018-05-08 00:11
@vanpact to clarify @soupault's comment: this is how dtype conventions currently work (see documentation [here](http://scikit-image.org/docs/dev/user_guide/data_types.html)), but we are aware that this is surprising behaviour and are working to change it. (See discussion in #3009 as linked by @soupault.) Thanks for reporting, and watch #3009 for news of a resolution. I hope `preserve_range` works for you in the meantime!
