### ISSUE TITLE
Error installing scikit-image

### ISSUE THREAD

**Issue by leon089y** [scikit-image/scikit-image#4720] opened 2020-05-14 09:43 UTC
I have error during install scikit-image. I am using: python version - 3.6.9, Ubuntu - 18.04
I execute in command line: pip3 install  scikit-image.
In result a have error (bellow on image). How to fix the error?
![Снимок экрана от 2020-05-14 12-33-41](https://user-images.githubusercontent.com/65338598/81918818-aa8f8700-95df-11ea-9492-d7b1ce5f0e48.png)

**Comment by rfezzani** [comment] 2020-05-14 09:49
This is duplicate of #4673.
Please refer to @hmaarrfk https://github.com/scikit-image/scikit-image/issues/4673#issuecomment-626382017 for a solution.

**Closed by rfezzani** 2020-05-14 09:49 UTC

**Comment by rfezzani** [comment] 2020-05-14 10:07
@leon089y, feel free to reopen the issue if you need more help ;)
