### ISSUE TITLE
skimage.io.imread prints stacktrace even if try ... except block:

### ISSUE THREAD

**Issue by MaxNoe** [scikit-image/scikit-image#1772] opened 2015-11-06 17:51 UTC
Consider this minimal example:
```
from skimage import io
try:
    io.imread('foo.png')
except:
    pass
```

If foo.png is not readable, the output is:

```
%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/IptcImagePlugin.py", line 113, in _open
    layers = i8(self.info[(3, 60)][0])
KeyError: (3, 60)
%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 71, in _open
    if s.read(32) != 0x1B3:
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 53, in read
    v = self.peek(bits)
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 38, in peek
    c = self.next()
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 34, in next
    return i8(self.fp.read(1))
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/deflicker/lib/python3.5/site-packages/PIL/TgaImagePlugin.py", line 57, in _open
    idlen = i8(s[0])
IndexError: index out of range
```

**Comment by blink1073** [comment] 2015-11-09 16:35
Hi @MaxNoe, what version of skimage are you using?  What do you mean the image is `not readable`, as in corrupt?  Can you provide the file?

**Comment by MaxNoe** [comment] 2015-11-09 17:14
The one that comes from with conda at the moment. I can check later.   For the example I just did `touch foo.png `.

**Comment by stefanv** [comment] 2015-11-09 17:35
I can reproduce this.

**Comment by blink1073** [comment] 2015-11-09 21:40
Okay, I can reproduce (only with Python 3.5).  I looked and we're not trapping and printing any errors in our plugin, I think this is actually a bug in PIL.

**Comment by stefanv** [comment] 2015-11-09 22:26
Max, will you please file this against PIL, if it is still visible against the latest version?  Here's the code snippet to reproduce:

```
In [4]: try:
   ...:     Image.open('foo.png')
   ...: except:
   ...:     pass
```

**Comment by MaxNoe** [comment] 2015-11-09 22:34
Yes, can reproduce this with:
```
from PIL import Image
try:
    Image.open('foo.png')
except:
    print('Catched Exception')
```
This prints the traceback and 'Catched Exeption'.
I'm using anaconda 2.4 with pillow 3.0.0.

**Comment by stefanv** [comment] 2015-11-09 22:43
Max, remember to describe the problem on #1532 as well, i.e. that you are seeing an exception printed where you shouldn't.

**Comment by MaxNoe** [comment] 2015-11-09 22:45
Are you sure you mentioned the correct commit? There seems to be no connection to me.

**Comment by stefanv** [comment] 2015-11-10 02:40
Fixed, thanks.

**Comment by stefanv** [comment] 2015-12-10 19:51
Since this is being fixed on the PIL side, I'm closing.

**Closed by stefanv** 2015-12-10 19:51 UTC
