### ISSUE TITLE
win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True.

### ISSUE THREAD

**Issue by cy19980615** [scikit-image/scikit-image#4636] opened 2020-05-02 04:11 UTC
my code:
 x_reconst = self.G(x_fake, c_org)
 score= structural_similarity(x_real, x_reconst,multichannel=True)
 g_loss_rec = 1 - score

with error:
ValueError
win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True.

and in terminal:
UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "

how to deal with it ? thanks so much

**Comment by soupault** [comment] 2020-05-02 06:27
@cy19980615 hi, what shapes do `x_real` and `x_reconstr` have in your example?

**Comment by cy19980615** [comment] 2020-05-02 06:52
> @cy19980615 hi, what shapes do x_real and x_reconstr have in your example?

shape is（16，3，128，128），but i make the Normalized to the input images , is it make the error?

**Comment by soupault** [comment] 2020-05-02 07:27
I see. Please, double check https://scikit-image.org/docs/dev/api/skimage.metrics.html#skimage.metrics.structural_similarity . Particularly, it says that "multichannel: If True, treat the _last_ dimension of the array as channels.". In your arrays of (16, 3, 128, 128), the first three dimensions are considered as _spatial_ and the last one (128,) - as _channels_ (since you set `multichannel` to True). Since the second dimension has lenght of 3, it is, most likely, smaller than the default `win_size`.

So, to run `structural_similarity` on your data, you will need to:
1. Convert the inputs to numpy ndarrays, since `scikit-image` does not support pytorch tensors by design
2. Move the axis (3, ) to the end, e.g. `np.moveaxis(arr, 1, -3)`
3. Process each sample from the batch independently, since, I assume, you do not want to thread that dimension as spatial either.

On a side note, `structural_similarity` is implemented for numpy arrays only and it probably should not be used in pytorch pipeline, where one needs to have a pytorch-based differentiable function. Probably, what you are looking for is https://github.com/pytorch/pytorch/issues/6934 .

I am going to close this tickets as I see no issue here on `scikit-image` side.

**Closed** 2020-05-02 07:28 UTC
Labels: status: needs info

**Comment by cy19980615** [comment] 2020-05-02 08:55
> I see. Please, double check https://scikit-image.org/docs/dev/api/skimage.metrics.html#skimage.metrics.structural_similarity . Particularly, it says that "multichannel: If True, treat the last dimension of the array as channels.". In your arrays of (16, 3, 128, 128), the first three dimensions are considered as spatial and the last one (128,) - as channels (since you set multichannel to True). Since the second dimension has lenght of 3, it is, most likely, smaller than the default win_size.
> So, to run structural_similarity on your data, you will need to:
> 
> Convert the inputs to numpy ndarrays, since scikit-image does not support pytorch tensors by design
> Move the axis (3, ) to the end, e.g. np.moveaxis(arr, 1, -3)
> Process each sample from the batch independently, since, I assume, you do not want to thread that dimension as spatial either.
> 
> On a side note, structural_similarity is implemented for numpy arrays only and it probably should not be used in pytorch pipeline, where one needs to have a pytorch-based differentiable function. Probably, what you are looking for is pytorch/pytorch#6934 .
> I am going to close this tickets as I see no issue here on scikit-image side.

thanks very much
