### ISSUE TITLE
Lineprofile plugin misbehaves with CollectionViewer from skimage.viewer

### ISSUE THREAD

**Issue by pskeshu** [scikit-image/scikit-image#2310] opened 2016-09-19 07:00 UTC
## Description

To view multiple image stacks, especially microscope z stack images, CollectionViewer is very useful, as there's a slider which is makes it easy to navigate through the z stack of images. 

There's a neat handy plugin to draw a line and get the intensity values along the line in skimage.viewer.plugins called lineprofile. 

When used with CollectionViewer, the lineprofile shows the profile for a selected region, however, as I move through the different frames in CollectionViewer, the plot that shows the lineprofile data remains unchanged. It doesn't appear to adapt to the new frame on top of which the lines lies as the image shown by the CollectionViewer is changed.
## Test code:

```
def show_collection(images):
    from skimage.viewer import CollectionViewer
    new_viewer = viewer.CollectionViewer(images)
    from skimage.viewer.plugins import lineprofile
    new_viewer += lineprofile.LineProfile()
    new_viewer.show()
```

Pass any grey-scale image stack to the `show_collection()` to test this.  
## OS and software version:

```
Linux darwin 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 

GNU/LinuxPython 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2

>>> skimage.__version__
'0.13dev'
```

**Comment by jni** [comment] 2016-10-21 04:29
@pskeshu I'm not sure this is unexpected behaviour... Unfortunately the viewer is a rather neglected part of the code base. Do other plugins update correctly when you do this?

My guess is that you need to somehow hook up the lineprofile call to the slider...

**Comment by mkcor** [comment] 2022-01-06 10:40
Dear @pskeshu,

I'll close this issue since we have now removed the viewer module (#6160).

We recommend that you use other libraries, which specialize in viewing multi-dimensional images interactively, such as Napari: https://github.com/Napari/napari

All the best,
Marianne

**Closed by mkcor** 2022-01-06 10:40 UTC
Labels: type: bug, module: viewer
