### ISSUE TITLE
 error message: ImportError: cannot import name 'img_as_float32' 

### ISSUE THREAD

**Issue by YubinXie** [scikit-image/scikit-image#3821] opened 2019-03-28 23:04 UTC
## Description
When import skimage it shows  ImportError: cannot import name 'img_as_float32' 

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
import skimage.io
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))


```

```python
3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Darwin-18.2.0-x86_64-i386-64bit
scikit-image version: 0.14.2
numpy version: 1.16.1
```

**Comment by YubinXie** [comment] 2019-03-28 23:23
But it seems numpy version 1.4.3, 1.16.2 work.

**Comment by soupault** [comment] 2019-03-30 09:06
I cannot reproduce on MacOS in Docker with exactly the same versions.

@YubinXie good that your make it work! I'm going to close the issue as it seems to be related to the inconsistency of the environment (see also https://github.com/scikit-image/scikit-image/issues/3788), but feel free to re-open if you face it again.

**Closed by soupault** 2019-03-30 09:06 UTC

**Comment by Pumking-cn** [comment] 2019-04-15 20:58
I tried the commands above, but it seems the problem still exists.
<img width="732" alt="Screen Shot 2019-04-15 at 2 37 48 PM" src="https://user-images.githubusercontent.com/25112842/56164894-abe71e00-5f9f-11e9-8868-b442f04e20bc.png">

**Comment by hmaarrfk** [comment] 2019-04-16 00:39
With these support issues, I really prefer you open a new issue.

Finally, 3.5 is pretty old and I would recommend you upgrade.

**Comment by YubinXie** [comment] 2019-04-16 01:31
Your numpy version is not shown here. Change numpy version to 1.4.3 and restart your jupyter. Then to see if it works.

**Comment by YubinXie** [comment] 2019-05-29 21:56
I met this error again in my new python environment where numpy version is '1.16.4'. 

I think 0.14.2 skimage does not work with newest numpy, e.g., 1.16.x.

**Comment by jni** [comment] 2019-05-29 23:16
@YubinXie can you specify your full new Python environment? (Python version, NumPy version, skimage version, *and how skimage was installed*) both 0.14.2 and 0.15 should work with the latest NumPy.

**Comment by YubinXie** [comment] 2019-05-30 05:00
Python 3.6; NumPy 1.16.4; Skimage 0.14.2. 

I installed them with conda.

**Comment by jni** [comment] 2019-05-31 08:43
@YubinXie there must be something wrong with your environment, or are you running this in a directory that includes a directory called `skimage`? I've created two brand new environments:

```
conda create -n skimage-3821-defaults --channel defaults python=3.6 numpy=1.16.4 scikit-image=0.14.2
```

and 

```
conda create -n skimage-3821-cf --channel conda-forge python=3.6 numpy=1.16.4 scikit-image=0.14.2
```

And in both cases I can import and use scikit-image just fine...

Unfortunately it's quite easy to break an environment when combining conda and pip these days, or conda using different channels...
