### ISSUE TITLE
Sigma value(s) for wavelet denoising

### ISSUE THREAD

**Issue by MOAMSA** [scikit-image/scikit-image#6466] opened 2022-08-11 18:33 UTC
Hello,
I have an image with anisotropic voxel. Do we need to reflect this in the sigma value (in x, y and z directions) that will be used to compute the wavelet detail coefficient thresholds?

I tried but it returns an error in the line
https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/restoration/_denoise.py#L677

Thanks,

**Comment by mkcor** [comment] 2022-08-13 07:39
Dear @MOAMSA,

Could you please paste your code as well as the error you got, so we can check if it's a bug? Thanks!

**Comment by MOAMSA** [comment] 2022-08-15 17:38
Here is the code:
```
   import skimage
    import numpy as np
    volume = np.random.randint(0, 256, size=(128, 1024, 64), dtype=np.uint8)
    volume_denoised = skimage.restoration.denoise_wavelet(volume, sigma=np.array([1.0, 2.0, 3.0]),
                                                          multichannel=False, convert2ycbcr=False, )
```
Error:
`(<class 'ValueError'>, ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'), <traceback object at 0x00000196542CB040>)`

**Comment by grlee77** [comment] 2022-08-16 13:36
We had only anticipated sigma being a single value representing the standard deviation of Gaussian noise in an image. It should not be related to the image pixel or voxel size, so I don't think this is a bug or missing feature. Internally, the sigma is used to determine scalar thresholds that get applied to individual wavelet bands (adapted per band if using BayesShrink or the same for all bands if using VisuShrink).

**Comment by grlee77** [comment] 2022-08-16 13:37
I will close this as not a bug, but feel free to continue the conversation here

**Closed by grlee77** 2022-08-16 13:37 UTC
