### ISSUE TITLE
ImportError: Cannot import name _hough_circle

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2155] opened 2016-06-17 14:34 UTC
## Description
I have been using scikit-image on Travis successfully for a while now. But all of a sudden I seem to be getting an import error about `_hough_circle`:
```
file_metadata/image/image_file.py:18: in <module>
    import skimage.transform
../../../miniconda/envs/py2.7/lib/python2.7/site-packages/skimage/transform/__init__.py:1: in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
../../../miniconda/envs/py2.7/lib/python2.7/site-packages/skimage/transform/hough_transform.py:4: in <module>
    from ._hough_transform import (_hough_circle,
E   ImportError: cannot import name _hough_circle
```
Related build https://travis-ci.org/AbdealiJK/file-metadata/builds/138345298

I'm installing scikit-image using `pip` in an an environment created with miniconda.

System: Travis, Ubuntu 12.04 Precise
Python version: 2.7.11 : In a miniconda environment
Scikit version: 0.12.3

**Comment by AbdealiJK** [comment] 2016-06-18 08:23
I found a very similar error on another server where I was trying to run my new script. (I started using the `skimage.transform` in the latest version).

In that, I got the error msg:
```
Traceback (most recent call last):
  File "tests/bulk.py", line 24, in <module>
    from file_metadata.image.image_file import ImageFile
  File "/home/abdealijk/file-metadata/file_metadata/image/image_file.py", line 18, in <module>
    import skimage.transform
  File "/home/abdealijk/miniconda/envs/py27/lib/python2.7/site-packages/skimage/transform/__init__.p
y", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/home/abdealijk/miniconda/envs/py27/lib/python2.7/site-packages/skimage/transform/hough_tran
sform.py", line 4, in <module>
    from ._hough_transform import (_hough_circle,  
  File "skimage/transform/_hough_transform.pyx", line 13, in init skimage.transform._hough_transform
 (skimage/transform/_hough_transform.c:23691)
  File "/home/abdealijk/miniconda/envs/py27/lib/python2.7/site-packages/skimage/draw/__init__.py", l
ine 1, in <module>
    from .draw import circle, ellipse, polygon_perimeter, set_color
  File "/home/abdealijk/miniconda/envs/py27/lib/python2.7/site-packages/skimage/draw/draw.py", line 
6, in <module>
    from .._shared._geometry import polygon_clip
  File "/home/abdealijk/miniconda/envs/py27/lib/python2.7/site-packages/skimage/_shared/_geometry.py", line 4, in <module>
    from matplotlib import _path, path, transforms
ImportError: No module named matplotlib
```

This made me realize that the actual error was that `matplotlib` was not installed. When I tried installing `matplotlib` in the travis build, It works: https://travis-ci.org/AbdealiJK/file-metadata/builds/138544440 (This is without a cache)

In [L635](https://travis-ci.org/AbdealiJK/file-metadata/builds/138546205#L635) it is seen that matplotlib is not installed, but scikit-image is installed. The next line where I again do `pip install matplotlib` installs matplotlib (It would have said "already installed" if pip had installed it with skimage) 

So there seems to be 2 issues:
 - 1. Matplotlib is not getting installed from pip ?
 - 2. The error in Travis for some reason is truncated and not complete.

I further checked the `setup.py` in skimage, and it does indeed add `matplotlib` to the install_requires.
I'm not sure why `pip` is not installing it ...

**Comment by soupault** [comment] 2016-06-18 09:09
@AbdealiJK I suppose you are using this file to list dependencies -> https://github.com/AbdealiJK/file-metadata/blob/master/requirements.txt . I'm not an expert in Travis-CI, but [this](https://stackoverflow.com/questions/28110449/can-pip-install-packages-recursively-from-requirements-txt) seems to be the solution.
Let us know if it works for you.

Closing as not a bug of `scikit-image`.

**Closed by soupault** 2016-06-18 09:09 UTC
