### ISSUE TITLE
Interpolation error in measure.profile_line

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#4279] opened 2019-11-04 21:10 UTC
## Description

#4206, once merged, exposes interesting behavior for [measure.profile_line](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.profile_line). Consider

```python
image = np.arange(12).reshape(4, 3)
# reduce_func is a new parameter proposed in #4206
prof = profile_line(image, (0, 1), (3, 1), linewidth=3, reduce_func=None)
assert_array_equal(image, prof)
```
As I understand it, the returned profile should be identical with the original image but we get this (value at (0, 2) is different):
```
AssertionError: 
Arrays are not equal
Mismatch: 8.33%
Max absolute difference: 2
Max relative difference: 0.
 x: array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
 y: array([[ 0,  1,  0],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```
This might originate in [scipy.ndimage.map_coordinates](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.map_coordinates.html#scipy.ndimage.map_coordinates). Looks like a potential bug to me but might be an edge case for the underlying interpolation that can be ignored/is not reasonable to fix. 
This behavior is already relevant even before merging #4206 because the faulty value will change the mean value of the profile line.

https://github.com/scikit-image/scikit-image/pull/4206#issuecomment-544920806 also highlights additional strange behavior.

## Version information

Current master, exposed once #4206 is merged.

**Comment by jni** [comment] 2019-11-06 03:26
@lagru it has to do with this: https://github.com/scipy/scipy/issues/9746 (though that issue needs links to other posts).

I think what is happening is that the `arctan2` call is getting a coordinate that is *just* past (2,) for axis=1 due to floating point error, and that evaluates to 0, which I've argued with @stefanv is a mistake, but I'll leave that battle for a future post. =P I agree with his statement on Zulip that someone needs to take a close look at this, *and* I kinda wanna be that someone. =P Soon...

**Comment by lagru** [comment] 2019-11-13 19:49
Thanks for the pointer! Do you mean to take a look at scipy/scipy#9746 or at NumPy's `arctan2`?

**Comment by rfezzani** [comment] 2020-01-27 22:58
`profile_line` uses `_line_profile_coordinates`to compute the coordinates of the profile of the input image along the desired scan line. In the example that @lagru provided, its output is:
```python
>>> _line_profile_coordinates((0, 1), (3, 1), 3)
array([[[-6.123234e-17,  0.000000e+00,  6.123234e-17],
        [ 1.000000e+00,  1.000000e+00,  1.000000e+00],
        [ 2.000000e+00,  2.000000e+00,  2.000000e+00],
        [ 3.000000e+00,  3.000000e+00,  3.000000e+00]],

       [[ 2.000000e+00,  1.000000e+00,  0.000000e+00],
        [ 2.000000e+00,  1.000000e+00,  0.000000e+00],
        [ 2.000000e+00,  1.000000e+00,  0.000000e+00],
        [ 2.000000e+00,  1.000000e+00,  0.000000e+00]]])
```
The negative value at index `(0, 0, 0)` causes the observed bug!
One option could be to clip the output of `_line_profile_coordinates`, but this imposes that the `src` and `dst` arguments of `profile_line` o be positive...

**Comment by stefanv** [comment] 2020-01-30 19:20
I don't like clipping in general, but if we ensure that the coordinates provided are inside the image, and then clip our generated coordinates, that's probably about as good as we can do.

**Comment by rfezzani** [comment] 2020-01-30 21:00
@stefanv, that's almost what is implemented in #4416 ;-), I a just required that the input coordinates are positive... I like your suggestion, but it will require a deprecation cycle...

**Comment by stefanv** [comment] 2020-01-30 21:11
Ah, so we currently allow "out-of-bounds" coordinates?  I guess we could just clip the line against the image borders.

**Comment by jni** [comment] 2020-02-12 23:56
Hi everyone,

Sorry that I missed this discussion when it was happening. I don't think clipping or enforcing in-bounds coordinates is the right approach here. If we take the original use case for this function, I was measuring line profiles of a certain width from the top edge of the image to the bottom edge. (This is in [fig 3](https://peerj.com/articles/453/#fig-3) of the skimage paper!) If there is any angle at all on the line, some coordinates will naturally fall out of bounds! In that situation, I think the best policy is to be consistent with scipy's out of bounds interpolation modes. Indeed, the original issue in this PR is actually fixed by passing `mode='nearest'` to `profile_line`:

```python
In [10]: prof = measure.profile_line(image, (0, 1), (3, 1), linewidth=3,
    ...: reduce_func=None, mode='nearest')                                                   

In [11]: prof                                                                      
Out[11]: 
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```

So, in my opinion we should not merge #4416 and we should instead consider changing the default mode to "nearest", or documenting this fix.

**Comment by rfezzani** [comment] 2020-02-13 08:14
@jni , the problem is that we are that `profile_line` uses internally `ndi.map_coordinates`, and for negative coordinates, this function uses the convention of indexing from the end of the array, So whatever is the used mode, if we face negative coordinates, the interpolation result will be wrong on the edge of the image!!!

**Comment by jni** [comment] 2020-02-13 08:33
@rfezzani, unless I am misunderstanding, that is only true for `mode='wrap'`:

```python
In [1]: arr = np.arange(100)

In [5]: ndi.map_coordinates(arr, [[-1, -2, -3]], mode='nearest')
Out[5]: array([0, 0, 0])

In [6]: ndi.map_coordinates(arr, [[-1, -2, -3]], mode='constant', cval=42)
Out[6]: array([42, 42, 42])

In [7]: ndi.map_coordinates(arr, [[-1, -2, -3]], mode='wrap')
Out[7]: array([98, 97, 96])

In [9]: ndi.map_coordinates(arr, [[-1, -2, -3]], mode='reflect')
Out[9]: array([0, 1, 2])
```

**Comment by rfezzani** [comment] 2020-02-13 08:50
Yeah, you are right, sorry. I performed some test from my side, and I observe this too....
I have to investigate more...

**Comment by rfezzani** [comment] 2020-02-13 08:59
OK, my bad :pray: !
The problem is an edge mode problem! Back to the example of this issue
```python
>>> image = np.arange(12).reshape(4, 3)
>>> profile_line(image, (0, 1), (3, 1), linewidth=3, reduce_func=None)
array([[ 0,  1,  0],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
>>> profile_line(image, (0, 1), (3, 1), linewidth=3, reduce_func=None, mode='reflect')
array([[ 0,  1,  5],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
>>> profile_line(image, (0, 1), (3, 1), linewidth=3, reduce_func=None, mode='nearest')
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```
The reported bug comes from the fact that the default mode is 'constant'

**Comment by stefanv** [comment] 2020-02-19 18:30
I think either clipping or using boundary modes is acceptable, as long as it is clearly specified in the docstring. @jni not sure what you mean by "will naturally fall out"; if you specify a starting and end point inside the image, all coordinates should be in the image.

**Comment by jni** [comment] 2020-02-19 23:41
@stefanv there is optionally a width to the line being measured, so you are actually measuring a rectangle, and some corners of the rectangle will fall outside the image even if you clip the start and end coordinates of the (mid)line of the rectangle.

**Closed** 2020-04-08 00:18 UTC
Labels: type: bug
