### ISSUE TITLE
problems with scikit-image display in eclipse for linux

### ISSUE THREAD

**Issue by antonio19812** [scikit-image/scikit-image#1564] opened 2015-06-18 18:15 UTC
I have copied this short script from the scikit-image web page, just to try it and see how it displays images : 

from skimage import data
import numpy as np
import matplotlib.pyplot as plt
cat = data.chelsea()

reddish = cat[:,:,0] > 160
cat[reddish] = [0, 255, 0]
plt.imshow(cat)

But actually when I run it I do no obtain anything, neither an error nor an image displayed.

What could the problem? I am working in python on Eclipse for Suse13.2 in a virtual machine

**Comment by vighneshbirodkar** [comment] 2015-06-18 18:19
Insert
```
plt.show()
```
towards the end

**Comment by antonio19812** [comment] 2015-06-18 18:20
I did it already and nothing came out :(

**Comment by JDWarner** [comment] 2015-06-18 18:22
This depends a little on your matplotlib backend, but generally if you're using defaults and it's executing without warnings or exceptions `plt.show()` is a blocking command that spawns a new window and pauses the Python thread execution until it's closed.

So look for a new window with a picture of a red-tinted cat.

**Comment by antonio19812** [comment] 2015-06-18 18:25
I don't see any new window opened and eclipse does not give me any warning or error...

**Comment by antonio19812** [comment] 2015-06-18 18:37
I added just a line  that print some characters in the console, after the plt.show() line, to see if python execution was blocked by plt.show but this does not happen , the script is totally executed until the end.

**Comment by JDWarner** [comment] 2015-06-18 18:49
Please experiment with matplotlib directly to determine if it works in isolation or scikit-image has a problem. Once you verify matplotlib works independently, we can attempt to sort this out - before that, we have no idea if the problem was in the matplotlib installation or if it might be in our package.

**Comment by antonio19812** [comment] 2015-06-18 20:18
Following your suggestion I searched for an example of the only matplotlib functionality and I found this one in the matplotlib official website :

Simple demo of the imshow function.
"""
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook

image_file = cbook.get_sample_data('ada.png')
image = plt.imread(image_file)

plt.imshow(image)
plt.axis('off') # clear x- and y-axes
plt.show()

After downloading the png file it should have been possible to display it easily but it happened what had happened before, the script is executed totally with no errors or warnings but nothing is displayed.
what should I do then?

**Comment by blink1073** [comment] 2015-06-18 20:24
try copying that code to your clipboard, opening ipython, and using the `%paste` magic.

**Comment by antonio19812** [comment] 2015-06-18 20:55
First stupid question of the day, but I am not an expert, from where can I access to IPython???

**Comment by blink1073** [comment] 2015-06-18 20:58
you should be able to install it from `yast`, then just run `ipython` from the command line.

**Comment by antonio19812** [comment] 2015-06-18 20:58
okok, i will try :)

**Comment by antonio19812** [comment] 2015-06-18 21:04
I hope it will not have any interference with python in eclipse, otherwise i will be desperate:))

**Comment by antonio19812** [comment] 2015-06-18 21:54
wow, in ipython it works, so what should i do?

**Comment by antonio19812** [comment] 2015-06-18 22:02
so matplotlib works in ipython , where is the problem?

**Comment by blink1073** [comment] 2015-06-18 22:03
I'm not familiar with eclipse, you may creating a matplotlib issue, they would have a better idea. 



—

**Comment by JDWarner** [comment] 2015-06-18 22:03
The problem is not with scikit-image. Since the pure matplotlib snippet also failed in Eclipse, I'm closing this as the problem is not with scikit-image.

Consider not using Eclipse, or investigate possible interactions between Eclipse and matplotlib with either of those parties.

**Closed** 2015-06-18 22:03 UTC
