### ISSUE TITLE
How do I overload skimage.graph methods?

### ISSUE THREAD

**Issue by eithun** [scikit-image/scikit-image#3923] opened 2019-05-21 16:12 UTC
## Description

Several methods in skimage.graph say "This method can be overloaded to modify the behavior of the MCP algorithm." How do I do this? I tried things like 

`
class MCP:
    def goal_reached(self, index, cumcost):
        print("hi")
`

**Comment by stefanv** [comment] 2019-05-21 17:15
This is probably the clearest example: https://github.com/scikit-image/scikit-image/blob/master/skimage/graph/tests/test_flexible.py

Since this is not a bug, I will close the issue, but feel free to ask if you need further clarification.  We encourage usage questions to be posted to the [online forum](https://forum.image.sc/tags/scikit-image).

**Closed by stefanv** 2019-05-21 17:15 UTC
