### ISSUE TITLE
TypeError: No matching signature found in watershed

### ISSUE THREAD

**Issue by weibei43** [scikit-image/scikit-image#7087] opened 2023-08-07 05:11 UTC
Hi,

I am a new user, I encountered the problem with watershed of the package. Here are the errors:

```
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 52>()
     49 markers[resized_im >= upper_cutoff] = 2
     50 print (markers)
---> 52 segmentation = watershed(elevation_map, markers)
     53 plt.imshow(segmentation)
     54 plt.title('Segmented tissues')

File ~/.local/lib/python3.9/site-packages/skimage/segmentation/_watershed.py:215, in watershed(image, markers, connectivity, offset, mask, compactness, watershed_line)
    212 marker_locations = np.flatnonzero(output)
    213 image_strides = np.array(image.strides, dtype=np.intp) // image.itemsize
--> 215 _watershed_cy.watershed_raveled(image.ravel(),
    216                                 marker_locations, flat_neighborhood,
    217                                 mask, image_strides, compactness,
    218                                 output.ravel(),
    219                                 watershed_line)
    221 output = crop(output, pad_width, copy=True)
    223 return output

File _watershed_cy.pyx:70, in skimage.segmentation._watershed_cy.__pyx_fused_cpdef()

TypeError: No matching signature found
```

Could you please help with the bug?

Thank you very much!

**Comment by lagru** [comment] 2023-08-07 09:48
Hey @weibei43 :wave:, we will likely need more information than just the traceback to help you. How did you install scikit-image? `_watershed_cy.watershed_raveled` is only available if scikit-image was properly compiled so that might be an issue. It would also be useful if you could include a minimal code snippet with which we can try to reproduce your error.

**Comment by MartinGardfjell** [comment] 2023-08-29 15:02
Hi,
I also experienced this bug, running watershed as intended, e.g:

sobel = skimage.filters.sobel(img)
markers = np.zeros_like(img)
markers[img < 0.05] = 1
markers[img > 0.7] = 2
segmentation = skimage.segmentation.watershed(sobel, markers)

The bug disappeared after I rolled back skimage to 0.20.0. Seems like you introduced a bug in 0.21.0.

**Comment by rvrooij** [comment] 2023-10-09 13:05
Same for me.

**Comment by hmaarrfk** [comment] 2023-10-09 13:33
As lagru has mentionned, we really need the full code, from the very first import statement to the command that provides the error to help you debug.

In the example @MartinGardfjell  it is unclear what the datatype of the original `img` is.

Please see this post for more information
https://matthewrocklin.com/minimal-bug-reports#minimal-complete-verifiable-examples

**Comment by mkcor** [comment] 2024-02-20 15:24
Hi all,

It appears the change comes from 7389da78e1399e4058 which belonged to PR #6839.

It is important that you pass your `markers` as an ndarray of int as [documented](https://scikit-image.org/docs/stable/api/skimage.segmentation.html#skimage.segmentation.watershed), now that they are not coerced into `np.int32` anymore.

@lagru @hmaarrfk I would consider closing this issue.

**Comment by lagru** [comment] 2024-02-21 13:05
@weibei43 and everyone else please feel welcome to re-open or add more information!

**Closed by lagru** 2024-02-21 13:05 UTC
Labels: :people_hugging: Support
