### ISSUE TITLE
bug in rotate resize 

### ISSUE THREAD

**Issue by mistycheney** [scikit-image/scikit-image#1874] opened 2016-01-13 07:04 UTC
There is a bug in rotate() if resize=True. The output image is not resized correctly.

https://github.com/scikit-image/scikit-image/blob/953fbfc539217ad4c92fcf14a9d6dfe1b4b1b793/skimage/transform/_warps.py#L273
should be 
`translation = -np.asarray((minc, minr))`

https://github.com/scikit-image/scikit-image/blob/953fbfc539217ad4c92fcf14a9d6dfe1b4b1b793/skimage/transform/_warps.py#L277
should be
`warp(image, tform.inverse, output_shape=output_shape, order=order,
                mode=mode, cval=cval, clip=clip, preserve_range=preserve_range)`

**Comment by OrkoHunter** [comment] 2016-01-13 10:08
@mistycheney Can you show an image example to reproduce the problem? I tried with `image = data.camera()` and there was no difference. It would be better to have the image used by you.

Further, while rotating without `resize=True` argument, I got a UserWarning : 
```py
>>> io.imsave("default.png", transform.rotate(image, 90))
/home/hunter/anaconda/lib/python2.7/site-packages/skimage/util/dtype.py:111: UserWarning: Possible precision loss when converting from float64 to uint16
  "%s to %s" % (dtypeobj_in, dtypeobj))
```
while, there was no such warning with
```py
>>> io.imsave("bug.png", transform.rotate(image, 90, resize=True))
```
Is this intentional or supposed to be an issue?

**Comment by mistycheney** [comment] 2016-01-13 21:57
If you run:
```
image = data.camera()
rotated = rotate(image, 45, resize=True, center=(0,0))
```
You will see `rotated` is not the smallest bounding box of the output image.

**Comment by OrkoHunter** [comment] 2016-01-14 02:16
Yes, I reproduced the image. Maybe the issue is with the center argument. Doesn't it work fine without `center=(0,0)`?

**Comment by stefanv** [comment] 2016-01-14 07:00
This is a bug.  Are you interested in working on a fix?

**Comment by OrkoHunter** [comment] 2016-01-14 07:06
@mistycheney Has listed out two changes in above comment. If he's interested, he can create a patch. Otherwise, I'll be interested in doing this !

**Comment by mistycheney** [comment] 2016-01-14 08:13
@OrkoHunter Please go ahead to fix it! Thank you!

**Comment by ahojnnes** [comment] 2016-01-14 10:33
Thanks for reporting and fixing the bug. This bug was introduced when the `center` argument feature was added... Please, also add a unit test to catch the behavior. Thanks!

**Comment by OrkoHunter** [comment] 2016-01-14 14:35
@mistycheney After changing `tform` to `tform.inverse` in the `warp` function, some tests ([`test_rotate`](https://github.com/scikit-image/scikit-image/blob/953fbfc539217ad4c92fcf14a9d6dfe1b4b1b793/skimage/transform/tests/test_warps.py#L106-L110), [`test_rotate_center`](https://github.com/scikit-image/scikit-image/blob/953fbfc539217ad4c92fcf14a9d6dfe1b4b1b793/skimage/transform/tests/test_warps.py#L124-L132)) break. While, leaving it unchanged has a positive effect. Any comments on this?

**Comment by ahojnnes** [comment] 2016-01-14 15:51
Positive effect meaning what? All tests pass?

**Comment by OrkoHunter** [comment] 2016-01-14 17:25
@ahojnnes Yes. Please have a look on #1878.

**Comment by OrkoHunter** [comment] 2016-01-14 17:58
And I tried to test the changes locally, but sadly I didn't see it fixed. I think we need little more changes here. This is beyond me as of now.

**Comment by ahojnnes** [comment] 2016-01-20 20:53
Fixed in https://github.com/scikit-image/scikit-image/pull/1887.

Please test the fix. Thanks!

**Comment by stefanv** [comment] 2016-01-21 02:51
I'm not sure that's the right way to fix this issue.

**Comment by ahojnnes** [comment] 2016-01-21 07:33
@stefanv What do you mean? I am relatively certain it is doing the right thing :-)

**Comment by stefanv** [comment] 2016-01-22 02:00
The code just feels a bit messy.  But if you think this is the cleanest way
forward, I'll go with it.

**Comment by ahojnnes** [comment] 2016-01-22 07:55
Maybe we are looking at different functions, but I don't see how it is messy or how I could make it less messy. Somehow you need to determine the corners of the rotated image to fix it in the resizing step.

**Comment by stefanv** [comment] 2016-01-22 16:58
I guess I saw you reversing the tform1 + tform2 + tform3 order, and it made me wonder.  But I checked again and I think it's all good.  Thanks!

**Closed by stefanv** 2016-01-22 16:58 UTC
Labels: bug
