### ISSUE TITLE
Pip3 install of scikit-image fails for Python 3.9 on macOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by mok0** [scikit-image/scikit-image#5121] opened 2020-12-09 21:49 UTC
## Description
The build of scikit-image using Python 3.9 and

```
pip3 install scikit-image
```

fails with C compilation errors in both `scikit-image` and `pycares`.

## Way to reproduce

```
pip3 install scikit-image
```
[scikit-image-build.log](https://github.com/scikit-image/scikit-image/files/5668924/scikit-image-build.log)

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import numpy; print("numpy version: {}".format(numpy.__version__))
import skimage; print("scikit-image version: {}".format(skimage.__version__))
# (Switched last two lines from template to make script print numpy version)
```

```python
3.9.0 (default, Dec  6 2020, 18:02:34)
[Clang 12.0.0 (clang-1200.0.32.27)]
macOS-10.15.7-x86_64-i386-64bit
numpy version: 1.19.4
Traceback (most recent call last):
  File "/private/tmp/tmp.py", line 5, in <module>
    import skimage; print("scikit-image version: {}".format(skimage.__version__))
ModuleNotFoundError: No module named 'skimage'

```

Most of the compilation errors are deprecation warnings but a few are actual C-code errors in this version of Clang:

```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

Log file attached.

**Comment by hmaarrfk** [comment] 2020-12-09 22:40
Thank you for reporting.

This seems to be a duplicate of https://github.com/scikit-image/scikit-image/issues/5051 and we are addressing it in the next release. For now, We would suggest using python 3.8 if possible. or installing from the github page.

**Closed by hmaarrfk** 2020-12-09 22:40 UTC
