### ISSUE TITLE
Multi Scale Structural Similarity Index

### ISSUE THREAD

**Issue by a-parida12** [scikit-image/scikit-image#6437] opened 2022-07-13 20:36 UTC
Why dont we have the ms ssim as a metric in the `skimage.metrics`. ?

I see that from here https://github.com/mubeta06/python/blob/master/signal_processing/sp/ssim.py#L50 the implementation is straight forward. We already have the `ssim` as a metric and should be a good extension. 

Is their a reason it is skipped?

**Comment by grlee77** [comment] 2022-08-16 13:31
Hi @a-parida12, I will close this as a duplicate of #5194. As mentioned there, it would be great if you want to work on this. 

The specific repository above does not seem to have a license, so I would not adapt that code directly unless you can clarify license terms with the author. (It must be a permissive license compatible with our BSD 3-clause license)

**Closed by grlee77** 2022-08-16 13:31 UTC
