### ISSUE TITLE
imsave showing error with is_low_contrast

### ISSUE THREAD

**Issue by YubinXie** [scikit-image/scikit-image#3973] opened 2019-06-20 18:49 UTC
## Description

imsave showing error with is_low_contrast. However, the image looks fine/not low contrast when display with plt.imshow. 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-84482ecfeae4> in <module>
---->      io.imsave(test_img,save_folder + filename)

~/miniconda3/lib/python3.7/site-packages/skimage/io/_io.py in imsave(fname, arr, plugin, **plugin_args)
    137         if fname.lower().endswith(('.tiff', '.tif')):
    138             plugin = 'tifffile'
--> 139     if is_low_contrast(arr):
    140         warn('%s is a low contrast image' % fname)
    141     if arr.dtype == bool:

~/miniconda3/lib/python3.7/site-packages/skimage/exposure/exposure.py in is_low_contrast(image, fraction_threshold, lower_percentile, upper_percentile, method)
    501         image = rgb2gray(image)
    502 
--> 503     dlimits = dtype_limits(image, clip_negative=False)
    504     limits = np.percentile(image, [lower_percentile, upper_percentile])
    505     ratio = (limits[1] - limits[0]) / (dlimits[1] - dlimits[0])

~/miniconda3/lib/python3.7/site-packages/skimage/util/dtype.py in dtype_limits(image, clip_negative)
     55         warn('The default of `clip_negative` in `skimage.util.dtype_limits` '
     56              'will change to `False` in version 0.15.')
---> 57     imin, imax = dtype_range[image.dtype.type]
     58     if clip_negative:
     59         imin = 0

KeyError: <class 'numpy.str_'> 
## Way to reproduce
```python
    new_img = rescale(image=img,scale=1.28,anti_aliasing=True,multichannel=True,preserve_range=True,mode='reflect')
    new_img =new_img/np.max(new_img,axis=(0,1))
    io.imsave(new_img,save_folder + filename)
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-18.5.0-x86_64-i386-64bit
scikit-image version: 0.14.2
numpy version: 1.16.4
```

**Comment by YubinXie** [comment] 2019-06-20 19:03
For the same image, imageio.imwrite works.

**Comment by jni** [comment] 2019-06-21 00:29
I have made this mistake many times, so I feel your pain, but it's not a bug. =) The last line should be `io.imsave(save_folder + filename, new_img)` (the order of the arguments is reversed compared to what you have).

I'm going to close this as not-a-bug, but let us know if you still have a problem, and we can reopen if necessary!

**Closed by jni** 2019-06-21 00:29 UTC

**Comment by YubinXie** [comment] 2019-06-21 01:56
oh, I see. Thank you for pointing it out! Somehow I was well-convinced that array first... I guess because the error did not point out and I guess it is not the order issue.

It might be better if the warning could be more straightforward saying it is an order issue...  I recalled got a warning from other image-saving package saying 'input should be an arr instead of string'. 

Thanks!
