### ISSUE TITLE
Unable to install, showing you the logs,  please help me.

### ISSUE THREAD

**Issue by shivamqainfotech** [scikit-image/scikit-image#2798] opened 2017-09-11 10:20 UTC
```
Command "c:\users\shivambharadwaj\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SHIVAM~1\\AppData\\Local\\Temp\\pip-build-225g8oyu\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SHIVAM~1\AppData\Local\Temp\pip-_qm8t876-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SHIVAM~1\AppData\Local\Temp\pip-build-225g8oyu\scipy\
```

**Comment by soupault** [comment] 2017-09-11 13:30
Seems to me that you are trying to install `scipy` on Windows via `pip`, which is not the best option currently. You should consider using pre-build wheels for `numpy` and `scipy` on Windows (see http://www.lfd.uci.edu/~gohlke/pythonlibs/ ), and only then try to install `scikit-image`.

Closing as not a bug, but feel free to continue the discussion here.

**Closed by soupault** 2017-09-11 13:30 UTC
