### ISSUE TITLE
resize function incorrect behaviour for integer types.

### ISSUE THREAD

**Issue by ashesh-0** [scikit-image/scikit-image#4139] opened 2019-09-05 14:12 UTC
## Description
When resize is called on  image of type np.int32/np.int64, it returns wierd values.

## Way to reproduce
```python
In [18]: from skimage.transform import resize as imresize 
    ...: import numpy as np 
    ...:  
    ...: img = np.random.randint(0, 255, (240, 240)) 
    ...: print(img.min(), img.mean(), img.max()) 
    ...:  
    ...: img2 = imresize(img.astype(np.int32), (64, 64)) 
    ...: print(img2.min(), img2.mean(), img2.max()) 
    ...:  
    ...: img3 = imresize(img.astype(np.float32), (64, 64)) 
    ...: print(img3.min(), img3.mean(), img3.max()) 
    ...:                                                     
```

![Screenshot from 2019-09-05 22-08-35](https://user-images.githubusercontent.com/6098025/64349665-eb370980-d029-11e9-8303-4c741cf1410c.png)

## Version information
```python
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Linux-4.15.0-60-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.15.0
numpy version: 1.17.0


```

**Comment by jni** [comment] 2019-09-05 17:19
@ashesh-0 unfortunately, this is expected behaviour, see http://scikit-image.org/docs/dev/user_guide/data_types.html. We realise that this can be confusing and are discussing possibilities for making things more intuitive in #3009. Please continue the discussion there if needed. For now, I am going to close this as duplicate of that one. Don't hesitate to contact us for more info!

**Closed by jni** 2019-09-05 17:19 UTC
