### ISSUE TITLE
Pyramid functions do not allow user to preserve image range

### ISSUE THREAD

**Issue by zpincus** [scikit-image/scikit-image#1945] opened 2016-02-17 16:19 UTC
Is there any reason that the various skimage pyramid functions do not have `preserve_range=False` in the arguments? I find this frustrating, and so if there's no reason to keep it this way, I'll make a PR to fix this.

**Comment by JDWarner** [comment] 2016-02-17 18:24
It does not appear this is a necessary limitation. Feel free to make a PR to this effect!

**Comment by stefanv** [comment] 2016-02-17 19:30
It's a pattern we only started adopting fairly recently, so it's not very
widely in place.  I'm not convinced it's the best pattern, even, but I
guess we'll learn the best way forward in due course.

**Comment by zpincus** [comment] 2016-02-17 21:04
Not sure what the best pattern is either. At least `preserve_range` is a start, though... without it, skimage is extraordinarily frustrating to use for my day-to-day tasks. Here is the case from today where I ran across the issue with pyramids: I want to correct an image from a microscope for uneven illumination, so I want to fit a particular image region to a low-order polynomial in 2D.

The images are big so the fitting is slow, so I want to use `pyramid_reduce()` to make a smaller version. **Problem 1:** now my original image and downsampled image are scaled differently. Easy enough fix, though, just need to remember the scale factor. Then I fit a polynomial to the intensities of the downsampled image to produce a "background image".

Now, to subtract the background image from the original image I just need to expand the background image back up with `pyramid_expand()`.

**Problem 2:** the background image exceeds 1 at a few points because it was generated from a polynomial fit. This causes `pyramid_expand()` to choke. Now, I need to rescale the image to [0,1] before enlarging it, and then undo both that rescaling and the first rescaling from `pyramid_reduce()`, just to get an image that I can apply to my microscope image. (The microscope image needs to stay in the units of original detector counts because I have a whole pipeline to convert detector counts into meaningful physical units).

One could even argue that there's no real reason that the transforms should bother enforcing dtype ranges in the first place. (Algorithms that actually need to make assumptions about pixel intensities -- sure, let them require the ranges be right. But transforms?) I'm glad  `preserve_range` is now available, but even so, lots of skimage remains broken-by-default for the vast majority of my tasks.

**Comment by ahojnnes** [comment] 2016-02-17 21:13
@Zachary Thanks for your feedback, this is valuable to improve scikit-image. I agree that most of our range conventions for float images are not good, mainly caused by the img_as_float function. We should really try to reduce its usage to places where it is really necessary. Would you go ahead and create a new PR to enable the preserve_range in the pyramid functions? Please, let us know if there is any other "annoying" things that you encounter in your work.

**Comment by OlaPaw** [comment] 2016-02-18 15:18
This is a very good point.  I had the same issue occur to me with float images when using gaussian_filter of all things.  What does that filter need to worry about the 1.0 limit?  I ended up frustrated with having to rescale and just used the cv2 GaussianBlur (which then led to figuring out the difference in kernel sizes and standard deviation uses between the two libraries, but that's another story.

**Comment by rfezzani** [comment] 2020-02-13 11:11
This is no more True, pyramid functions all supports the `preserve_range` argument :wink:. Closing

**Closed by rfezzani** 2020-02-13 11:11 UTC
Labels: type: enhancement
