### ISSUE TITLE
New canny implementation silently fails with integer images.

### ISSUE THREAD

**Issue by erykoff** [scikit-image/scikit-image#6871] opened 2023-04-05 19:13 UTC
### Description:

The new `skimage.feature.canny` implementation silently fails if given an integer image.  This worked on `scikit-image<=0.19`, and no longer works with `scikit-image=0.20`.  The documentation says that any dtype should work:
```
    image : 2D array
        Grayscale input image to detect edges on; can be of any dtype.
```

### Way to reproduce:

```
from skimage.feature import canny
import numpy as np

im = np.zeros((100, 100))
im[0: 50, 0: 50] = 1.0
print("Edge pixels with float input: ", canny(im, low_threshold=0, high_threshold=1).sum())
print("Edge pixels with int input: ", canny(im.astype(np.int64), low_threshold=0, high_threshold=1).sum())
```
This prints on new skimage (0.20):
```
Edge pixels with float input:  182
Edge pixels with int input:  0
```
And on old skimage (0.19):
```
Edge pixels with float input:  144
Edge pixels with int input:  144
```

As I write this test case I also need to ask ... why did the number of pixels change?

### Version information:

```Shell
3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
scikit-image version: 0.20.0
numpy version: 1.23.5
```

**Comment by stefanv** [comment] 2023-04-05 19:16
Yikes, thanks for catching this!

On latest skimage I see:

```
Edge pixels with float input:  144
Edge pixels with int input:  0
```

So, at least the float version seems OK.

**Comment by stefanv** [comment] 2023-04-05 19:35
Note that with `(im * 255).astype(np.uint8)` as input, we already achieve the same result in v0.20 as with v0.19.

@rfezzani Could you confirm whether `low_threshold /= dtype_max` is wanted and necessary? We'll probably have to take this out for skimage v2 anyway, since we cannot rely on the dtype being meaningful.

**Comment by rfezzani** [comment] 2023-04-06 12:20
It seems that the division by `dtype_max` was introduced in this [commit](https://github.com/scikit-image/scikit-image/commit/c97b1b6c974da5ed01e09ab257322e7096ad1aaa) after merging #2983. It was proposed as a fix for #2981.
This issue reminds me the #3009 and #4442 issues. It at least needs fix/clarification/warning in the documentation as pointed out by @erykoff .

**Comment by rfezzani** [comment] 2023-04-06 15:35
I don't think the division by `dtype_max` is causing the bug... The following script gives
```python
import skimage
from skimage.feature import canny
import numpy as np

im = np.zeros((100, 100))
im[:50, :50] = 1

print(f"{skimage.__version__=}")

for dtype in ["float64", "float32",
              "uint8", "uint16", "uint32", "uint64",
              "int8", "int16", "int32", "int64"]:
    print(f"Edge pixels count with {dtype} input: ",
          np.count_nonzero(canny(im.astype(dtype),
                                 low_threshold=0, high_threshold=1)))
```
Gives 

### v0.19

```
skimage.__version__='0.19.0'
Edge pixels count with float64 input:  230
Edge pixels count with float32 input:  274
Edge pixels count with uint8 input:  190
Edge pixels count with uint16 input:  230
Edge pixels count with uint32 input:  230
Edge pixels count with uint64 input:  230
Edge pixels count with int8 input:  270
Edge pixels count with int16 input:  230
Edge pixels count with int32 input:  270
Edge pixels count with int64 input:  230
```

### v0.20

```
Edge pixels count with float64 input:  144
Edge pixels count with float32 input:  183
Edge pixels count with uint8 input:  98
Edge pixels count with uint16 input:  102
Edge pixels count with uint32 input:  142
Edge pixels count with uint64 input:  0
Edge pixels count with int8 input:  182
Edge pixels count with int16 input:  103
Edge pixels count with int32 input:  105
Edge pixels count with int64 input:  0
```

I don't understand why I see so many different values comparing with @stefanv and @erykoff  results :/

**Comment by stefanv** [comment] 2023-04-06 18:24
My results correspond with yours, @rfezzani.

**Comment by stefanv** [comment] 2023-04-06 18:27
The reason I suspected the dtype handling of being at fault, is because the magnitude of the edges are going to be very small when you input a value of `1` in an int64 image. Either way, it's clear that something's changed between the two versions.

**Comment by stefanv** [comment] 2023-04-06 18:54
The problem originated in 376d30f5ba83e98d2745622d9d4951914e0c91f7, #6348

**Comment by stefanv** [comment] 2023-04-06 20:10
The eroded mask calculation for the `mask=None` case seems suspect, even though it does not seem to impact the results much:

```diff
-        eroded_mask[:1, :] = 0
-        eroded_mask[-1:, :] = 0
-        eroded_mask[:, :1] = 0
-        eroded_mask[:, -1:] = 0
-
+        eroded_mask[1, :] = 0
+        eroded_mask[-1, :] = 0
+        eroded_mask[:, 1] = 0
+        eroded_mask[:, -1] = 0
```

**Comment by stefanv** [comment] 2023-04-06 20:17
OK, found the problem: it's related to `compute_bleedover`: before that was not done for an unmasked image, and now it's used.

**Comment by stefanv** [comment] 2023-04-06 20:19
```
        smoothed_image /= bleed_over
```

**Comment by stefanv** [comment] 2023-04-06 20:24
We apply a Gaussian filter to the mask to estimate bleed-over, but we set `mode='constant'`, which means that instead of returning mostly 1, the bleed-over varies a lot on the edges.

**Comment by stefanv** [comment] 2023-04-06 20:28
So, to get results compatible with previous versions, we should skip bleed_over calculation when no mask is given.

*Ideally*, however, computing bleedover should not affect the result; but I don't know what bleedover is, so I can't comment on that.

The closest I can get is to change the bleedover calculation not to use `mode='constant'`:

```python
        bleed_over = gaussian(mask.astype(float_type, copy=False), sigma=1) + np.finfo(float_type).eps
```

**Comment by stefanv** [comment] 2023-04-06 20:33
This does not resolve the issues with int64, btw. Even removing the range normalization, that thresholding still fails.

**Comment by stefanv** [comment] 2023-04-06 20:45
Re: difference between `float32` and `float64`, looks like the dtype influences the calculation of the smoothed (Gaussian filtered) image, which then later impacts gradients etc.

**Comment by lagru** [comment] 2023-04-06 20:47
I can reproduce the results in https://github.com/scikit-image/scikit-image/issues/6871#issuecomment-1499595076. Though, I think you omitted the last line for int64, which is still 0 and not 230 like in v0.19 (see https://github.com/scikit-image/scikit-image/issues/6871#issuecomment-1499262279):

```
skimage.__version__='0.21.0rc0.dev0+git20230406.6e51f8c7a'
Edge pixels count with float64 input:  230
Edge pixels count with float32 input:  270
Edge pixels count with uint8 input:  190
Edge pixels count with uint16 input:  230
Edge pixels count with uint32 input:  230
Edge pixels count with uint64 input:  0
Edge pixels count with int8 input:  270
Edge pixels count with int16 input:  230
Edge pixels count with int32 input:  270
Edge pixels count with int64 input:  0
```

**Comment by stefanv** [comment] 2023-04-06 20:50
OK, here we go: we call `gaussian` with `preserve_range=False`, so the uint64 image gets normalized before filtering :eyes:

**Comment by stefanv** [comment] 2023-04-06 20:51
```
Edge pixels count with float64 input:  230
Edge pixels count with float32 input:  270
Edge pixels count with uint8 input:  230
Edge pixels count with uint16 input:  230
Edge pixels count with uint32 input:  230
Edge pixels count with uint64 input:  230
Edge pixels count with int8 input:  230
Edge pixels count with int16 input:  230
Edge pixels count with int32 input:  230
```

**Comment by erykoff** [comment] 2023-04-06 20:52
There's some sleuthing!  These final numbers are with some patch done?  And `int64` is missing.

**Comment by stefanv** [comment] 2023-04-06 20:55
Woops, fixed that.

Yes, I'll make a PR with the patch soon for review.

**Comment by stefanv** [comment] 2023-04-06 20:58
The question remains of which `mode` we should use to calculate bleed-over; perhaps @rfezzani can answer that one.

**Comment by stefanv** [comment] 2023-04-06 21:05
OK, fixed by setting `mode='nearest'` for bleed-over calculation. May not be ideal in all cases, but aligns the masked and non-masked implementations for a full image mask.

**Comment by rfezzani** [comment] 2023-04-07 15:07
> The question remains of which `mode` we should use to calculate bleed-over; perhaps @rfezzani can answer that one.

I think that bleed-over has nothing to do with boundary mode...

**Comment by rfezzani** [comment] 2023-04-07 15:26
@erykoff, I am really sorry to see your https://github.com/lsst/pipe_tasks/pull/766#issuecomment-1499464515 ...
Image processing with `int64` data in is absolutely not standard (again, please see #3009 and #4442)...
The bug you reported 2 days ago (many thanks for that) is analyzed, and a patch is already close to be available... `scikit-image` is maybe not bug free (sorry for that), but its community is really responsive and helpful...  I hope you will nevertheless enjoy working with `scikit-image`...

**Comment by stefanv** [comment] 2023-04-07 19:39
I've concluded investigating the issue @erykoff.

(1) skimage does not support int64 images, so the fact that that worked before was coincidence. Please see https://scikit-image.org/docs/stable/user_guide/data_types.html

(2) There has been a change in behavior since 0.19, namely that we now are better at not returning (erroneous) canny edges on the border of images and masks. I consider this to be a bug fix.

(3) In #6875 I prohibit 64-bit integer images as input to canny, and add tests to ensure that masked and unmasked processing of images align.

**Closed** 2023-04-08 01:30 UTC
Labels: :bug: Bug
