### ISSUE TITLE
h_maxima/minima strange behaviors on floating point image input

### ISSUE THREAD

**Issue by w-hc** [scikit-image/scikit-image#4194] opened 2019-09-29 01:09 UTC
## Description
I have been trying to use the h_maxima implementation but this function seems to exhibit unstable behaviors. For example, 

1. when the input is all zeros, h_maxima returns a marker filled with all 1s. This seems incorrect.

2. Also, when my input consists of floating point values, and h set to a floating point threshold, even with a slight 0.1 change in h value, the number of detected instances can vary quite a bit. 

## Way to reproduce
```python
img = np.zeros((10, 10), dtype=float)
marker = h_maxima(img, h=1)
print(np.unique(marker))
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
scikit-image version: 0.15.0
numpy version: 1.16.4

```

**Comment by jni** [comment] 2019-09-30 11:31
@w-hc thanks for the report!

I don't have time to investigate in detail right now, but

1. It's unclear to me whether this is a bug or an ambiguous case... I'll have to think more about it.
2. Without more detail, that is, a specific test image and some code to that shows the maxima "varying quite a bit", we won't be able to help you in this case. It's quite probably that the output is correct for your image. The only guarantee that you can have for h_maxima is that the number of detected maxima should increase with decreasing h.

**Comment by w-hc** [comment] 2019-09-30 17:33
Here is script and sample image that can reproduce what I see. You need to uncompress this zip file to get the numpy array.

```python
import numpy as np
from skimage.morphology import h_maxima
from scipy import ndimage as ndi
heatmap = np.load('heatmap.npy')
assert heatmap.dtype == np.float32
for h in np.linspace(0.2, 4.0
[heatmap.npy.zip](https://github.com/scikit-image/scikit-image/files/3672479/heatmap.npy.zip)
, num=10):
    num_instances = ndi.label(h_maxima(heatmap, h))[1]
    print('at h= {:.3f}, discovered {} instances'.format(h, num_instances))
```

Output:
```
at h= 0.200, discovered 17 instances
at h= 0.622, discovered 25 instances
at h= 1.044, discovered 17 instances
at h= 1.467, discovered 25 instances
at h= 1.889, discovered 17 instances
at h= 2.311, discovered 24 instances
at h= 2.733, discovered 16 instances
at h= 3.156, discovered 23 instances
at h= 3.578, discovered 21 instances
at h= 4.000, discovered 23 instances
```

**Comment by jni** [comment] 2019-10-02 09:21
@w-hc 

> The correct number of local maxima should be 25.

well then just use 0.622, what's the problem??? :joy: 

Kidding of course. Yikes! Either I misunderstand `h_maxima` or this is indeed a significant bug. Thank you so much for the report and for the test case!

**Comment by jni** [comment] 2019-10-02 09:47
Yep, definitely a bug. By computing a bunch of results, displaying them in napari, and slicing through them, I can see individiual maxima blinking on and off, instead of being off and staying off:

```python
import numpy as np
from skimage.morphology import h_maxima as hmaxima
import napari

image = np.load('heatmap.npy')
# use this in ipython --gui=qt, or in a `with napari.gui_qt():` code block
viewer = napari.view_image(image, name='original', colormap='green', blending='additive')
result = np.array([hmaxima(image, f) for f in np.linspace(0.2, 100.0, num=100)])
res_layer = viewer.add_image(result, name='result', colormap='magenta', blending='additive')
```

**Comment by jni** [comment] 2019-10-02 09:53
I suspect that this has to do with the handling of the `resolution` variable here:

https://github.com/scikit-image/scikit-image/blob/e28ccfbd2abf818c1d972bd6b89c873be2f959b3/skimage/morphology/extrema.py#L114-L118

One concerning thing is that if the image is float32, which it is here, `resolution / 2` gets cast to float64, and `h - resolution / 2` is float64, while `image - h` is float32. I don't know whether this will then cause problems but it's plausible that it would.

**Comment by w-hc** [comment] 2019-10-02 14:14
I tried changing the heatmap dtype to float64 but the error persists, albeit with different number of maxima.

```python
import numpy as np
from skimage.morphology import h_maxima
from scipy import ndimage as ndi
heatmap = np.load('heatmap.npy').astype(np.float64)
assert heatmap.dtype == np.float64
for h in np.linspace(0.2, 4.0, num=10):
    num_instances = ndi.label(h_maxima(heatmap, h))[1]
    print('at h= {:.3f}, discovered {} instances'.format(h, num_instances))
```

```
at h= 0.200, discovered 25 instances
at h= 0.622, discovered 12 instances
at h= 1.044, discovered 25 instances
at h= 1.467, discovered 21 instances
at h= 1.889, discovered 11 instances
at h= 2.311, discovered 14 instances
at h= 2.733, discovered 23 instances
at h= 3.156, discovered 16 instances
at h= 3.578, discovered 17 instances
at h= 4.000, discovered 23 instances
```

**Comment by w-hc** [comment] 2019-10-02 14:56
Just to confirm, the intensity parameter in `peak_local_max` works differently than h in `h_maxima`, right? 

I have been trying to understand the exact meaning of `h_maxima` and find the doc in skimage quite difficult to parse. 


A local maximum M of height h is a local maximum for which there is at least one path joining M with a higher maximum on which the minimal value is f(M) - h (i.e. the values along the path are not decreasing by more than h with respect to the maximum’s value) and no path for which the minimal value is greater.

After a bit of research, my current understanding is that `h_maxima` is equivalent to:
1. Finding all morphological local maxima
2. Throw away those maxima whose 'height' <= h
    where 'height' is defined as how much you can descend from this local peak without rising up again. 

It is implemented by morphological reconstruction but in effect it is equivalent to what I described above. (disregarding the fact that height of remaining maxima would decrement by h)

**Comment by HazenBabcock** [comment] 2020-03-03 16:37
It looks like a rounding error, if you multiply everything by 10 you get more sensible results.

```
tmp = (10.0 * heatmap)

for h in np.linspace(2, 40, num=10):
    num_instances = ndi.label(h_maxima(tmp, int(h)))[1]
    print('at h= {:.3f}, discovered {} instances'.format(h, num_instances))
```

```
at h= 2.000, discovered 25 instances
at h= 6.222, discovered 25 instances
at h= 10.444, discovered 25 instances
at h= 14.667, discovered 25 instances
at h= 18.889, discovered 24 instances
at h= 23.111, discovered 24 instances
at h= 27.333, discovered 23 instances
at h= 31.556, discovered 23 instances
at h= 35.778, discovered 23 instances
at h= 40.000, discovered 23 instances
```

**Comment by HazenBabcock** [comment] 2020-03-03 16:58
This is very ad-hoc, but if you change `h_maxima` in `morphology/extrema.py` to:

```
        resolution = 2 * numpy.finfo(image.dtype).resolution
        if h < resolution:
            h = resolution
        h_corrected = h - 2 * resolution
        shifted_img = image - h
```

Then the example works as expected.

**Comment by emmanuelle** [comment] 2020-03-03 20:12
@HazenBabcock thanks a lot for taking a look! Are you interested in working in a pull request in order to correct this bug? We can help you of course in this process, if you wish.

**Comment by HazenBabcock** [comment] 2020-03-03 21:03
@emmanuelle Sure, happy to try.

**Comment by emmanuelle** [comment] 2020-03-03 21:34
Great, thank you so much :-)! One difficult part is maybe to add a unit test which would fail currently and pass if you can fix the bug, but if the current test suite passes and the example of @w-hc is fixed (when testing manually), this will definitely be an improvement.

**Comment by HazenBabcock** [comment] 2020-03-04 18:57
I think I have a test and fix in my fork, feedback welcome. It is two commits, test first so that you can see the failure without the fix.

I should also fix `extrema.h_minima()`?

This still doesn't work correctly for the h = 0.0 case however. Should that be documented as ambiguous? Or should this give the same results as `extrema.local_maxima()`?

**Comment by emmanuelle** [comment] 2020-03-04 19:30
Awesome! Could you please open a pull request from your branch so that we can comment on the pull request? If you think that `h_minima` needs to be fixed in the same way, yes, please, that'd be great :-). 

For `h=0.0` this is definitely a corner case; I would suggest to raise a `ValueError` and mention `local_maxima` in the error message. Would that seem reasonable to you? I'd prefer users to use explicitly `local_maxima` without having it used under the hood. Since the current behaviour is buggy, no need to set up a deprecation cycle for such a change.

**Comment by HazenBabcock** [comment] 2020-03-04 20:27
Hmm, I think I just found another bug, possibly in both versions. If h is greater than the maximum difference in the image `h_maxima` will still return the highest maxima in the image. I'm pretty sure that in this case it should return nothing, so some more work to do here.

**Comment by emmanuelle** [comment] 2020-03-04 20:39
Good catch, thanks. If you think this other bug comes from the reconstruction function (hopefully not) you can open another issue which will be fixed later, as you wish.

**Comment by HazenBabcock** [comment] 2020-03-04 21:53
Another issue is that `h_maxima` is silently upgrading `shifted_img` to numpy.float64 if `h` is not an integer. Should we enforce that the type of `h`  matched that of `image`?

**Comment by emmanuelle** [comment] 2020-03-04 22:12
Hum, this _would_ be a breaking change. It does not make much sense I think to provide a float `h` when `image` is of integer type - or maybe it does for half integers? I'm not sure. One possibility would be to modify the docstring, which is inexact at the moment (it says that `h` is integer, but it's a scalar). We could mention that there will a cast to float if `h` is float and `image` is integer (which can be a problem for the memory footprint, otherwise I don't think this is a problem - or am I missing something?).

**Comment by HazenBabcock** [comment] 2020-03-05 17:11
The problem is that fails for some non-integer values of h. I added a test that demonstrates this, as well as test that demonstrates the `h_maxima` (for floats) doesn't work correctly for large h. I've created a pull request for this. I see already that it is not PEP8 compliant..

**Comment by emmanuelle** [comment] 2020-03-05 19:21
Great! Don't worry too much about PEP8, it's more an indication. If you fix some of it it's cool, but we don't have our CI depend on this so it's more indicative really.

**Closed** 2020-04-22 08:22 UTC
Labels: priority: critical, type: bug
