### ISSUE TITLE
Adding target number of points to skimage.measure.approximate_polygon

### ISSUE THREAD

**Issue by ad-si** [scikit-image/scikit-image#2988] opened 2018-03-19 22:59 UTC
I was thinking about implementing a mode for `approximate_polygon` where you specify the target number of points instead of the maximum tolerance.

E.g. `approximate_polygon(coords, target_count=10)` would then mean "simplify polygon until it has 10 coordinate points"

Shall I open a PR for this?

**Comment by soupault** [comment] 2018-03-20 06:00
Yes, feel free to submit a PR.
Closing as a duplicate of https://github.com/scikit-image/scikit-image/issues/2212 .

**Closed by soupault** 2018-03-20 06:00 UTC

**Comment by stefanv** [comment] 2018-03-20 07:03
That sounds like a good feature to have, thanks @ad-si
