### ISSUE TITLE
MCP_Geometric generates negative cumulative costs

### ISSUE THREAD

**Issue by ozak** [scikit-image/scikit-image#1912] opened 2016-01-28 00:15 UTC
Hi y'all,

I just noticed that `MCP_Geometric` generates negative cumulative costs whenever the starting point is in a negative cell. In principle it should juts generate `inf` for all the matrix but somehow it is showing negative and positive values...here's a minimal working example:

```
import skimage.graph as graph
import numpy as np

# Declare cost matrix
costs = np.ones((10,10))
# Create row with only negative values (should prevent one half of the matrix to connect to the other)
costs[5,:]=-9
# Create MCP_Geometric object
mcp=graph.MCP_Geometric(costs)
# Compute cumulative costs
#1. cell on positive values (Notice correct values and non-connectivity)
right_cumulative_costs, traceback = mcp.find_costs([[3,0]])
#2. cell on negative values (Notice incorrect values and connectivity!)
wrong_cumulative_costs, traceback = mcp.find_costs([[5,0]])
```

Am I missing something or is this a know issue? Using a masked array generates the same issue. I have tried this on two installations, one has version `0.12-dev` pip installed on OS-X 10.9 the other one has `0.11.3` from the Anaconda distribution.

**Comment by stefanv** [comment] 2016-02-02 15:48
Lower cost indicates more likely paths, so you probably want to use ``inf`` instead of ``-9``.

**Comment by ozak** [comment] 2016-02-02 16:30
Hi @stefanv thanks for your answer. In the docs it says ``Array elements with infinite or negative costs will simply be ignored, as will paths whose cumulative cost overflows to infinite.`` [see here](http://scikit-image.org/docs/dev/api/skimage.graph.html#skimage.graph.MCP_Geometric). And as is shown in the example I provided the problem is generated when the initial point lies on a cell that should be ignored (For the initial point in a correct location things works perfectly). I have used ``numpy.masked_array``s which basically assing ``nan`` and the same issue arises. I think it is missing a check or something. Moreover, in some of the GIS computations I am working on, I get cumulative costs between locations that should have been excluded.

**Comment by ozak** [comment] 2016-02-05 06:18
Looking at the output of my example I also noticed that the command is returning the actual array instead of a copy. Thus, in the previous example one ends up with ``right_cumulative_costs`` being equal to ``wrong_cumulative_costs``. I think returning copied would make more sense in order to avoid possible problems for users.

**Comment by rfezzani** [comment] 2020-10-13 09:23
I can't reproduce the issue @ozak :
```python
>>> np.array_equal(right_cumulative_costs, wrong_cumulative_costs)
True
```
I close it, but feel free if you disagree to reopen :wink:

**Closed by rfezzani** 2020-10-13 09:23 UTC
