### ISSUE TITLE
roundtrip hed -> rgb -> hed is broken

### ISSUE THREAD

**Issue by cgebbe** [scikit-image/scikit-image#6104] opened 2021-12-06 16:29 UTC
## Description

It seems the roundtrip hed -> rgb -> hed has been broken recently:

## Way to reproduce
```python
  img_in = np.random.uniform(size=(10,10,3))
  img_out = skimage.color.rgb2hed(skimage.color.hed2rgb(img_in))
  np.testing.assert_array_almost_equal(img_in, img_out)  #  throws an error
```

## Version information

```python
3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Windows-10-10.0.19042-SP0
scikit-image version: 0.19.0
numpy version: 1.20.3
```

## Possible root cause

I believe that the root cause is the added `np.maximum`, see https://github.com/scikit-image/scikit-image/blame/main/skimage/color/colorconv.py#L1578

## Existing test

There already is a test for hed->rgb->hed conversion, namely https://github.com/scikit-image/scikit-image/blob/v0.19.x/skimage/color/tests/test_colorconv.py#L241 . However, `self.img_stains` only has float values until 0.3. We can make the test above pass by enforcing...

```python
    img_in = np.random.uniform(size=(10,10,3)) * 0.3   # note the additional 0.3!
    img_out = skimage.color.rgb2hed(skimage.color.hed2rgb(img_in))
    np.testing.assert_array_almost_equal(img_in, img_out)  # passes
```

**Comment by mkcor** [comment] 2021-12-07 13:41
Hello @cgebbe,

> I believe that the root cause is the added `np.maximum`, see https://github.com/scikit-image/scikit-image/blame/main/skimage/color/colorconv.py#L1578

:thinking: I wouldn't think so, since `img_in` contains no negative value... So we wouldn't expect `img_out` to contain negative values either...

**Comment by rfezzani** [comment] 2021-12-08 08:10
Thank you @cgebbe for reporting, I can reproduce!

**Comment by rfezzani** [comment] 2021-12-08 08:45
OK, it seems that the round trip breaking was expected: please see https://github.com/scikit-image/scikit-image/issues/5164#issuecomment-754077092 and it seems that you are right @cgebbe, `np.maximum` is causing this.

**Comment by rfezzani** [comment] 2021-12-13 09:08
@scikit-image/core, do we consider this is a bug or an expected behavior? Should we close?

**Comment by mkcor** [comment] 2021-12-13 15:43
At this point, I would consider it expected behaviour, but we should say something about it in the docstring. So maybe relabel this issue from 'bug' to 'documentation?'

My understanding is that there is no perfect solution, from what @crisluengo explained ("Every lab produces different colors for the same stains..."), also in this more recent thread: https://github.com/scikit-image/scikit-image/discussions/6065#discussioncomment-1708113

**Comment by alexdesiqueira** [comment] 2022-01-20 04:20
@rfezzani @mkcor I think that we should deal with this as a documentation "issue" right now. However, I will get back to this at some point in time and check how other packages deal with this (not in the near future, for sure :slightly_smiling_face:).

**Comment by crisluengo** [comment] 2022-01-20 22:27
@cgebbe There are colors that cannot be represented in this HED "color space". HED represents the combination of three stains commonly used in microscopy: Hematoxylin (blue/purple), Eosin (pink) and DAB (brown). There is no way to combine these three stains to obtain, for example, green. So in your input random image, any greenish pixel, when converted to HED, will necessarily change color.

Conversion from RGB to HED should be applied only to images of tissue stained with these stains. Conversion from HED to RGB can be used to simulate what such a stained tissue would look like. Don't use HED as a generic color space such as RGB, CMYK, Yxy, Lab, etc.

**Comment by grlee77** [comment] 2022-02-25 03:01
I am going to close this as answered. It does not seem that new changes are necessary

**Closed by grlee77** 2022-02-25 03:01 UTC
Labels: type: documentation
