### ISSUE TITLE
A short book has been created from your examples

### ISSUE THREAD

**Issue by tirthajyoti** [scikit-image/scikit-image#4916] opened 2020-08-14 07:43 UTC
I have created a short book from many of your examples so that interested folks can navigate through methods in an easy manner.

I am hosting it here: https://tirthajyoti.github.io/Scikit-image-book/Intro.html

Hope this is alright with your team.

**Comment by jni** [comment] 2020-08-15 02:28
@tirkarthi thanks for the heads-up!

Our code license is BSD, which means that *it needs to be reproduced in distributed derivative works*. So, what I would appreciate is, in the section "Examples from the scikit-image website", to add (a) a link to the source material, either scikit-image.org directly or the gallery, and explicitly mention, "the code examples are used here under the terms of the BSD-license of the scikit-image project."

Also, ideally, this acknowledgement would come at the very top of the book, next to your authorship. e.g. rather than "Dr Dr. Tirthajyoti Sarkar", which strongly implies authorship, that section could say "examples curated and annotated by Dr. Tirthajyoti Sarkar, based on the scikit-image.org gallery [link], and used here under the terms of the BSD 3-clause license".

Does that sound fair?

Other than that, cool stuff! I've started to experiment with jupyter-book myself and love the project.

**Comment by jni** [comment] 2020-08-15 02:29
btw we can keep discussing here but I'm going to close this issue, since it's not actually an issue with the library. 🙂

**Closed by jni** 2020-08-15 02:29 UTC

**Comment by tirthajyoti** [comment] 2020-08-15 06:17
Thanks. I have implemented all the suggestions you made.
