### ISSUE TITLE
ValueError: Big-endian buffer not supported on little-endian compiler, when using skimage.transform.resize()

### ISSUE THREAD

**Issue by servoz** [scikit-image/scikit-image#4525] opened 2020-03-24 15:30 UTC
We're using scikit-image in [our project.](https://github.com/populse)
Since the upgrade to version 0.16.1 of scikit-image [we raise an ValueError exception](https://github.com/populse/populse_mia/issues/153) when using skimage.transform.resize() (no problems with scikit-image == 0.15.0)
```
Traceback (most recent call last):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 2085, in selection_changed
    self.data_browser.connect_mini_viewer()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 333, in connect_mini_viewer
    self.viewer.verify_slices(full_names)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 774, in verify_slices
    self.show_slices(file_paths)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 578, in show_slices
    self.image2DModifications(idx)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 413, in image2DModifications
    anti_aliasing=False)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
```

Is this a bug from the scikit-image project?

Do we have to adapt our codes? (in this last case, some informations to help to get around this problem will be very appreciate).

**Comment by sciunto** [comment] 2020-03-24 18:36
I would say it's a regression, but we need to investigate. I found this useful to understand the message: https://pandas.pydata.org/pandas-docs/version/0.19.1/gotchas.html#byte-ordering-issues

**Comment by jni** [comment] 2020-03-25 08:12
Hi @servoz and thank you for reporting this!

I think probably what is happening is that we used to pass your input data through `img_as_float`, but now we attempt to warp it without a copy. I'm going to guess your image is a 32-bit float? See this PR:

https://github.com/scikit-image/scikit-image/pull/3486

I think the short term fix for you is to use `skimage.transform.resize(skimage.util.img_as_float(image))`, rather than just `resize` directly. I don't have a big-endian array to test this on, though. Could you share your input data with us, @servoz?

**Comment by jni** [comment] 2020-03-25 08:13
Incidentally, I wouldn't consider this a bug on our end... Perhaps something we need to document.

**Comment by servoz** [comment] 2020-03-25 09:38
Hi jni and thank a lot for your help!
[Please, find an input data example we use](https://filesender.renater.fr/?s=download&token=11812510-7346-52ef-8afa-91554e2dd3d6).
Minimum steps to reproduce:
```
$ python
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nibabel as nib
>>> from skimage.transform import resize
>>> import skimage as sk
>>> from packaging import version
>>> file_path='file_path_for_data_example_videSupra'
>>> img=nib.load(file_path)
>>> img
<nibabel.nifti1.Nifti1Image object at 0x7fb42887d990>
>>> img.shap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Nifti1Image' object has no attribute 'shap'
>>> img.shape
(512, 512, 160)
>>> img_2D=img.get_data()[:, :, 80]
>>> img_2D
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> version.parse(sk.__version__)
<Version('0.15.0')>
>>> im2D = resize(img_2D, (128, 128), mode='constant',anti_aliasing=False)
```
Ok with scikit-image V0.15.0.

```
$ python3
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nibabel as nib
>>> from skimage.transform import resize
>>> import skimage as sk
>>> from packaging import version
>>> file_path='file_path_for_data_example_videSupra'
>>> img=nib.load(file_path)
>>> img
<nibabel.nifti1.Nifti1Image object at 0x7f05c81e3510>
>>> img.shape
(512, 512, 160)
>>> img_2D=img.get_data()[:, :, 80]
>>> img_2D
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> version.parse(sk.__version__)
<Version('0.16.2')>
>>> im2D = resize(img_2D, (128, 128), mode='constant',anti_aliasing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
```

Not working with scikit-image V0.16.2.

```
$ python3
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nibabel as nib
>>> from skimage.transform import resize
>>> import skimage as sk
>>> from packaging import version
>>> from skimage.util import img_as_float
>>> file_path='file_path_for_data_example_videSupra'
>>> img=nib.load(file_path)
>>> img
<nibabel.nifti1.Nifti1Image object at 0x7ffa540e1510>
>>> img.shape
(512, 512, 160)
>>> img_2D=img.get_data()[:, :, 80]
>>> img_2D
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> img_as_float(img_2D)
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> im2D = resize(img_as_float(img_2D), (128, 128), mode='constant',anti_aliasing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
```

Not working with scikit-image V0.16.2. and skimage.transform.resize(skimage.util.img_as_float(image))

I will carefully read the PR you propose to read (not yet had time to do so).
Thank you for all the informations that will help us save time in fixing this problem.

**Comment by servoz** [comment] 2020-03-25 09:58
Hum ... As proposed by @sciunto :

```
>>> import nibabel as nib
>>> from skimage.transform import resize
>>> import skimage as sk
>>> from packaging import version
>>> from skimage.util import img_as_float
>>> file_path='file_path_for_data_example_videSupra'
>>> img=nib.load(file_path)
>>> img
<nibabel.nifti1.Nifti1Image object at 0x7ffa540e1510>
>>> img.shape
(512, 512, 160)
>>> img_2D=img.get_data()[:, :, 80]
>>> img_2D
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> img_2D.byteswap().newbyteorder()
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> im2D = resize(img_2D.byteswap().newbyteorder(), (128, 128), mode='constant',anti_aliasing=False)
```

with scikit-image V0.16.2, converting the underlying array to the native system byte order seems to be a possible working around ...

**Comment by jni** [comment] 2020-03-30 12:48
@servoz does this workaround fix the issue on your end?

**Comment by jni** [comment] 2020-03-30 12:49
By the way, I think the reason `img_as_float` failed is that we now also just pass through float32s. `img_as_float64` might fix things... But I don't know, to be honest, just how much automation NumPy has when it comes to dealing with byte order.

**Comment by servoz** [comment] 2020-03-30 14:48
Thank you @jni  !!
Actually it's all our fault... Since your last message, I have started working on this problem again and I have been observing:
```
>>> import nibabel as nib
>>> from skimage.transform import resize
>>> import skimage as sk
>>> from skimage.util import img_as_float
>>> from skimage.util import img_as_float32
>>> from skimage.util import img_as_float64
>>> file_path='file_path_for_data_example_videSupra'
>>> img=nib.load(file_path)
>>> img_2D=img.get_data()[:, :, 80]
>>> sk.__version__
'0.16.2'
>>> img_2D
memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> img_as_float(img_2D)
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> img_as_float32(img_2D)
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> img_as_float64(img_2D)
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
>>> im2D = resize(img_2D, (128, 128), mode='constant',anti_aliasing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
>>> im2D = resize(img_as_float(img_2D), (128, 128), mode='constant',anti_aliasing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
>>> im2D = resize(img_as_float32(img_2D), (128, 128), mode='constant',anti_aliasing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/econdami/.local/lib/python3.7/site-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
>>> im2D = resize(img_as_float64(img_2D), (128, 128), mode='constant',anti_aliasing=False)
>>> im2D = resize(img_2D.byteswap().newbyteorder(), (128, 128), mode='constant',anti_aliasing=False)
```
at that moment I realised that the problem was either that the data was in big-endian or that it was not in float64!
Indeed:
```
>> import numpy
>>> numpy.result_type(img_2D)
dtype('>f4') # big-endian float32 -> not supported on my computer (compiler)
>>> numpy.result_type(img_as_float(img_2D))
dtype('>f4') # big-endian float32 -> not supported on my computer (compiler)
>>> numpy.result_type(img_as_float32(img_2D))
dtype('>f4') # big-endian float32 -> not supported on my computer (compiler)
>>> numpy.result_type(img_as_float64(img_2D))
dtype('float64') # supported on my computer (compiler)
>>> numpy.result_type(img_2D.byteswap().newbyteorder())
dtype('<f4') # little-endian float32-> supported on my computer (compiler)

```
and I remembered that `nibabel.danibabel.dataobj_images.DataobjImage.get_data()` is  deprecated, due to return type prediction problems, in favor of `nibabel.danibabel.dataobj_images.DataobjImage.get_fdata()`.
Indeed:
```
>>> img_2DBis=img.get_fdata()[:, :, 80]
>>> numpy.result_type(img_2DBis)
dtype('float64')
```

So I'm very confused, the problem comes only from our side and we will have to change all the get_data() functions by get_fdata() from our side on our old codes ...
Thank you for this discussion which put me on the way !
Unless you see something else, I think this ticket can be now closed !

**Comment by rfezzani** [comment] 2020-03-30 15:04
Thank you for your feedback @servoz, closing this issue then.

**Closed by rfezzani** 2020-03-30 15:04 UTC
Labels: type: bug
