### ISSUE TITLE
binary erosion attach to Image boundaries

### ISSUE THREAD

**Issue by Borda** [scikit-image/scikit-image#1462] opened 2015-04-02 15:17 UTC
Hello, I used the erosion and while there is an object attached to image boundary it keeps this link like the boundary is also the object, is it correct behavior? Thanks

**Comment by JDWarner** [comment] 2015-04-02 19:18
Yes. This is intended behavior. The correct padding behavior for binary erosion is to pad with 1s; you can also think of this as if _only_ the zero pixels _actually in the image_ erode the image. If your structuring element is large enough the object overlapping the boundary will be completely eroded, but it has to happen from the inside.

Consider the alternative. If zero padding were employed, especially for fairly large structuring elements, the result would eat away everything around the edge.

I'm closing the issue, but if you need any further clarification I'm happy to continue discussing in the closed thread.

**Closed by JDWarner** 2015-04-02 19:18 UTC
