### ISSUE TITLE
RAG example incomplete

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2148] opened 2016-06-13 21:33 UTC
@jni, @vighneshbirodkar What is going on with this example: http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_boundary_merge.html#sphx-glr-auto-examples-segmentation-plot-boundary-merge-py ? Specifically, the TODO in the beginning :-)

**Comment by soupault** [comment] 2016-06-13 21:37
@ahojnnes this is the issue with 2/3 plots - https://github.com/scikit-image/scikit-image/issues/2059#issue-151394133 .
This one is about TODO - https://github.com/scikit-image/scikit-image/issues/2099, https://github.com/scikit-image/scikit-image/pull/2106.

**Comment by soupault** [comment] 2016-06-13 21:43
Ignore first part, not related.

As for tiny plots' size, `sphinx-gallery` changed the appearance a bit. Need to revise all the plots.

**Comment by soupault** [comment] 2016-06-17 08:04
@ahojnnes Do you mind closing this as duplicate?

**Comment by soupault** [comment] 2016-06-18 10:47
Closed as a duplicate of #2099.

**Closed by soupault** 2016-06-18 10:47 UTC
