### ISSUE TITLE
Possible error in SLIC with the start_label parameter

### ISSUE THREAD

**Issue by JuanIgnacioCG** [scikit-image/scikit-image#6240] opened 2022-02-09 14:30 UTC
## Description
I think there is an error in the SLIC segmentation. When I applied the segmentation in one image I use the predefined parameter start_label=1,  but, in certain cases, the resulting superpixels start at 0. I have checked other odd things as well:
  - I was checking the effect of changing the superpixel size. The num_segments is computed based on the size of the image divided by each element of the list of [4,9,16,25,36,49]. The error appears for the cases of 36 and 49. In the cases of [4,9,16,25] the segmentation is correct.
  - The pixels labeled as 0 are not connected. 

![imagen](https://user-images.githubusercontent.com/52458775/153220569-def89b9c-3ed2-4fdf-97df-c0c522dfd125.png)

## Way to reproduce
sample image is available at> https://acortar.link/MeH1kV
(it is 23KB)
```python
# Place the full code we need to recreate your issue here
import numpy as np
import pandas as pd
from pathlib import Path
import napari
from PIL import Image
import imageio as iio
from napari.utils import nbscreenshot
from skimage.segmentation import slic 

# slic based on number of pixels
def get_spp(array2d,r_psp,compactness,multichannel=False,convert2lab=False):
    num_segments = array2d.size / r_psp
    superp = slic(array2d,
              start_label=1,
              multichannel=multichannel,
              n_segments=num_segments,
              compactness=compactness,
              convert2lab=convert2lab)
    print('Real number of superpixels: ',np.max(superp))
    return superp

compactness=1
ruta_tst = Path(r"pathtoimg")
tst_img = iio.imread(ruta_tst)
tst_superp = get_spp(tst_img,36,compactness)
tst_viewer = napari.view_labels(tst_superp)
```

## Version information
Python 3.8.12
 print(skimage.__version__)
0.18.3

import sys; print(sys.version)
3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]

import platform; print(platform.platform())
Windows-10-10.0.19042-SP0

import numpy; print(f'numpy version: {numpy.__version__}')
numpy version: 1.21.2

# your output here
The shown image is the result of the napari.view_labels for the provided piece of code. it can be checked that there is a label=0, even though it should start at 1.

**Comment by grlee77** [comment] 2022-02-09 20:51
Thanks for raising the issue @JuanIgnacioCG, I will take a look

**Comment by grlee77** [comment] 2022-02-09 21:09
I can observe a similar behavior in v0.19.3, but have to adjust to a substantially smaller connectivity value due to changes made in #5518. Specifically, the function always rescales the input to range [0, 1] internally so that a given connectivity has the same relative effect across images of different scale. However, this is a change from the prior behavior. 

Below is where I have zoomed in on part of the output when I set connectivity = 0.01. In this case, I see an area at the top left that is zero as well as a very small area at the top right that is also 0. So these looks like it is perhaps not an issue of superpixel labels incorrectly starting at zero, but instead perhaps an issue of some regions not getting assigned to any superpixel label and thus remaining 0. 

![slic_output1](https://user-images.githubusercontent.com/6528957/153289841-f2508f01-ee63-4eb7-98f0-c6ccb7d9dc3a.png)

Additionally, if I use a large connectivity where the superpixels start to become uniform squares, then the labels start at 1 as expected and there are no omitted regions.

I will still need to look into the cause of the 0 in the case with a smaller connectivity value setting

**Comment by grlee77** [comment] 2022-02-09 21:20
Another empirical observation: If `enforce_connectivity=False`, then even with very small connectivity, the labels start at 1 (although obviously, they are no longer so nicely contiguous). So this indicates that perhaps the issue lies somewhere in the code enforcing connectivity of the superpixels.

**Comment by grlee77** [comment] 2022-02-09 22:53
I think this issue gets fixed via the single line change in #6242. I will try to get that PR merged for v0.19.2.

A potential workaround in the meantime is to try reducing `min_size_factor` a bit, which seems to make it less likely to occur. Reducing that size factor will likely lead to a larger number of superpixels, though.

**Comment by JuanIgnacioCG** [comment] 2022-02-10 11:14
Hello!
thanks for the anwer grlee77! I get a bit lost in the explanation because I do not know the inner working of the Slic implementation, nor cython. In any case, I will check the effect of the min_size_factor. 

It is being an interesting experience, it´s the second time I raise an issue. The first one somebody checks and suggest a pull request that needs the approval of a reviewer (If I got 6242 right). I will follow the process. 
Have a good day.

**Comment by grlee77** [comment] 2022-02-10 12:45
> The first one somebody checks and suggest a pull request that needs the approval of a reviewer (If I got 6242 right).

Yes, another scikit-image maintainer will have to approve the pull request I made yesterday. Once that is done we will merge the change and the next release should have the fix. You will not have to do anything else on your end for this PR. I appreciate that you included an image to help us easily reproduce the issue!

**Closed** 2022-02-14 14:10 UTC
