### ISSUE TITLE
Small bug in skimage.feature.peak_local_max()

### ISSUE THREAD

**Issue by arares** [scikit-image/scikit-image#3019] opened 2018-04-16 17:37 UTC
## Description
When provided both `min_distance` and `threshold_abs` parameters to the `skimage.feature.peak_local_max()` function, the first parameter takes unnecessary precedence over the second one. I did not look at the code, but from my experiments it appears that a list of peaks is calculated internally, then the first constrained is applied, and then the second one. However, if there is a peak above the given threshold that lies to the right of another one under the threshold, but close to it (under `min_distance`), it will be rejected because of its proximity. As such, a tiny peak that will be excluded from the final list anyway manages to eclipse a big peak. I think the threshold criterion should be applied before the minimal distance criterion. Even better, the problem would not appear if the list of thresholds would be processed in decreasing height order, rather than top-down, left-right order (as I guess it is done now).

**Comment by sciunto** [comment] 2018-04-24 09:40
Hi,

Thanks for the report.
Your proposition makes sense to me. However, we are planning to refactor the peak detection provided in scikit-image (See #3022) and it might not be worth to fix a function that will be deprecated relatively soon.

**Comment by emmanuelle** [comment] 2018-06-01 22:04
Thank you for the issue. We need to fix it. Can you please provide a small snippet of code so that we can reproduce the problem (and put it in a test for the future function)?

**Comment by stefanv** [comment] 2018-06-01 22:06
This seems to be orthogonal to the changes proposed in #3022.

Solution: sort peaks by amplitude, and suppress nearby neighbors.

**Comment by sciunto** [comment] 2018-06-02 10:08
I thought that #3022 would have been merged in 0.14. Now it makes sense to merge a fix in the LTS version.

**Comment by jni** [comment] 2018-06-02 15:46
#3022 is almost definitely destined for 0.14 as well.

**Comment by rfezzani** [comment] 2020-10-13 08:25
I think this is fixed now by #4501 and #4582. Feel free to reopen if you disagree :wink:

**Closed by rfezzani** 2020-10-13 08:25 UTC
Labels: type: bug
