### ISSUE TITLE
regionprops dimensions of one and single element regions

### ISSUE THREAD

**Issue by earthflat** [scikit-image/scikit-image#2105] opened 2016-05-23 14:09 UTC
Hi,

skimage.measure.regionprops does not handle images with an axis having a of size 1 correctly. E.g. an image of shape (1,3), which has a single row, is not detected as an 2D-image and an error is thrown, which says, that only 2D and 3D image are allowed.
Same for 3D images of e.g. shape (1,1,3).

Further, properties of regions with only one pixel are not correct. At least the property 'major_axis_length' results in 0.0 for a single pixel region (guess it should be the diagonal of the pixel: sqrt(2)).

**Comment by jni** [comment] 2016-05-23 23:46
Your first point is valid, but I'm not sure about the second one... I think single-pixel regions can be correctly considered point sources, see ["A pixel is not a little square"](http://alvyray.com/Memos/CG/Microsoft/6_pixel.pdf).

**Comment by stefanv** [comment] 2016-05-24 00:43
I agree with Juan, here.  But you can very easily write a function to
detect this extreme case and replace the major_axis_length with you own
preferred value.

**Comment by jni** [comment] 2016-05-24 00:52
@stefanv here's the cause of the first error:

https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py#L520

I'm not sure how to deal with this. I don't know why it's there. I can just remove it, but there's a 100% chance that someone's code will get messed up because of it. So my preferred course of action is:

- squeeze the image
- if it results in an invalid image, go back to the original image
- if that's still invalid, raise the error.

What do you think?

**Comment by ahojnnes** [comment] 2016-05-24 06:20
How about a `np.atleast_2d(np.sequeeze(label_image))`? It is probably there for the cases where the shape of the input image is `(rows, cols, 1)`...

**Comment by soupault** [comment] 2016-05-24 06:43
@ahojnnes this will make 1-column and 1-row images indistinguishable and therefore lead to erroneous properties.

**Comment by stefanv** [comment] 2016-05-24 22:43
Removing the squeeze is not too bad.  If these inputs accidentally worked
before, they will eventually break things in the future, so better be
strict about shape interpretation now.

**Comment by rfezzani** [comment] 2020-02-20 16:00
I see [here](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py#L652) that this is no more an issue. Closing ;-)

**Closed by rfezzani** 2020-02-20 16:00 UTC
Labels: type: bug
