### ISSUE TITLE
`width` and `height` swapped in `morphology.rectangle`

### ISSUE THREAD

**Issue by FirefoxMetzger** [scikit-image/scikit-image#4925] opened 2020-08-17 11:57 UTC
https://github.com/scikit-image/scikit-image/blob/20297dca8c797ca91ad515d0cd8d6f738a4e8b9e/skimage/morphology/selem.py#L57

I just noticed that the rectangle structuring element behaves inconsistently. The line should be:

```
return np.ones((height, width), dtype=dtype)
```

or the variables should be renamed.

**Comment by jni** [comment] 2020-08-17 12:39
@FirefoxMetzger This is a duplicate of #4125. See the discussion in the #4126 (stalled PR) for the proposed fix. We'd certainly welcome the proper deprecation fix!

In the meantime I'll close this as duplicate, though. =) Thank for reporting!

**Closed by jni** 2020-08-17 12:39 UTC
