### ISSUE TITLE
warp returns all-NaN for cval=NaN and order>1

### ISSUE THREAD

**Issue by melanieclarke** [scikit-image/scikit-image#6266] opened 2022-02-24 22:36 UTC
## Description

In scikit-image 0.19 and later, warp is returning arrays with all-NaN values when cval=np.nan and the interpolation order is higher than 0 or 1.

The code below prints False for all combinations of cval and order in v0.18.3; True for cval=np.nan and order>1 in v0.19.2.

```
cval=0 order=0: all nan False
cval=0 order=1: all nan False
cval=0 order=2: all nan False
cval=0 order=3: all nan False
cval=0 order=4: all nan False
cval=0 order=5: all nan False
cval=nan order=0: all nan False
cval=nan order=1: all nan False
cval=nan order=2: all nan True
cval=nan order=3: all nan True
cval=nan order=4: all nan True
cval=nan order=5: all nan True
```

<img width="620" alt="scikit0 19 2" src="https://user-images.githubusercontent.com/2838388/155618122-46ee3b65-8e13-4eed-a230-40ad4b26674a.png">

## Way to reproduce
```python
import numpy as np
from skimage.transform import PiecewiseAffineTransform, warp
from matplotlib import pyplot as plt

dest = np.array([[0.,0.],[46.,11.5],[92.,23.],[0.,46.],[46.,57.5],
                [92.,69.],[0.,92.],[46.,103.5],[92.,115.]])
src = np.array([[0,0],[92,23],[184,46],[0,92],[92,115],[184,138],
                 [0,184],[92,207],[184,230]])
P = PiecewiseAffineTransform()
P.estimate(src, dest)

data = np.arange(100*100, dtype=float).reshape(100, 100)
cval = [0, np.nan]
fig, ax = plt.subplots(2, 6)
for i, c in enumerate(cval):
    for o in range(6):
        wdata = warp(data, P, cval=c, order=o, mode='constant')
        print(f'cval={c} order={o}: all nan {np.all(np.isnan(wdata))}')
        ax[i][o].imshow(wdata)
fig.tight_layout()
plt.show()
```

## Version information

```python
3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
macOS-10.16-x86_64-i386-64bit
scikit-image version: 0.19.2
numpy version: 1.20.3
```

**Comment by grlee77** [comment] 2022-02-24 23:51
We do not have any testing for the behavior of image transforms (or most other scikit-image functions) on images with NaNs. scipy.ndimage also doesn't really handle NaNs. Given that this occurs only for order > 1, it is most likely related to the spline prefiltering that is only used in those cases. Specifically, the prefilter is an IIR filter which would propagates any NaN value at the edge across the whole image. This may also be related to introduction of [internal pre-padding that is done with SciPy 1.6 for "grid-constant" mode](https://github.com/scipy/scipy/blob/9e8df2e78d1df43bc04fe6a6b846c96d7b8e9aaf/scipy/ndimage/_interpolation.py#L196-L209). Since scikit-image 0.19, using mode="constant" calls SciPy with mode="grid-constant" so that extra padding to get correct boundary behavior could be the cause.

To verify you could try pinning to "SciPy<1.6" while keeping scikit-image at its current version. One could in principle to edit the code within warp.py to first apply the prefilter with a different mode, although you would still have issues if there are any NaN values within the extent of the original image as these would still get propagated to the image edge by the spline prefilter. Or you could disable the prefilter entirely, but at cost of some image blurring.

If you really are sure there are never NaNs in the image, but you only want to introduce them outside of the original range, then a workaround may be to use a different, finite `cval=edge_value` and the later set (``output[output == edge_val] = np.nan``).

**Comment by melanieclarke** [comment] 2022-02-25 00:03
I see, thanks.  We were already working around NaNs in the image, but it used to work to specify NaN as the edge value at least.  I will add the additional handling for a finite cval for the border pixels.

**Comment by grlee77** [comment] 2022-02-28 20:48
I am going to close this, given the answer above, but feel free to continue the discussion and follow up here.

**Closed by grlee77** 2022-02-28 20:48 UTC
Labels: type: discussion
