### ISSUE TITLE
canny smoothing step is inaccurate for image of dtype uint8

### ISSUE THREAD

**Issue by mdickinson** [scikit-image/scikit-image#2981] opened 2018-03-08 11:17 UTC
## Description

The `smooth_with_function_and_mask` step of the Canny edge detector applies a SciPy `gaussian_filter` to the image data. For image data with dtype `np.uint8`, [this line](https://github.com/scikit-image/scikit-image/blob/897acb778c91e8152b947ffd3f172ef98d29f9f0/skimage/feature/_canny.py#L48) of that function also gives a `np.uint8` result, losing significant precision compared to the floating-point result.

I suspect that the line:

    smoothed_image = function(masked_image)

should be something like:

    smoothed_image = function(masked_image.astype(float))

to match the earlier invocation of the smoothing function on the mask:

    bleed_over = function(mask.astype(float))

Background: we discovered this after trying to understand why upgrading SciPy from 0.19.1 to 1.0.0 changed our detected edges on a particular np.uint8 image. It turned out that there were some epsilon-sized changes in the Gaussian kernel that SciPy was using, and because of the quantization in `smoothed_image` above, those tiny differences were magnified to significantly larger differences.

I regret that I can't share the images in question, for IP reasons; if it's useful, I can try to find time later to find non-IP-protected images that reproduce the effect.

Related comment from an earlier discussion (about adding a Gaussian filter): https://github.com/scikit-image/scikit-image/pull/204#issuecomment-7615629

**Comment by jni** [comment] 2018-03-13 08:50
Hi @mdickinson, thanks for the report! If you can make a reproducible test case, that would be invaluable towards getting this fixed.

**Comment by stefanv** [comment] 2018-03-13 19:24
I've made an initial PR here: https://github.com/scikit-image/scikit-image/pull/2983
I have no test yet, so would have to try and come up with that later today.

**Comment by itamarst** [comment] 2018-09-24 19:17
Looks like the PR was merged, so this should be closed?

**Comment by jni** [comment] 2018-09-25 09:49
@itamarst well spotted!

@mdickinson I am closing this for now. If scikit-image master doesn't fix your problem, please feel free to reopen.

**Closed by jni** 2018-09-25 09:49 UTC
Labels: good first issue, type: enhancement
