### ISSUE TITLE
lab2rgb got strange warning

### ISSUE THREAD

**Issue by zhangchenkai** [scikit-image/scikit-image#4506] opened 2020-03-12 12:52 UTC
## Description
LAB color space my have two implementation for its value range from wiki https://en.wikipedia.org/wiki/CIELAB_color_space

1. L(0,100) A(-127,128) B(-127,128)
2. L(0,100) A(-100,100) B(-100,100)
(I'm not sure if the value can reach the left and right value)

>  The scaling and limits of the a* and b* axes will depend on the specific implementation, as described below, but they often run in the range of ±100 or −128 to +127 (signed 8-bit integer).

However, I got some strange warnings when I tried to convert a LAB colored image to RGB image.

## Way to reproduce
```
import numpy as np
from skimage import color

t = np.empty([256,256,3])
t[:,:,0] = np.random.randint(1,99,[256,256])
t[:,:,1] = np.random.randint(-99,99,[256,256])
t[:,:,2] = np.random.randint(-99,99,[256,256])
r = color.lab2rgb(t)
```
However, I always got this warning even I set the random value in a open interval
> /usr/local/lib/python3.7/site-packages/skimage/color/colorconv.py:1068: UserWarning: Color data out of range: Z < 0 in 5105 pixels

## My question

1. What is the value range of LAB color space in skimage? I can't find any description in the documentation;
2. I think the lab2rgb() function may have a problem to recognize the valid value.

## Version information
```
python 3.7.6 (default, Dec 30 2019, 19:38:26)
[Clang 11.0.0 (clang-1100.0.33.16)]
Darwin-19.3.0-x86_64-i386-64bit
scikit-image version: 0.16.2
numpy version: 1.18.1
```

**Comment by jni** [comment] 2020-03-12 22:56
@zhangchenkai thanks for your question! 

1. Indeed we lack such a description! There are already actually duplicate existing issues for this: #1185 and #4474. We just haven't had the time to document these properly.

2. The problem is that the Lab color space is not actually rectangular, so, not all values in the possible range are valid: https://ninedegreesbelow.com/photography/pictures-of-color-spaces.html So, some values for a/b, even in range, and especially at high or low values of L, are not valid Lab tuples.

You can determine the range of Lab colors by creating an image containing all RGB colors and converting it:

```python
all_rgb = np.stack(
    np.meshgrid(*(np.arange(256, dtype=np.uint8),) * 3),
    axis=-1,
).reshape((2**12, 2**12, 3))
all_lab = color.rgb2lab(all_rgb)  # this will take a while
print(np.min(all_lab, axis=(0, 1)))
print(np.max(all_lab, axis=(0, 1)))
```

This gives:

```
[   0.        ,  -86.18302974, -107.85730021]
[100.        ,  98.23305386,  94.47812228]
```

So, it looks like we use the +/- 100 model, but there is some wiggle room around that. I'm not sure whether that is a bug or not... Perhaps someone from @scikit-image/core with more experience with colorspaces can comment?

**Comment by zhangchenkai** [comment] 2020-03-13 03:48
@jni Thanks for your detailed reply, that solved my problems, I appreciate it. Now I have a better understanding of these color space.

**Comment by jni** [comment] 2020-03-13 04:56
@zhangchenkai very happy to help! I am going to close this issue, as the remaining problem of updating our docs is captured by #1185.

**Closed by jni** 2020-03-13 04:56 UTC

**Comment by blue-sky54** [comment] 2022-10-15 09:26
Hello @jni and thanks for your answers, Now how can we fix the warning? Does this warning say that the result conversion is not totally correct?

**Comment by stefanv** [comment] 2022-10-18 18:47
@blue-sky54 I think this discussion is now at https://github.com/scikit-image/scikit-image/issues/1185

The warning from https://github.com/ptrstn/colorspaces/commit/c9679ca18c4d873b544c397b361ff11eff9ad712 says that invalid input values were provided to the conversion.
