### ISSUE TITLE
TypeError when running in Python optimized mode

### ISSUE THREAD

**Issue by gst** [scikit-image/scikit-image#3392] opened 2018-09-07 13:42 UTC
## Description
I'm investigating running a project, which use scikit-image, with python optimized mode.
The problem happens because the `_parse_docs()` function try to regex parse a docstring which is None.
I already fixed it on my side and can provide the patch ..

## Way to reproduce
scikit_image ==  0.14.0

`python2.7 -OO -c "import skimage.measure"`

**Comment by hmaarrfk** [comment] 2018-09-07 14:01
I think you meant to do

```
import skimage.measure
```

I don't know why `scikit_image.measure` doesn't raise a module not found error.

I was able to reproduce this on my machine (linux + conda + python2.7 + pip install, conda install might also cause I problem).

**Comment by hmaarrfk** [comment] 2018-09-07 14:08
sorry emmanuelle, I guess i'm not thinking staight.

@gst, the error:
```
ImportError: No module named scikit_image.measure
```
is factual. There is no module called `scikit_image` just `skimage` happy coding!

**Comment by gst** [comment] 2018-09-07 18:02
oupsss my bad, effectively it's `skimage.measure`

**Comment by gst** [comment] 2018-09-07 19:52
No particular setup, just use `python -O` 
**NB:** I'm not using master but **v0.14.x**  given master doesn't support anymore python2..

```
15:49 $ python -O -c "import skimage.measure ; print skimage"
<module 'skimage' from 'skimage/__init__.pyo'>
(venv) ✔ ~/work/public/python/scikit-image [v0.14.x|✚ 1…90] 

15:49 $ python -O -c "import skimage.measure ; print skimage"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "skimage/data/__init__.py", line 18, in <module>
    from ._binary_blobs import binary_blobs
  File "skimage/data/_binary_blobs.py", line 2, in <module>
    from ..filters import gaussian
  File "skimage/filters/__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "skimage/restoration/__init__.py", line 12, in <module>
    from .inpaint import inpaint_biharmonic
  File "skimage/restoration/inpaint.py", line 9, in <module>
    from ..measure import label
  File "skimage/measure/__init__.py", line 6, in <module>
    from ._regionprops import regionprops, perimeter
  File "skimage/measure/_regionprops.py", line 651, in <module>
    _install_properties_docs()
  File "skimage/measure/_regionprops.py", line 638, in _install_properties_docs
    prop_doc = _parse_docs()
  File "skimage/measure/_regionprops.py", line 631, in _parse_docs
    __doc__, flags=re.DOTALL)
  File "/home/gregory.starck/.virtualenvs/venv/lib/python2.7/re.py", line 190, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or buffer
```

**Comment by stefanv** [comment] 2018-09-07 19:58
It would be great if you could check whether this bug persists on Python 3 with the latest master.  If so, you are welcome to submit a patch, as long as it does not adversely impact the current behavior.  Thanks!

**Comment by soupault** [comment] 2018-09-07 19:59
Still nothing 😕 :
```
[~]$ python2.7 --version
Python 2.7.15
[~]$ python2.7 -O -c "import skimage.measure; print skimage"
<module 'skimage' from '/usr/local/lib/python2.7/site-packages/skimage/__init__.pyo'>
[~]$ python2.7 -O -c "import skimage.measure; print skimage.__version__"
0.14.0
```

**Comment by hmaarrfk** [comment] 2018-09-07 20:09
@gst, few questions:


1. where did you install scikit-image from? git? pypi, conda?
2. Can you try your install in a fresh environment?
3. Finally it seems that you are running the code from within either the `site-packages` directory, or the git directory. Generally, this is a bad idea as python has trouble finding the right version of the library.

I have a feeling the issue is related to 3 and either an older version of 0.14 or a version of 0.14 that is too new.

**Comment by gst** [comment] 2018-09-07 20:10
and now like most of you I can't reproduce anymore as if optimize mode wasn't enabled anymore while I still use the **-O** option.. hhoooo well ; I've reinstalled in a venv meanwhile, I think I'm going to re-do all from scratch..
if I can't reproduce anymore reliably I'll close..

**Comment by hmaarrfk** [comment] 2018-09-07 20:12
if you are trying to compile it yourself, we've been having issues with the bulid.

I have a feeling it is related to cython (well because python typically updates well). Try `make clean` before you do install it from the git directory.

**Comment by hmaarrfk** [comment] 2018-09-10 01:45
@gst, I guess it took me some time to understand the bug. Seems like it is the same thing as:

https://stackoverflow.com/questions/52242859/file-e-python-lib-re-py-line-229-in-finditer-return-compilepattern-flags

Please submit your fix for this bug. I would be interested in reviewing it.

**Comment by hmaarrfk** [comment] 2018-09-10 04:08
Hmm, still not able to reproduce though :/ I should just not work past 10pm .....

**Comment by gst** [comment] 2018-09-10 12:32
@hmaarrfk this is exactly *that* error :)
**NB:**  my bad, this is with `python -OO` actually, this is what disable docstrings. -O only disables \_\_debug\_\_
I'll submit my PR probably during the day.
( what I don't get is that in a pip --user install with pypi wheel on a computer A I reproduce the error but not on a second computer B.. I'm looking to figure out what's going on )

**Closed** 2018-10-09 20:15 UTC
Labels: status: needs decision
