### ISSUE TITLE
Setting up conda environment for development of skimage throws a package not found error

### ISSUE THREAD

**Issue by pamitabh** [scikit-image/scikit-image#7478] opened 2024-07-26 20:26 UTC
### Description:

Following the conda environment setup instructions at: https://scikit-image.org/docs/stable/user_guide/install.html#id4 fails at the line ` conda install -c conda-forge --file requirements/default.txt` with a package not found error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - lazy-loader[version='>=0.4']

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults
```

The lazy loader package is available on conda-forge ([here](https://anaconda.org/conda-forge/lazy_loader)) but its installation is listed as `conda install lazy_loader` instead of `conda install lazy-loader`. 

### Way to reproduce:

Follow the conda environment setup instructions for skimage dev at https://scikit-image.org/docs/stable/user_guide/install.html#id4. 

### Version information:

```Shell
conda version: 24.5.0
```

**Comment by pamitabh** [comment] 2024-07-26 20:36
Update: editing the requirements/default.txt line from `lazy-loader>=0.4` to `lazy_loader>=0.4` fixed the failure for me. I know the first two lines of the file says!!
> # Generated via tools/generate_requirements.py and pre-commit hook.
> # Do not edit this file; modify pyproject.toml instead.

**Comment by lagru** [comment] 2024-08-01 13:25
Uff, thanks for the report! We are running into the fact that pip-style requirement files are not really intended to work with conda. That it has been working has, so far been luck. I don't really see a non-hackish way around this. 

Since these are the instructions for the contributor setup, I propose to drop conda / conda-forge here:

- We only really test with dependencies from PyPI in our CI.
- Our dev workflow heavily depends on spin. There are command line options in several commands that use pip and PyPI to handle dependencies.

**Comment by hmaarrfk** [comment] 2024-08-03 14:52
Sorry about this. The develeoent instructions are hard to test on all combinations of operating systems and conda

the issue is that the pip package changed spelling from an underscore to a dash

the fix is being worked on upstream right now
https://github.com/conda-forge/lazy_loader-feedstock/pull/11

as a temporary workaround, which you found, you can edit the default.txt to use the underscore for lazy-loader. 

I’m going to close this issue here while we resolve it at conda-forge (just have to give time for people to review). 

If the package with a dash is not released within two week ping on the linked pull request, I can move it forward at that stage.

**Comment by lagru** [comment] 2024-08-05 11:49
Let's reopen this while it's still in an unfixed state and to increase the chances we think on it in two weeks. :)

**Closed** 2024-08-16 02:29 UTC
Labels: :bug: Bug

**Comment by stefanv** [comment] 2024-08-16 02:55
Thanks for taking care of this, Mark!
