### ISSUE TITLE
Build issue with scikit_image-0.12.3-cp27-cp27mu-manylinux1_x86_64.whl

### ISSUE THREAD

**Issue by LeeKamentsky** [scikit-image/scikit-image#2003] opened 2016-03-15 19:28 UTC
Hi all,
We're having problems with our Travis build that seem to have started with the upload of scikit_image-0.12.3-cp27-cp27mu-manylinux1_x86_64.whl to PyPi. This is a pointer to a good build:
https://travis-ci.org/CellProfiler/CellProfiler/builds/115324719

and this to one that is failing:

https://travis-ci.org/CellProfiler/CellProfiler/builds/116202446

The stack trace is:

    __ ERROR collecting cellprofiler/modules/tests/test_exporttospreadsheet.py ____cellprofiler/modules/tests/test_exporttospreadsheet.py:25: in <module>
        from cellprofiler.modules import identifyprimaryobjects cellprofiler/modules/identifyprimaryobjects.py:187: in <module>
    from centrosome.watershed import watershed
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/centrosome/watershed.py:1: in <module>
        import skimage.morphology
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/morphology/__init__.py:1: in <module>
        from .binary import (binary_erosion, binary_dilation, binary_opening,
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/morphology/binary.py:6: in <module>
        from .misc import default_selem
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/morphology/misc.py:5: in <module>
        from .selem import _default_selem
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/morphology/selem.py:3: in <module>
        from .. import draw
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/draw/__init__.py:1: in <module>
        from .draw import circle, ellipse, polygon_perimeter, set_color
    ../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/skimage/draw/draw.py:4: in <module>
        from ._draw import _coords_inside_image
    E   ImportError: cannot import name _coords_inside_image

I'm going to try and rejigger things so that it builds scikit-image from the source wheel and report back if it fixes things. Travis is running on Ubuntu 12.04, many more details are in the Travis log. Let me know if I can help you further.

**Comment by JDWarner** [comment] 2016-03-15 19:35
On first glance this looks like at least one Cython file may not be built properly, specific to that wheel.

**Comment by LeeKamentsky** [comment] 2016-03-15 19:50
I think you're right that it's a Cython problem. I did install skimage from source on the Travis build and it appears to be working fine.

I am wondering how you can build binaries for scikit-image that are agnostic to the Numpy version. I know that at least my contributions use enough Cython Numpy magic that I'd be surprised if the binary worked for any Numpy.

**Comment by stefanv** [comment] 2016-03-15 23:12
We build against the earliest version of NumPy required, which should in
theory give you wheels that are compatible with any later numpy of the same
major version.

**Comment by soupault** [comment] 2016-05-15 18:54
@LeeKamentsky could we close the issue then?

**Closed** 2016-05-16 15:02 UTC

**Comment by stefanv** [comment] 2016-05-17 01:02
Just to double check: is the wheel on PyPi broken or not?

**Comment by LeeKamentsky** [comment] 2016-05-17 12:33
This is the build that failed:
https://travis-ci.org/CellProfiler/CellProfiler/builds/116202448

I installed from a tarball from github here and it worked:
https://travis-ci.org/CellProfiler/CellProfiler/builds/116210573#L392

We're still building scikit-image in our build from the source on github:
https://travis-ci.org/CellProfiler/CellProfiler/builds/130094735

I'm no longer working for CellProfiler, so I'm not too well equipped  to look at this further.

**Comment by stefanv** [comment] 2016-06-29 00:44
@cgohlke @ernaveenkoul Tried to install the scikit-image wheels from your site today and ran into this same problem.  Do you see this problem occurring on your systems?

**Comment by cgohlke** [comment] 2016-06-29 01:18
I can't reproduce this on Windows.
