### ISSUE TITLE
regionprops().area broken

### ISSUE THREAD

**Issue by scaramallion** [scikit-image/scikit-image#1465] opened 2015-04-07 07:39 UTC
I'm trying to use regionprops() in a manner similar to the [plot_label example](http://scikit-image.org/docs/dev/auto_examples/plot_label.html#example-plot-label-py) but am getting a ValueError exception when I try to get the area of each region: 

   ` File "_moments.pyx", line 8, in skimage.measure._moments.moments (skimage/measures/_moments.c:1415)
ValueError: Buffer dtype mismatch, expected 'double' but got 'unsigned char'. `

I suspect it has something to do with this commit: https://github.com/scikit-image/scikit-image/commit/fc0a6064d7651c8db2420500c82be42d24c62758

Using v0.11.3 installed via pip

**Comment by jni** [comment] 2015-04-07 08:09
@scaramallion can you send a minimal code snipped to reproduce the error? Preferably using one of the images in `skimage.data`.

Thanks!

**Comment by scaramallion** [comment] 2015-04-07 23:45
Using a simple array

    import numpy as np
    from skimage.measure import regionprops

    image = np.zeros((200, 200).astype(numpy.uint8)
    image[95:105, 95:105] = 255

    print regionprops(image)[0].area

Alternatively using `skimage.data`

    import numpy as np
    from skimage.measure import regionprops
    from skimage.data import coins
    from skimage.filters import threshold_otsu
    from skimage.morphology import closing, square

    image = coins()[50:-50, 50:-50]
    thresh = threshold_otsu(image)
    bw = closing(image > thresh, square(3))

    print regionprops(bw)[0].area

**Comment by JDWarner** [comment] 2015-04-08 00:12
I cannot reproduce. Win7 x64, latest Anaconda, current master branch. Running the second set of commands returns without errors

```
19278.0
```

**Comment by JDWarner** [comment] 2015-04-08 00:16
@scaramallion I'm closing this as I cannot reproduce the problem.

Please reinstall (`python setup.py install`) or rebuild (`python setup.py build_ext -i`) your version of the package. 

If that doesn't resolve the problem, pull down the newest branch and repeat those steps. If that doesn't resolve the problem, check `skimage.__version__` to ensure you don't have another broken version of the package being preferentially loaded on your PYTHONPATH.

If none of that fixes it, re-open the issue and provide detailed information about your system including operating system, Python installation (distribution and version as applicable), and how you obtained scikit-image.

**Closed by JDWarner** 2015-04-08 00:16 UTC

**Comment by jni** [comment] 2015-04-08 02:28
@scaramallion as @JDWarner, I cannot reproduce the error: both your code snippets work for me.

**Comment by scaramallion** [comment] 2015-04-08 03:10
Compiling the current master fixed the issue. Thanks!
