### ISSUE TITLE
Remove IO package in favor of imageio

### ISSUE THREAD

**Issue by blink1073** [scikit-image/scikit-image#1605] opened 2015-07-13 00:43 UTC
This is intended for `scikit-image` v1.0:
- Replace `PIL` dependency with `imageio`
- Import all of `imageio` API into `skimage.io` namespace.
- Move `ImageCollection` to `imageio`
- Keep image stack
- Remove `external.tifffile`
- Use `matplotlib` only for `show`.

I have added plugins to `imageio` for `tifffile`, `gdal`, `fits`, and `itk`.

`imageio` only depends on `libfreeimage`, which is included in Debian repos, and will be included within the wheel installs for OSX and Windows.  There is a cross-platform `conda` recipe for `libfreeimage`.

Benefits:
- No `PIL`!
- Plugins are selected based on file extension, but can be overridden.
- A sane API for multi-image read/write.
- We benefit from any additional plugins that are added.

**Comment by blink1073** [comment] 2015-07-13 00:43
cc @almarklein

**Comment by matthew-brett** [comment] 2015-07-13 11:00
I notice that imageio does not currently have an OSX wheel on pypi - @almarklein - would you like me to set up a repo to build this, on the same lines as:

* https://github.com/MacPython/numpy-wheels
* https://github.com/MacPython/scipy-wheels

etc?

**Comment by almarklein** [comment] 2015-07-13 11:02
Support for wheels is in progress. I think we've got the OSX wheels covered, right @blink1073 ?

**Comment by blink1073** [comment] 2015-07-13 12:41
@matthew-brett, I am new to OSX wheels, your expertise would be greatly appreciated.  I just naively created `imageio-1.3-cp27-none-macosx_10_5_x86_64.whl` based on the library that @almarklein had pre-compiled: https://github.com/imageio/imageio-binaries.


https://github.com/imageio/imageio/pull/108

**Comment by vighneshbirodkar** [comment] 2015-07-13 13:07
If I understand correctly,  we plan to remove the io module completely?

**Comment by blink1073** [comment] 2015-07-13 13:09
It would contain `stack`, `imshow` and `show`, and then the `imread` and friends from `imageio`'s API: https://imageio.readthedocs.org/en/latest/userapi.html

**Comment by matthew-brett** [comment] 2015-07-13 13:14
Ah - OK - I will create a MacPython repo for this.

The tricks are:

* to make the wheels compatible with Python.org and System Pythons, which requires a dual-arch build of the libraries and the Python extensions, and:
* embedding the dynamic library in the wheel, maybe with `delocate` or doing static linking, so the personal installing the wheel does not need to also copy the library.

**Comment by vighneshbirodkar** [comment] 2015-07-13 14:08
@blink1073 What do you mean by friends ? 
I am not clear, how would you read and write images ? `skimage.io.imread` or `skimage.imageio.imread` ?

**Comment by blink1073** [comment] 2015-07-13 14:11
Sorry, I was using a colloquialism.  I meant that we would present the `imageio` API as part of the `skimage.io` API.  So, you would use `skimage.io.imread`, etc.

**Comment by vighneshbirodkar** [comment] 2015-07-13 14:12
@blink1073, so we'll make `imageio` a necessary requirement and drop other plugins ?

**Comment by matthew-brett** [comment] 2015-07-13 14:15
How active is the Freeimage project?  I see that the Makefile for OSX is still building PPC and requiring gcc-4.0, and the project is using CVS for version control.

**Comment by blink1073** [comment] 2015-07-13 14:17
@vighneshbirodkar, yes, we would defer handling of plugins to `imageio`.

**Comment by blink1073** [comment] 2015-07-13 14:18
@matthew-brett, from their website: "March 15th, 2015 FreeImage 3.17.0 released"

**Comment by vighneshbirodkar** [comment] 2015-07-13 14:25
Nice. What about `imshow` ? Is it a good idea to have a light weight viewer ? A bare-minimum window with a close button.

**Comment by blink1073** [comment] 2015-07-13 14:31
We still depend on `matplotlib`, and we provide some nice defaults for `plt.imshow` [here](https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/matplotlib_plugin.py#L114).

**Comment by blink1073** [comment] 2015-07-13 14:31
That part will stay.

**Comment by matthew-brett** [comment] 2015-07-13 14:45
Hmm.   In response to what seemed to me a rather reasonable request to switch Freeimage development to git and maybe Github:

"Stop trying to turn this into a pissing match. The point is that neither SourceForge nor CVS are broken by any means. Everything you've said is more or less your opinion or something completely irrelevant. It simply doesn't matter how many users a service has or where other projects are hosted. If SourceForge and CVS are working for the FreeImage developers, there is no pressing reason to change."   http://sourceforge.net/p/freeimage/discussion/36111/thread/f2fae857/#a630

I don't think they have automated testing set up either.

There was an attempted fork to Github, with travis testing, but it only appears to have a single active developer : https://github.com/imazen/freeimage

**Comment by almarklein** [comment] 2015-07-13 14:52
That's a bit sad ...

**Comment by blink1073** [comment] 2015-07-13 14:53
And a bit scary

**Comment by almarklein** [comment] 2015-07-13 15:19
As long as the lead devs stay active enough to maintain it. They won't attract much other devs this way, but maybe they don't need to; most work now, I suppose, consists of fixing the odd bug.

**Comment by matthew-brett** [comment] 2015-07-13 15:24
It raises the question whether Freeimage will survive into the medium term though.

**Comment by JDWarner** [comment] 2015-07-13 15:34
Choice of VC system isn't necessarily the problem, SourceForge is. After the recent incidents where SourceForge added spyware/malware to binaries of "abandoned" projects, nothing from that service should be trusted. I wonder if we're doing users a disservice by supporting a project/plugin from a known dangerous source.

**Comment by sciunto** [comment] 2015-07-13 15:36
Regarding the future of freeimage. Some major libs seems to depend on freeimage on debian (https://packages.debian.org/source/unstable/freeimage) but debian has a heavy policy on dependencies.  Arch packages doesn't depend so much on freeimage (https://www.archlinux.org/packages/community/i686/freeimage/). So, it's seems to be weak dependencies.
Do we know alternative? What's used in opencv?

**Comment by matthew-brett** [comment] 2015-07-13 15:42
The problem is the one that Almar alluded to - it's going to be hard for Freeimage to attract and keep developers if it a) uses a VCS that's very bad for collaborative coding and b) does not show much interest in adapting to newer coding practices, such as pull-requests, and continuous integration.

As evidence, the OS build system is terribly out of date.  It appears to assume OSX 10.6, and it certainly does not work on 10.9.

**Comment by vighneshbirodkar** [comment] 2015-07-13 15:49
@sciunto 
A quick look tells me OpenCV is doing decoding on its own, at least for PNG. Am I missing something ?
https://github.com/Itseez/opencv/blob/b46719b0931b256ab68d5f833b8fadd83737ddd1/modules/imgcodecs/src/grfmt_png.cpp

**Comment by matthew-brett** [comment] 2015-07-13 15:53
I _think_ (from a quick cvs2git import) that there have only been two committing contributors in the last five years.  There have been 568 commits over that time though, which is not too bad.  The discussion forum looks moderately active.

**Comment by matthew-brett** [comment] 2015-07-13 16:59
Ah - ouch - imageio uses ctypes rather than linking directly, that makes it harder to ship the dynamic library with the wheel.

**Comment by jni** [comment] 2015-07-13 17:22
As I've mentioned before I suggest we keep tifffile for TIFF files, as it is rock-solid for multi-page tiffs and various dtypes. Doesn't imageio itself depend on a bunch of external libraries, including freeimage? Whatever we do, I want to make sure that our IO doesn't depend on system libraries that may or may not be present. We switched to Pillow to ensure that there is always an image decoder available.

**Comment by blink1073** [comment] 2015-07-13 17:34
@jni, `tifffile` is included in `imageio` in the latest master.  Also, see my main PR comments about distribution concerns.  We had several users at the tutorial who had problems with PIL, and frankly I would not be sad to see it go.

**Comment by jni** [comment] 2015-07-13 17:39
@blink1073 ah, sorry for missing those the first time around. But it sounds like we are not too happy about depending on freeimage... =\ Pillow also has conda support, not sure about wheels? Note that I'm completely agnostic as to which library we end up depending on; I'm just sceptical that depending on freeimage would have resulted in any fewer headaches at the tutorials...!

**Comment by blink1073** [comment] 2015-07-13 17:42
I spoke with an Anaconda maintainer, who is ready to add libfreeimage and imageio when needed.   We will match Pillow's wheel offerings.  My main concern is that PIL can seem like it installed correctly, while falling on its face if it was not compiled with JPEG support.

**Comment by matthew-brett** [comment] 2015-07-13 17:48
Is anyone having difficultly with Pillow do you know?   Which platform was this on?   If the problem is PIL, then surely we can expect this problem to go away in the near future?

I can see that imageio is a great solution for Debian, and OK for conda, but in general I think the idea is you install the libfreeimage library in the system directories (on the runtime load path), and this is uncomfortable for things like wheel installs.

**Comment by sciunto** [comment] 2015-07-13 17:48
@blink1073 Isn't it something we can bring to the attention of their maintainers?

**Comment by matthew-brett** [comment] 2015-07-13 17:49
Pillow has good wheel support.

**Comment by blink1073** [comment] 2015-07-13 18:33
I didn't get exact bug reports, since this was during the tutorial at the conference.  We can match the wheel support of Pillow, and the conda model has shown that you can use "system" libraries within your environment if needed, as a deference to practicality.

**Comment by matthew-brett** [comment] 2015-07-13 18:40
I don't know how to match the wheel support of Pillow.  I guess it's possible, but it will be a hack, because wheels aren't designed to put stuff on the system path.

I am sure it can be done with conda, but as I say fairly often, it doesn't seem like a good idea to put ourselves into the situation where scikit-image can't easily be installed without conda.

**Comment by blink1073** [comment] 2015-07-13 18:58
Imageio will either use the system lib, or one installed locally within it's package.  It will also download the appropriate library from imageio/imageio-binaries and put it within it's package space if need be. 

https://github.com/blink1073/imageio/blob/master/imageio/core/findlib.py#L97

**Comment by matthew-brett** [comment] 2015-07-13 19:02
You mean the wheel appears to be a pure Python wheel, but in fact ships with OSX Linux and windows binary libraries in the Python import directory?

I was reading quickly - but does the code really try and download a binary library at import time, and write into the package space (which might not be writeable)?  So import will fail when your wireless is down?

**Comment by blink1073** [comment] 2015-07-13 19:09
Yes to your first question.  For the second, that would only happen if you `pip install`ed from a Linux 32 machine *and* did not have an internet connection, in which case you could have installed from the linux32 tar file.

**Comment by matthew-brett** [comment] 2015-07-13 19:29
Ouch.   I guess that means you can't build a platform-specific wheel, because you have to build the freeimage library for every platform and copy all the dynamic libraries into the Python wheel in order to ship?

I think you are going to run into problems here, because you are subverting the usual wheel build and install mechanisms, but I don't know pip well enough to tell you exactly when that will happen, and therefore how likely it is.

**Comment by blink1073** [comment] 2015-07-13 19:31
Here's how I view it:  we *are* shipping a pure python package, with an optional compiled library.  The name of the wheel is used by `pip` to choose the right one to download.  The binary is included in the MANIFEST, and gets installed to site-packages along with everything else.

**Comment by matthew-brett** [comment] 2015-07-13 19:53
I guess this means that it is hard to test the wheel that you are going to ship, because you can't build it until you have built a dynamic freeimage library for every platform.

**Comment by blink1073** [comment] 2015-07-13 19:54
Yes, @almarklein has been building them and putting them in imageio/imageio-binaries.

**Comment by matthew-brett** [comment] 2015-07-13 19:59
Will imageio a hard dependency?

**Comment by blink1073** [comment] 2015-07-13 20:05
Would everyone be satisfied if I add a `pil` plugin to imageio as a fallback?

**Comment by blink1073** [comment] 2015-07-13 20:06
And then we could have a hard dependency on `imageio`, which in turn could use `libfreeimage` or `pil`.

**Comment by sciunto** [comment] 2015-07-13 20:09
To me, all this thread does not invalidate the main purpose which is that skimage must focus on image processing, not io and imageio is a great candidate for that. It's more on how to strengthen imageio.

**Comment by almarklein** [comment] 2015-07-13 20:34
@sciunto I agree :)

This thread spun of two topics: 

a) Whether we can rely on freeimage. I'd say yes. Their "community" could be better, and they use sourceForge. But the library is quite stable, and we don't download binaries from sourceForge; only code. Also, there is no alternative of an open source library that can read so many formats.

b) If and how we can build wheels for imageio. @matthew-brett I don't understand how the fact that the lib is dynamically linked via ctypes can make distribution *harder*. That's silly. We can put that lib anywhere we want, as long as imageio knows where to find it. Let's discuss further here: https://github.com/imageio/imageio/pull/108

**Comment by matthew-brett** [comment] 2015-07-13 23:46
Bear in mind I am a very minor scikit-image contributor.

Almar - I gave a shot at explaining why I thought the using pure-Python wheels with multiple shipped libraries was likely to be fragile, but honestly, we are early in the wheel era, it's difficult for me to guess  what problems you'll hit.

Honestly, if it were me, I think I would set up continuous integration testing of the imageio wheels on Windows, OSX and Linux 64 / 32, and then - as scikit-image - wait until imageio had working pypi installable wheels on the various platforms for enough time to get a feel for how reliable they are in use.  But it is really not my call.

**Comment by blink1073** [comment] 2015-07-14 02:13
@matthew-brett, sorry if I came off as adversarial earlier.  I do appreciate your help and insight.  These packaging issues leave me a bit exasperated...

**Comment by matthew-brett** [comment] 2015-07-14 10:19
I do understand - I'm guessing from your introduction at the top that imageio would make some things easier and more pleasant to work with, so me doing a Mr Grumpy on freeimage and wing-it wheels must be disheartening, I'm sorry for that.  I hope I'm not restricting your options, I consider myself well outside the group of people who have to agree on big decisions like this...

**Comment by blink1073** [comment] 2015-07-14 11:52
@matthew-brett, on the contrary, if you have concerns, by all means voice them.  We surely don't want to  find ourselves stuck in an intractable situation.

Just to confuse things further, PyPI does not accept uploaded wheels for Linux, as they are considered broken for now.  They will most likely require more metadata to handle all definitions of "Linux".

https://bitbucket.org/pypa/pypi/issues/120/binary-wheels-for-linux-are-not-supported

**Comment by matthew-brett** [comment] 2015-07-14 12:55
Yes, as you know, the usual situation for wheels is that you build (and test) windows and OSX binary wheels, that are platform-specific, shipping the dynamic libraries in the wheel, and assume that Linux users a) have a compiler that works and / or b) will not be much flustered about being asked to do `apt-get` if necessary and / or c) won't mind being pointed to a wheel repository specific for their distribution.

**Comment by blink1073** [comment] 2015-07-14 13:01
I couldn't quite figure out how to make the wheel assert itself as platform specific, without adding an `Extension` to `setup.py`.

**Comment by matthew-brett** [comment] 2015-07-14 13:06
I _think_ (but am not sure) that it would be better to label these as platform-specific, and ship the wheels with hard-coded relative paths to the platform-specific dynamic lib, rather than searching across the file-system.

I just succeeded in building a OSX 10.6-compatible dual arch Freeimage library FWIW : https://travis-ci.org/MacPython/imageio-wheels/jobs/70881688

I don't know how to label wheels as platform-specific more nicely than adding a spurious `Extension`, but I could have a go at working that out.

**Comment by blink1073** [comment] 2015-07-14 13:12
@matthew-brett, can we take this conversation to https://github.com/imageio/imageio/pull/108?

**Comment by matthew-brett** [comment] 2015-07-14 13:34
We can, I will.

The question to scikit-image is - is this a sustainable way to go?   I'm not sure myself.  I still think it would be safer to wait say 3-6 months after imageio wheels have shipped and are working well before going this direction.

**Comment by stefanv** [comment] 2015-07-15 23:44
I would err on the side of Matthew's caution.

**Comment by almarklein** [comment] 2015-07-16 13:19
That's fair enough; we'll get wheels and conda packages up and then we revive this issue a few months down the line.

**Comment by blink1073** [comment] 2015-07-19 19:53
Another data point: pyzmq ships with a copy of libzmq, and IPython has been relying on it for some time now.

https://pypi.python.org/pypi/pyzmq

**Comment by matthew-brett** [comment] 2015-07-19 21:21
Sure, but in the same sense that numpy or scipy or matplotlib ship with various dynamic libraries - these all have standard C extensions linking to the libraries, when are then shipped in the platform-specific wheel.  The new variant is the pure Python wheel shipping with dynamic libraries for multiple platforms (or downloading the library on import).

**Comment by tacaswell** [comment] 2015-07-31 17:23
attn @danielballan

**Comment by jni** [comment] 2020-10-27 03:08
Closing in favour of #5306

**Closed by jni** 2020-10-27 03:08 UTC
Labels: type: enhancement, type: maintenance
