### ISSUE TITLE
Probably the wrong way to access slices of multipage TIFF used

### ISSUE THREAD

**Issue by MartSlaaf** [scikit-image/scikit-image#4495] opened 2020-03-05 16:07 UTC
## Description
For my project, I do need to access the random slices of large multipage tiff files (~5k pages). Holding such volumes in RAM is infeasible, so I need fast random reading. Initially, I was using the `skimage.io.MultiImage` for it, but I discovered that the speed of reading the random slice is way slower than possible. I will provide the function I used for comparison and the sketch of how to improve it quickly. It seems like just not optimal reading function from the tifffile.py being used.

## Way to reproduce
Function, which I use to compare my runs, which just reads the whole volume in random order.
```python
def function_to_get_results(file_collection):
    all_files = []
    for file_id in np.random.permutation(np.arange(len(file_collection))):
        all_files.append(file_collection[int(file_id)])
    all_files = np.concatenate(all_files)
    return all_files.mean()
```
The speed check results for th `MultiImage`:
```python
from skimage.io import MultiImage
c = MultiImage('/mnt/data/machine-learning/medakas/slice_8bit0.tiff')
%timeit function_to_get_results(c)
33min 41s ± 27 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

The sketch of the class which shows nearly the same speed. (I haven't run the full 7 runs check due to time consumption, but from the first run it's the same)
```python
from skimage.external import tifffile

class PeasantTiffFileWrapper:
    def __init__(self, file_addr):
        self.file_addr = file_addr
        self.len = len(tifffile.imread(file_addr)) # that's bad but outside of timing
        
    def __len__(self):
        return self.len
    
    def __getitem__(self, id):
        return tifffile.imread(self.file_addr, key=id)
```

And finally the sketch of the class which reads the slices nearly as fast as the separate files on disk:
```python
from skimage.external import tifffile

class KingTiffFileWrapper:
    def __init__(self, file_addr):
        self.file_descriptor = tifffile.TiffFile(file_addr)
        
    def __len__(self):
        return len(self.file_descriptor.pages)
    
    def __getitem__(self, id):
        return self.file_descriptor.asarray(id)
```

And it's test:
```python
d = KingTiffFileWrapper('/mnt/data/machine-learning/medakas/slice_8bit0.tiff')
%timeit function_to_get_results(d)
27.2 s ± 6.79 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This one takes way less time.

P.S. It takes some additional time for the test function to calculate the average, which affecting the last result more than first. But this will increase the difference, not decrease.

P.P.S. It's not so easy to implement this reading in the currently present paradigm, as far as I understand, but for me, it would be really nice and I can provide the possible help.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Linux-4.15.0-46-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.16.2
numpy version: 1.16.4
```

**Comment by cgohlke** [comment] 2020-03-05 20:00
Maybe I am missing something, but I don't see a real problem here. 

Of course opening the TIFF file every time you read a single page (`tifffile.imread(filename, key=id)`) will be much slower than opening the TIFF file once (`with tifffile.TiffFile(filename) as tif`) and then reading single pages from the open file handle (`tif.pages[id].asarray())`).

Using the [tifffile](https://pypi.org/project/tifffile/) package directly instead of the outdated `skimage.external.tifffile` should give another speed boost. 

Depending on your type of TIFF files and the access pattern, enabling the page cache (`tif.pages.cache = True`) or use of frames (`tif.pages.useframes = True`)  will make a difference.

**Comment by jni** [comment] 2020-03-06 05:40
@cgohlke well, it is definitely a problem for our users that our skimage-provided "canonical" way of opening a tifffile is totally suboptimal. But I agree that the correct workaround is to use tifffile directly.

@MartSlaaf thank you for reporting! I think @cgohlke's proposal is your best bet for now. The current discussion around skimage is to spin off the io package and/or merge it with imageio. At that point, issues like this one will be useful to guide future development of such a package. But this is a very long term proposal. In the medium term, you are not going to beat following @cgohlke's advice. =) *And*, in the long term, from a performance perspective, the best you can hope is to match it, since we will always be using tifffile under the hood!

**Comment by cgohlke** [comment] 2020-03-06 06:14
I see now. The issue is that `skimage.io.MultiImage` is implemented using high level `imread` functions:

https://github.com/scikit-image/scikit-image/blob/d212cb5100abbb0c5c50cc340b766cae8e368d55/skimage/io/collection.py#L432-L440

**Comment by jni** [comment] 2020-03-06 06:17
Yes, that is what I suspected given your response above. Since some plugins don't provide a persistent access pattern, and we use MultiImage as a pattern for any plugin, we are somewhat hamstrung.

**Comment by MartSlaaf** [comment] 2020-03-06 09:03
@cgohlke, @jni  thank you both for answers!

Yes, for now, I use somewhat like @cgohlke proposed. 
Just, it would be nice, if it will work out of the box in future. =)

P.S. should I close the issue in this case, or let it be here?

**Comment by sciunto** [comment] 2020-03-07 19:36
I propose to close as it will be fixed in the future when io will be reshaped. Thank you.

**Closed by sciunto** 2020-03-07 19:36 UTC
