### ISSUE TITLE
Invalid no-name-in-module from pylint on scikit-image>=0.19.0 using filters module

### ISSUE THREAD

**Issue by defe007** [scikit-image/scikit-image#7398] opened 2024-04-16 21:41 UTC
### Description:

I'm seeing an invalid `no-name-in-module` error in `pylint` when using `scikit-image>=0.19.0` (I believe related to the introduction of lazy loading). This was tested on a conda environment created using:
```bash
conda create -n skimage_env -c conda-forge python=3.8 scikit-image==0.19.3 pylint==3.1.0 -y
```

### Way to reproduce:

Create a file named `test.py` that contains:
```python
from skimage.filters import threshold_otsu
from skimage.filters import threshold_mean
from skimage.transform import warp
```

Assuming you have activated the conda environment, run `pylint` on the file:
```bash
pylint test.py
```

Generates the following error:
```
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: E0611: No name 'threshold_otsu' in module 'skimage.filters' (no-name-in-module)
test.py:2:0: E0611: No name 'threshold_mean' in module 'skimage.filters' (no-name-in-module)
test.py:1:0: W0611: Unused threshold_otsu imported from skimage.filters (unused-import)
test.py:2:0: W0611: Unused threshold_mean imported from skimage.filters (unused-import)
test.py:3:0: W0611: Unused warp imported from skimage.transform (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Version information:

```Shell
3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)
[GCC 12.3.0]
Linux-3.10.0-1160.114.2.el7.x86_64-x86_64-with-glibc2.10
scikit-image version: 0.19.3
numpy version: 1.24.4
pylint version: 3.1.0
astroid version: 3.1.0
```

**Comment by lagru** [comment] 2024-04-17 10:38
Thanks for the report @defe007. I can reproduce this, however, I'm not sure that this is an error on scikit-image's side. I can reproduce this without scikit-image being involved with the following minimal example:

```python
# lib/__init__.py

import lazy_loader as lazy
__getattr__, __dir__, __all__ = lazy.attach_stub(__name__, __file__)
```

```python
# lib/__init__.pyi
__all__ == ["bar"]
from ._foo import bar
```

```python
# lib/_foo.py
def bar():
    print("I'm happy")
```

```python
from lib import bar
bar()
```

Create a virtual environment with `lazy_loader` and `pylint` and inside the directory containing `lib` run 
```shell
python test.py  # works and prints "I'm happy"
pylint test.py  # fails with 
# test.py:1:0: E0611: No name 'bar' in module 'lib' (no-name-in-module)
```

As this is working fine, I'm guessing that pylint isn't recognizing the PYI file or giving it's content priority over `__init__.py`. So I'd probably inquire with Pylint first and lazy_loader second if this is a bug on their side.

Therefore, I'm closing this for now. But feel very welcome to add something here if you don't agree or have something to add. :)

**Closed by lagru** 2024-04-17 10:38 UTC
Labels: :bug: Bug

**Comment by defe007** [comment] 2024-04-17 13:36
Thank you @lagru for your insight. I've opened an [issue with pylint](https://github.com/pylint-dev/pylint/issues/9553). I hope you don't mind me using your example.

**Comment by lagru** [comment] 2024-04-17 13:55
No of course not. ;) Also tagging @jarrodmillman because of lazy_loader.
