### ISSUE TITLE
uninterpretable outcomes of skimage.measure.regionprops for flat connected regions in 3D image

### ISSUE THREAD

**Issue by IliaSafonov** [scikit-image/scikit-image#2635] opened 2017-04-26 13:33 UTC
skimage.measure.regionprops returns 2D properties for flat connected regions in 3D image. The outcomes (in particular, bbox) are uninterpretable.
I found out the issue when I worked on code for calculation of properties of holes inside connected regions of 3D image. 

Demonstration:
import numpy as np
from skimage import measure
from scipy import ndimage

example 1:
im = np.array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],
       [[ 0,  1,  1],
        [ 0,  1,  0],
        [ 0,  0,  0]],
       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])
labels, num_obj = ndimage.label(im)
props = measure.regionprops(labels)
print("bbox ", props[0].bbox)
print(np.uint8(props[0].image))
print("shape ", props[0].image.shape)

>> bbox  (1, 0, 1, 2, 2, 3)
>> [[[1 1]
   [1 0]]]
>> shape  (1, 2, 2)

Output is 3D image with flat region.

labels2, num_obj2 = ndimage.label(np.uint8(props[0].image),structure=ndimage.generate_binary_structure(3, 3))
props2 = measure.regionprops(labels2)
print("bbox ", props2[0].bbox)
print(np.uint8(props2[0].image))
print("shape ", props2[0].image.shape

>> bbox  (0, 0, 2, 2)
>> [[1 1]
   [1 0]]
>> shape  (2, 2) 

Output is 2D image. Why? I process 3D image, I expect to obtain 3D images as output.
Let's rotate initial image im.

example 2:
im = np.array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],
       [[ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  0,  0]],
       [[ 0,  1,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])
labels, num_obj = ndimage.label(im)
props = measure.regionprops(labels)
print("bbox ", props[0].bbox)
print(np.uint8(props[0].image))
print("shape ", props[0].image.shape)

>> bbox  (1, 0, 1, 3, 2, 2)
>> [[[1]
   [1]]
  [[1]
   [0]]]
>> shape  (2, 2, 1)

labels2, num_obj2 = ndimage.label(np.uint8(props[0].image),structure=ndimage.generate_binary_structure(3, 3))
props2 = measure.regionprops(labels2)
print("bbox ", props2[0].bbox)
print(np.uint8(props2[0].image))
print("shape ", props2[0].image.shape

>> bbox  (0, 0, 2, 2)
>> [[1 1]
   [1 0]]
>> shape  (2, 2) 

So, we obtain the same outcome as in example 1, but for different initial image. We cannot distinguish these cases (example 1 and 2). We cannot locate such flat regions in image (at least, by means of bbox) properly. 
In my opinion, it is a bug.

Workaround:
tmp_image = np.zeros((props[0].image.shape[0] + 1, props[0].image.shape[1] + 1, 
                props[0].image.shape[2] + 1), dtype=np.uint8)
tmp_image[:-1, :-1, :-1] = np.uint8(props[0].image)
labels2, num_obj2 = ndimage.label(tmp_image, structure=ndimage.generate_binary_structure(3, 3))
props2 = measure.regionprops(labels2)
print("bbox ", props2[0].bbox)
print(np.uint8(props2[0].image))
print("shape ", props2[0].image.shape)
>> bbox  (0, 0, 0, 2, 2, 1)
>> [[[1]
    [1]]
   [[1]
    [0]]]
>> shape  (2, 2, 1)
 
I didn't test it for 2D images, but I expect analogous issue for lines in 2D image as well.

It was checked for skimage versions 0.12.3 and 0.13.0 for python 3.5 on Windows.

**Comment by jni** [comment] 2017-04-26 14:06
@IliaSafonov I agree with you that it's a bug. The output images should have the same dimensionality as the input. Thanks for reporting!

**Comment by emmanuelle** [comment] 2018-10-20 20:47
I could not reproduce the problem. Has the issue been corrected recently?

**Comment by jni** [comment] 2018-10-21 00:14
@emmanuelle turns out it has, in #3284, which was fixing a duplicate of this issue, #3278! And **oops**, we forgot to backport it! :man_facepalming:

**Comment by jni** [comment] 2018-10-21 00:15
I'm going to close this and start a backport there. Thanks for spotting this, @emmanuelle!

**Closed by jni** 2018-10-21 00:15 UTC
Labels: type: bug
