### ISSUE TITLE
Multiple failures in 32-bit Linux builds

### ISSUE THREAD

**Issue by matthew-brett** [scikit-image/scikit-image#3091] opened 2018-05-22 15:37 UTC
I'm very sorry not to be more detailed, but this is just to flag up that all scikit-image-wheels matrix entries have multiple test failures.  Here's a build that I think is correctly updated:

https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382142313

**Comment by soupault** [comment] 2018-05-22 15:51
@matthew-brett there are some failing I've never seen before, but the used codebase is, most likely, not the latest - `random_walker` tests should be passing since https://github.com/scikit-image/scikit-image/pull/3063. Could you try to clear the build cache on Travis and restart?

**Comment by hmaarrfk** [comment] 2018-05-22 17:32
i think the issue is that those wheels are using the tag [0.13.1](https://github.com/scikit-image/scikit-image-wheels/blob/be1556fcff1581f23c16a91a82f754ddf478f3cc/.travis.yml#L4), and daily seems to be on [0.13.0](https://github.com/scikit-image/scikit-image-wheels/blob/4aaf20bfb8db67eab519339a77718de0b58f88c0/.travis.yml#L5) which was broken a few days ago. 
We need a version bump and tag to allow 

See PR #3087
and #3085

**Comment by matthew-brett** [comment] 2018-05-22 17:49
Yes, sorry, my mistake.  Current build matrix is for scikit-image master:

https://travis-ci.org/scikit-image/scikit-image-wheels/builds/382260738

New errors, on Python 2 and 3, 32-bit : 

* watershed errors on 32-bit : #3089
* test_spacing_1 : #3092
* test_descriptor_orb : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260741#L3102, https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260742#L2305
* TestRank.test_all : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260744#L2392, https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260742#L2425
* test_ellipse_model_estimate_failers : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260744#L2589, https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/382260742#L2596

**Comment by hmaarrfk** [comment] 2018-05-22 17:54
of course 32 bit has not been tested......

**Comment by matthew-brett** [comment] 2018-05-22 17:57
I think 32-bit is fairly rare on Linux, but it's at 35% or so on Windows : https://github.com/statsmodels/statsmodels/issues/4657#issuecomment-390726164

**Comment by matthew-brett** [comment] 2018-05-22 17:58
In case it's useful : https://github.com/scikit-image/scikit-image/wiki/Testing-in-32-bit-environment

**Comment by hmaarrfk** [comment] 2018-05-22 18:42
@matthew-brett could you help setup travis for 3.6 and 2.7 on linux 32 bit?

**Comment by hmaarrfk** [comment] 2018-05-22 18:50
@matthew-brett Thanks for the instructions.

I keep getting 
```
# cd /io
root@5400d9a10d55:/io# ls
ls: cannot open directory .: Permission denied
```

**Comment by soupault** [comment] 2018-05-22 19:02
@matthew-brett the last 3 points in your bullet list are our well-known clients :). I've updated your message above with the link to the corresponding issues.

**Comment by matthew-brett** [comment] 2018-05-24 19:05
@hmaarrfk - did you manage to get the 32-bit docker image working?

**Comment by hmaarrfk** [comment] 2018-05-24 19:09
@matthew-brett Unfortunately, I did not. I can try again.

**Comment by hmaarrfk** [comment] 2018-05-24 19:38
@matthew-brett , I think docker changed some security features. I had to create my own Dockerfile with

```
FROM matthewbrett/trusty:32
ENV PYTHON_VERSION="2.7"
COPY . /io
WORKDIR /io
```
build it, and run it, then follow your instructions (minus adding `$PWD`)

**Comment by hmaarrfk** [comment] 2018-05-24 20:48
The issue was with `selinux`. I updated the wiki.

I'm down to 4 failures.
1. test_descriptor_orb
2. TestRank.test_all
3. test_ellipse_model_estimate_failers
4. test_spacing_1

### test_descriptor_orb
I have no clue

### TestRank.test_all
At first I thought it was a floating point error, but it seems like these error are real. 

### test_spacing_1
This seems to be an overflow warning for 32 bit, maybe the integers are smaller?/
I've isolated the troublesome call to
```
/venv/local/lib/python2.7/site-packages/scipy/sparse/compressed.py:486: RuntimeWarning: overflow encountered in long_scalars
  maxval=M*N)
```
which relates to sparse matrix multiply most likely on [this call](https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/random_walker_segmentation.py#L162)

### test_ellipse_model_estimate_failers
should be fixed soon.

**Comment by hmaarrfk** [comment] 2018-07-02 17:02
@matthew-brett could you help me figure out what is wrong with my 32linux travis job.

I'm trying to use your multibuild library, but I keep getting stuck on the line 

https://github.com/hmaarrfk/scikit-image/blob/linux_32bit_circle_ci/.travis.yml#L43

[travis](https://travis-ci.org/hmaarrfk/scikit-image/jobs/399187604#L603) gives me the error:
```
linux32: /io//home/travis/multibuild/docker_build_wrap.sh: No such file or directory
```

I'm sandboxing the build on my branch:
https://github.com/hmaarrfk/scikit-image/blob/linux_32bit_circle_ci/.travis.yml

**Comment by matthew-brett** [comment] 2018-07-02 17:14
You need a `multibuild` submodule somewhere...

**Comment by hmaarrfk** [comment] 2018-07-02 17:22
Ah, I thought I could just clone it in the home directory and source the scripts from there. Thanks!

**Comment by hmaarrfk** [comment] 2018-07-02 17:36
@matthew-brett do you recommend just testing everything through your multibuild system? otherwise we will have to have 2 parallel logic chains, one for your containerized builds using docker, the other using pure travis. 

Of course, this doesn't matter if we just drop linux 32 bit support, though, I think the failures are indicative of an underlying bug in the code that we should address. For that reason, I do like testing with different architectures.

**Comment by matthew-brett** [comment] 2018-07-03 07:53
I don't do that with my projects - I have the main CI, that runs on every commit, and a separate `myproject-wheels` repository, using multibuild, that builds and tests wheels, running on a nightly cron job.   That way I know quickly if there is a problem with things like mac or 32-bit linux, without complicating the main CI setup.

**Comment by matthew-brett** [comment] 2018-07-03 08:01
Hence the `scikit-image-wheels` project ...

**Comment by hmaarrfk** [comment] 2018-07-03 08:03
got it.  Yeah, there still seems to be 2 bugs. I guess we will get to them eventually.

Also, it seems that `scipy` is needed to build the wheels. I don't know exactly. It has to do with the  `import *` in the top level `__init__.py`

**Comment by hmaarrfk** [comment] 2021-03-30 01:12
Seems like there are failures in 32 bit wheels with `features`
```
 Building wheels for collected packages: numpy
    Building wheel for numpy (PEP 517): started
    Building wheel for numpy (PEP 517): still running...
    Building wheel for numpy (PEP 517): still running...
    Building wheel for numpy (PEP 517): finished with status 'done'
    Created wheel for numpy: filename=numpy-1.20.2-cp39-cp39-linux_i686.whl size=15510674 sha256=4204d66d8e763719deedba8732c8d3bfbc0c23fd56dc81332f6c6a62b8be931e
    Stored in directory: /root/.cache/pip/wheels/7e/67/62/5839e355a815afc565cf6bf3d69ff34ffe886ba1d1889d0ebd
  Successfully built numpy
  Installing collected packages: six, python-dateutil, pyparsing, pillow, numpy, kiwisolver, decorator, cycler, tifffile, scipy, PyWavelets, networkx, matplotlib, imageio, scikit-image
  Successfully installed PyWavelets-1.1.1 cycler-0.10.0 decorator-4.4.2 imageio-2.9.0 kiwisolver-1.3.1 matplotlib-3.4.0 networkx-2.5 numpy-1.20.2 pillow-8.1.2 pyparsing-2.4.7 python-dateutil-2.8.1 scikit-image-0.18.2.dev0 scipy-1.6.2 six-1.15.0 tifffile-2021.3.17
      + pip install pytest pooch pytest-localserver pytest-faulthandler
  Collecting pytest
    Downloading pytest-6.2.2-py3-none-any.whl (280 kB)
  Collecting pooch
    Downloading pooch-1.3.0-py3-none-any.whl (51 kB)
  Collecting pytest-localserver
    Downloading pytest-localserver-0.5.0.tar.gz (20 kB)
  Collecting pytest-faulthandler
    Downloading pytest_faulthandler-2.0.1-py2.py3-none-any.whl (2.7 kB)
  Collecting packaging
    Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
  Collecting requests
    Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
  Collecting appdirs
    Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
  Collecting attrs>=19.2.0
    Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
  Collecting py>=1.8.2
    Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
  Collecting iniconfig
    Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
  Collecting pluggy<1.0.0a1,>=0.12
    Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
  Collecting toml
    Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Collecting werkzeug>=0.10
    Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
  Requirement already satisfied: pyparsing>=2.0.2 in /tmp/tmp.AXDBYFn753/venv/lib/python3.9/site-packages (from packaging->pooch) (2.4.7)
  Collecting urllib3<1.27,>=1.21.1
    Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
  Collecting idna<3,>=2.5
    Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
  Collecting chardet<5,>=3.0.2
    Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
  Collecting certifi>=2017.4.17
    Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
  Building wheels for collected packages: pytest-localserver
    Building wheel for pytest-localserver (setup.py): started
    Building wheel for pytest-localserver (setup.py): finished with status 'done'
    Created wheel for pytest-localserver: filename=pytest_localserver-0.5.0-py3-none-any.whl size=17486 sha256=be752f9f323752a21f5f8b6d66126f09bc2ffa0b006e69a14151cf160bc9ae30
    Stored in directory: /root/.cache/pip/wheels/f6/56/84/47c0d420838983510f988996d35a4a7a06b1f39c456de5b846
  Successfully built pytest-localserver
  Installing collected packages: urllib3, toml, py, pluggy, packaging, iniconfig, idna, chardet, certifi, attrs, werkzeug, requests, pytest, appdirs, pytest-localserver, pytest-faulthandler, pooch
  Successfully installed appdirs-1.4.4 attrs-20.3.0 certifi-2020.12.5 chardet-4.0.0 idna-2.10 iniconfig-1.1.1 packaging-20.9 pluggy-0.13.1 pooch-1.3.0 py-1.10.0 pytest-6.2.2 pytest-faulthandler-2.0.1 pytest-localserver-0.5.0 requests-2.25.1 toml-0.10.2 urllib3-1.26.4 werkzeug-1.0.1
      + sh -c 'pytest --pyargs skimage'
  Fatal Python error: Aborted/bin/bash: line 114:  1987 Aborted                 (core dumped) env HOSTNAME=d8b98e4a0fab SSL_CERT_FILE=/opt/_internal/certs.pem LC_ALL=en_US.UTF-8 LD_LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib:/usr/local/lib64:/usr/local/lib PATH=/tmp/tmp.AXDBYFn753/venv/bin:/opt/python/cp39-cp39/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin *** LANG=en_US.UTF-8 CIBUILDWHEEL=1 SHLVL=1 HOME=/root LANGUAGE=en_US.UTF-8 AUDITWHEEL_PLAT=manylinux1_i686 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig _=/usr/bin/env sh -c 'pytest --pyargs skimage'
  ============================= test session starts ==============================
  platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
  Error: Command ['sh', '-c', 'pytest --pyargs skimage'] failed with code 134. 
  
  rootdir: /root
  plugins: localserver-0.5.0
  collected 6258 items / 4 skipped / 6254 selected
  
  _shared/tests/test_coord.py ..........................................   [  0%]
  _shared/tests/test_fast_exp.py .                                         [  0%]
  _shared/tests/test_geometry.py ...                                       [  0%]
  _shared/tests/test_interpolation.py .                                    [  0%]
  _shared/tests/test_safe_as_int.py ..                                     [  0%]
  _shared/tests/test_testing.py .....                                      [  0%]
  _shared/tests/test_utils.py ............................................ [  1%]
  .......................                                                  [  1%]
  _shared/tests/test_version_requirements.py ....                          [  1%]
  _shared/tests/test_warnings.py .........                                 [  2%]
  color/tests/test_adapt_rgb.py .......                                    [  2%]
  color/tests/test_colorconv.py .......................................... [  2%]
  ........................................................................ [  4%]
  ........................................................................ [  5%]
  ........................................                                 [  5%]
  color/tests/test_colorlabel.py ..................                        [  6%]
  color/tests/test_delta_e.py ........                                     [  6%]
  data/tests/test_data.py ...........................                      [  6%]
  draw/tests/test_draw.py ................................................ [  7%]
  ...                                                                      [  7%]
  draw/tests/test_draw3d.py ........                                       [  7%]
  draw/tests/test_draw_nd.py ...                                           [  7%]
  draw/tests/test_polygon2mask.py .                                        [  7%]
  draw/tests/test_random_shapes.py ..............                          [  7%]
  exposure/tests/test_exposure.py ........................................ [  8%]
  ...........................s                                             [  9%]
  exposure/tests/test_histogram_matching.py ......                         [  9%]
  feature/tests/test_basic_features.py ....::endgroup::Testing wheel...
                                                              ✕ 290.26s
  Error: Process completed with exit code 1.
```

**Comment by hmaarrfk** [comment] 2021-03-30 02:18
It seems to fail specifically with
```
=================================== FAILURES ===================================
  ____________________ test_multiscale_basic_features_channel ____________________
  
      def test_multiscale_basic_features_channel():
          img = np.zeros((10, 10, 5))
          img[:10] = 1
          img += 0.05 * np.random.randn(*img.shape)
          n_sigmas = 2
          features = multiscale_basic_features(img, sigma_min=1, sigma_max=2, multichannel=True)
          assert features.shape[-1] == 5 * n_sigmas * 4
          assert features.shape[:-1] == img.shape[:-1]
          # Consider last axis as spatial dimension
  >       features = multiscale_basic_features(img, sigma_min=1, sigma_max=2)
  
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/tests/test_basic_features.py:28: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:171: in multiscale_basic_features
      features = list(itertools.chain.from_iterable(all_results))
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:159: in <genexpr>
      _mutiscale_basic_features_singlechannel(
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:87: in _mutiscale_basic_features_singlechannel
      out_sigmas = list(
  /opt/python/cp39-cp39/lib/python3.9/concurrent/futures/_base.py:600: in result_iterator
      yield fs.pop().result()
  /opt/python/cp39-cp39/lib/python3.9/concurrent/futures/_base.py:433: in result
      return self.__get_result()
  /opt/python/cp39-cp39/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
      raise self._exception
  /opt/python/cp39-cp39/lib/python3.9/concurrent/futures/thread.py:52: in run
      result = self.fn(*self.args, **self.kwargs)
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:89: in <lambda>
      lambda s: _singlescale_basic_features_singlechannel(
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:28: in _singlescale_basic_features_singlechannel
      results += (*_texture_filter(gaussian_filtered),)
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/_basic_features.py:14: in _texture_filter
      eigvals = feature.hessian_matrix_eigvals(H_elems)
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/corner.py:413: in hessian_matrix_eigvals
      return _symmetric_compute_eigenvalues(H_elems)
  /tmp/tmp.xmdLqkZ753/venv/lib/python3.9/site-packages/skimage/feature/corner.py:275: in _symmetric_compute_eigenvalues
      eigs = np.linalg.eigvalsh(matrices)[..., ::-1]
  <__array_function__ internals>:5: in eigvalsh
      ???
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  a = array([[[[[-1.21414661e-04, -1.69277191e-04,  3.27229500e-04],
            [-1.69277191e-04, -6.97374344e-06, -2.1612644...[ 9.68217850e-04, -5.34951687e-05, -3.97205353e-04],
            [ 1.41447783e-03, -3.97205353e-04,  4.82678413e-04]]]]])
  UPLO = 'L'
  
      @array_function_dispatch(_eigvalsh_dispatcher)
      def eigvalsh(a, UPLO='L'):
          """
          >>> a = np.array([[1, -2j], [2j, 5]])
          >>> LA.eigvalsh(a)
          array([ 0.17157288,  5.82842712]) # may vary
      
          >>> # demonstrate the treatment of the imaginary part of the diagonal
          >>> a = np.array([[5+2j, 9-2j], [0+2j, 2-1j]])
          >>> a
          array([[5.+2.j, 9.-2.j],
                 [0.+2.j, 2.-1.j]])
          >>> # with UPLO='L' this is numerically equivalent to using LA.eigvals()
          >>> # with:
          >>> b = np.array([[5.+0.j, 0.-2.j], [0.+2.j, 2.-0.j]])
          >>> b
          array([[5.+0.j, 0.-2.j],
                 [0.+2.j, 2.+0.j]])
          >>> wa = LA.eigvalsh(a)
          >>> wb = LA.eigvals(b)
          >>> wa; wb
          array([1., 6.])
          array([6.+0.j, 1.+0.j])
      
          """
          UPLO = UPLO.upper()
          if UPLO not in ('L', 'U'):
              raise ValueError("UPLO argument must be 'L' or 'U'")
      
          extobj = get_linalg_error_extobj(
              _raise_linalgerror_eigenvalues_nonconvergence)
          if UPLO == 'L':
              gufunc = _umath_linalg.eigvalsh_lo
          else:
              gufunc = _umath_linalg.eigvalsh_up
      
          a, wrap = _makearray(a)
          _assert_stacked_2d(a)
          _assert_stacked_square(a)
          t, result_t = _commonType(a)
          signature = 'D->d' if isComplexType(t) else 'd->d'
  >       w = gufunc(a, signature=signature, extobj=extobj)
  E       ValueError: On entry to DSYEVD parameter number 8 had an illegal value

**Comment by grlee77** [comment] 2022-02-28 21:14
I am going to close this issue as stale since we do not distribute 32-bit linux wheels anymore as of 0.19.0? We also no longer use the scikit-image-wheels repository to build the wheels.

We do have 32-bit Windows wheels but only for Python 3.7-3.9 since NumPy dropped 32-bit windows wheels with Python 3.10.

**Comment by KOLANICH** [comment] 2022-03-01 16:45
[Has it really?](https://github.com/numpy/numpy/issues/20277#issuecomment-957529088) Citation needed.

**Comment by grlee77** [comment] 2022-03-01 21:10
Okay, I guess they are just temporarily unavailable. I can reopen here

**Comment by hmaarrfk** [comment] 2022-03-01 22:35
I feel like we are testing 32 bit Linux during the build procedure.

Is that not true anymore? Maybe it was a cython and compiler bug

**Comment by stefanv** [comment] 2023-02-22 20:35
Our intent for the next release is not to provide 32-bit Windows (or any other platform) wheels, in line with SciPy's decision.

Since we have switched build systems in the mean time, I'm sure there will be new issues compiling on some of those platforms, but we'd need to handle them on a case by case basis.

**Closed by stefanv** 2023-02-22 20:35 UTC
Labels: :computer: Specific arch failure
