### ISSUE TITLE
Anaconda Defaults doesn't have 0.14.2. Fails with numpy 1.16

### ISSUE THREAD

**Issue by jgostick** [scikit-image/scikit-image#3780] opened 2019-03-04 04:26 UTC
## Description
The import of _validate_lengths in scikit-image/skimage/util/arraycrop.py fails now that I've upgraded to Numpy 1.16.2.  After some investigation is seems that the version comparison check does not work as it should.  

## Way to reproduce
```python
import skimage
```

But the real problem seems to stem from:

```python
import numpy as np
from distutils.version import LooseVersion as Version
old_numpy = Version(np.__version__) < Version('1.16')
print(old_numpy)
print(np.__version__ < '1.16')
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
numpy version: 1.16.2

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-25-f837fe66f817> in <module>
      4 import platform; print(platform.platform())
      5 import numpy; print("numpy version: {}".format(numpy.__version__))
----> 6 import skimage; print("scikit-image version: {}".format(skimage.__version__))

~\Anaconda3\lib\site-packages\skimage\__init__.py in <module>
    174                              dtype_limits)
    175 
--> 176     from .util.lookfor import lookfor
    177     from .data import data_dir
    178 

~\Anaconda3\lib\site-packages\skimage\util\__init__.py in <module>
      6 from .apply_parallel import apply_parallel
      7 
----> 8 from .arraycrop import crop
      9 from ._regular_grid import regular_grid, regular_seeds
     10 from .unique import unique_rows

~\Anaconda3\lib\site-packages\skimage\util\arraycrop.py in <module>
      6 
      7 import numpy as np
----> 8 from numpy.lib.arraypad import _validate_lengths
      9 
     10 

ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Users\Jeff\Anaconda3\lib\site-packages\numpy\lib\arraypad.py)



```

**Comment by grlee77** [comment] 2019-03-04 04:31
This should have been fixed in release scikit-image 0.14.2. Can you confirm which version of scikit-image you are using?

I am going to close this as a duplicate of #3551, but please continue the discussion here if you continue to have the problem.

**Comment by hmaarrfk** [comment] 2019-03-04 04:34
Its probably because anaconda defaults doesn't have scikit-image 0.14.2

https://anaconda.org/anaconda/scikit-image

**Comment by hmaarrfk** [comment] 2019-03-04 04:35
can you output 

```
conda list
```

if you are using conda, or 
```
pip list
```
if you are using pip (or both if you don't know)

**Comment by hmaarrfk** [comment] 2019-03-04 04:40
I really suspect you are using the default Anaconda channel.

A few suggestions:
1. Downgrade numpy to 1.15
```
conda install numpy=1.15
```
2. Use conda-forge https://github.com/conda-forge/scikit-image-feedstock https://conda-forge.org/

I would go with suggestion 1. 

That said, Python from Anaconda Defaults has been giving me lots of grief on Windows recently, so conda-forge might not be so bad to recommend.

Lets close this in a few days. After monitoring down stream https://github.com/AnacondaRecipes/scikit-image-feedstock/pull/3

**Comment by grlee77** [comment] 2019-03-04 04:55
Thanks for following up with more details @hmaarrfk. I did not realize that conda defaults was still on an older release.

**Comment by jni** [comment] 2019-03-04 07:58
@jgostick can you confirm whether the above suggestions fix your issue? It was definitely regrettable that the NumPy release broke our code because we were using private functionality, but there is little else we can do other than make a bugfix release. (Unless you have a time machine.)

**Comment by jgostick** [comment] 2019-03-04 13:19
``conda list`` reports version 0.14.1 for skimage.   I did ``conda update --all`` so assumed it was current, but apparently not.  Is 0.14.2 not on conda yet?  

BTW, I noticed this error via a Travis build, which started using Numpy 1.16 recently, while still using 0.14.1 of skimage, and now it doesn't build.  I assume I'm not the only one?

Also, let me apologize for reporting about the version checking not working...I was mistaken about how the logic was working (working too late at night and not paying enough attention).

**Comment by hmaarrfk** [comment] 2019-03-04 13:24
We don't control the Anaconda Distribution. I've requested that they update, but who knows when they'll have time.

conda-forge is a community driven conda channel. That one has 0.14.2. Now, they are basically the same packages between conda-forge, and the official anaconda channel.

**Comment by hmaarrfk** [comment] 2019-03-04 13:25
> Now, they are basically the same packages between conda-forge, and the official anaconda channel.

I mean, packages are mostly interoperable.

**Comment by hmaarrfk** [comment] 2019-03-04 13:27
I'm glad you opened a new issue. The solution to your particular issue is one we hadn't written anywhere else. No need to appologize for trying to investigate on your own :smile:

**Comment by bidhya** [comment] 2019-03-04 17:02
I had the same issue upon updating the numpy. So, basically running the following command update the skimage (from conda-forge channel ) on windows, the error is resolved.

conda update scikit-image -c conda-forge

**Comment by jgostick** [comment] 2019-03-04 19:48
Ok, so I will update my travis yaml to use the conda-forge channel instead of the default.  Thank you all.  I will let you close this issue if you see fit, but I think I'm all good now.

**Closed** 2019-03-04 21:08 UTC
