### ISSUE TITLE
error while using data.coins()

### ISSUE THREAD

**Issue by XtremeGood** [scikit-image/scikit-image#3852] opened 2019-04-20 16:24 UTC
## Description
While importing data.coins() I was getting some snappy AttributeKey error. As I checked on stackoverflow it was suggested to use ipython-snappy instead of snappy but in the jupyter cell I could see that scikitimage was using "import snappy".

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
from skimage import data
coins  = data.coins()



```
## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17763-SP0

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ecfc35388d92> in <module>
      2 import sys; print(sys.version)
      3 import platform; print(platform.platform())
----> 4 import skimage; print("scikit-image version: {}".format(skimage.__version__))
      5 import numpy; print("numpy version: {}".format(numpy.__version__))

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\__init__.py in <module>
    165         _raise_build_error(e)
    166     # All skimage root imports go here
--> 167     from .util.dtype import (img_as_float32,
    168                              img_as_float64,
    169                              img_as_float,

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\util\__init__.py in <module>
      4 from .shape import view_as_blocks, view_as_windows
      5 from .noise import random_noise
----> 6 from .apply_parallel import apply_parallel
      7 
      8 from .arraycrop import crop

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\util\apply_parallel.py in <module>
      6 
      7 try:
----> 8     import dask.array as da
      9     dask_available = True
     10 except ImportError:

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\array\__init__.py in <module>
      4     from ..utils import ignoring
      5     from .blockwise import blockwise, atop
----> 6     from .core import (Array, block, concatenate, stack, from_array, store,
      7                        map_blocks, to_hdf5, to_npy_stack, from_npy_stack,
      8                        from_delayed, asarray, asanyarray, PerformanceWarning,

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\array\core.py in <module>
     44 from ..sizeof import sizeof
     45 from ..highlevelgraph import HighLevelGraph
---> 46 from ..bytes.core import get_mapper, get_fs_token_paths
     47 from .numpy_compat import _Recurser, _make_sliced_dtype
     48 from .slicing import slice_array, replace_ellipsis

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\__init__.py in <module>
      2 
      3 from ..utils import ignoring
----> 4 from .core import read_bytes, open_files
      5 
      6 from . import local

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\core.py in <module>
      9 from toolz import merge
     10 
---> 11 from .compression import seekable_files, files as compress_files
     12 from .utils import (SeekableFile, read_block, infer_compression,
     13                     infer_storage_options, build_name_function,

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\compression.py in <module>
     29 with ignoring(ImportError):
     30     import snappy
---> 31     compress['snappy'] = snappy.compress
     32     decompress['snappy'] = snappy.decompress
     33 

AttributeError: module 'snappy' has no attribute 'compress'



```python
# your output here

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-80a2aff18844> in <module>
----> 1 from skimage import data
      2 coins  = data.coins()

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\__init__.py in <module>
    174                              dtype_limits)
    175 
--> 176     from .util.lookfor import lookfor
    177     from .data import data_dir
    178 

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\util\__init__.py in <module>
      4 from .shape import view_as_blocks, view_as_windows
      5 from .noise import random_noise
----> 6 from .apply_parallel import apply_parallel
      7 
      8 from .arraycrop import crop

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\skimage\util\apply_parallel.py in <module>
      6 
      7 try:
----> 8     import dask.array as da
      9     dask_available = True
     10 except ImportError:

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\array\__init__.py in <module>
      4     from ..utils import ignoring
      5     from .blockwise import blockwise, atop
----> 6     from .core import (Array, block, concatenate, stack, from_array, store,
      7                        map_blocks, to_hdf5, to_npy_stack, from_npy_stack,
      8                        from_delayed, asarray, asanyarray, PerformanceWarning,

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\array\core.py in <module>
     44 from ..sizeof import sizeof
     45 from ..highlevelgraph import HighLevelGraph
---> 46 from ..bytes.core import get_mapper, get_fs_token_paths
     47 from .numpy_compat import _Recurser, _make_sliced_dtype
     48 from .slicing import slice_array, replace_ellipsis

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\__init__.py in <module>
      2 
      3 from ..utils import ignoring
----> 4 from .core import read_bytes, open_files
      5 
      6 from . import local

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\core.py in <module>
      9 from toolz import merge
     10 
---> 11 from .compression import seekable_files, files as compress_files
     12 from .utils import (SeekableFile, read_block, infer_compression,
     13                     infer_storage_options, build_name_function,

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\dask\bytes\compression.py in <module>
     29 with ignoring(ImportError):
     30     import snappy
---> 31     compress['snappy'] = snappy.compress
     32     decompress['snappy'] = snappy.decompress
     33 

AttributeError: module 'snappy' has no attribute 'compress'
```

**Comment by hmaarrfk** [comment] 2019-04-20 19:24
Can you please fill out the rest of the requested information in the bug report?

**Comment by emmanuelle** [comment] 2019-04-22 20:33
There seems to a problem with your installation of ``dask`` (a dependency of scikit-image), could you please uninstall it and install it again? If it doesn't work, as @hmaarrfk suggested please give us more details in particular the version information and how you installed scikit-image.

**Comment by XtremeGood** [comment] 2019-04-22 22:06
Well, I used pip uninstall dask and then pip install dask but the problem still persists with the same error. By the way I am using jupyter notebook. Please tell me what kind of information is to be posted as I think I have posted whatever I was trying to do and got that error.

**Comment by hmaarrfk** [comment] 2019-04-22 23:31
Thanks for the added info. Those commands are basically the minimum information we need to understand your system.

You didn't really include the output of

```python
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
```

That helps too.

I have a feeling something is broken with your dask. It could be due to a few things, but the easiest way to tell is if you could open some kind of termina, and run the command 

```
pip list
```

that outputs all the versions of all the packages you have installed.

If you have trouble running that command, please run

```python
import pkg_resources; 
installed_packages = [(d.project_name, d.version) for d in pkg_resources.working_set]
from pprint import pprint
pprint(installed_packages)
```

**Comment by stefanv** [comment] 2019-04-23 00:32
Mark, this makes me wonder if we should have a script people can
download and run to debug their systems, that would give us a full
diagnostic report?

**Comment by hmaarrfk** [comment] 2019-04-23 03:50
@stefanv the challenge is keepign it under a few lines of code. I'm not sure people will be able to do things like "download a script and run it" it is legitimately difficult. Are you supposed to double click on it? How do you run it in jupyter? Spyder?

 The 4 lines of code we have in there are basically the bare minimum. When people run those and give us the output, I think it allows us to probe for more details. In many PRs, people just think that it is optional. They would ignore whatever else we would give them.

But here, we can do things like see what directory things are installed in. For example, I can immediately tell that they are using Windows, installed in a pretty "default" directory, for what I think is the installer from python.org. Therefore they use pip, not conda, and we can proceed to more targetted questions.

They also installed jupyter in the default environment, which is likely the cause of issues. I think from that pprint command, we will see that he is likely running an older version of pip which probably broke their environment. I'd rather have engagement, than people running too many commands, and us asking for more later.

**Comment by stefanv** [comment] 2019-04-23 18:15
I don't have strong opinions on this: I just see the same questions coming up over and over again, and I thought saying "run this debug script for us" is easier than guiding them through the same probing process over and over.

**Comment by hmaarrfk** [comment] 2019-05-19 16:07
@XtremeGood I assume you managed to get things working? Please let us know if we should close this issue.

**Comment by XtremeGood** [comment] 2019-05-19 16:18
Nope I dropped working on it.

**Comment by hmaarrfk** [comment] 2019-05-19 16:24
I know that about 30 days ago (when you first opened this issue) there were a few hiccups with dask and numpy, and skimage in terms of a change in the internal functions of numpy.

We are fairly confident that these issues have been resolved by upgrading to skimage 0.14.2, (or 0.15.0) and updating dask.

If that is something you still wanted to try, please let us know. Otherwise, I am inclined to close this issue. But i would rather help you get things working if that is still what you want.

**Comment by XtremeGood** [comment] 2019-05-19 16:25
Both dask and scikit image give same error regarding snapy

**Comment by hmaarrfk** [comment] 2019-05-19 16:28
can you upgrade dask?

**Comment by XtremeGood** [comment] 2019-05-19 17:26
Currently I m travelling and my laptop is in my bag underneath my clothes
and stuff.I will surely respond back day after tomorrow.

**Comment by sciunto** [comment] 2019-08-09 10:01
Im' closing this issue and there is no reply since mi-may. If you still face the issue, please reopen.

**Closed by sciunto** 2019-08-09 10:01 UTC
Labels: type: support
