### ISSUE TITLE
Can't read in geotiff image with imread but can imshow 

### ISSUE THREAD

**Issue by rbavery** [scikit-image/scikit-image#4157] opened 2019-09-13 00:23 UTC
## Description
imread fails with the following error:
`ValueError: operand array with iterator write flag set is read-only`
When reading a geotiff, see attached. I've used skimage.io.imread to read geotiffs before so I'm not sure why it is failing on this one.

The particularly strange thing is that I can still show the image with `imshow` by supplying the same filepath. I can also read this file path in as a numpy array with rasterio

Here is the image: https://ucsb.box.com/s/80fjva1e5jv993umh92kt694gwzukqgd

## Way to reproduce
```python
import rasterio
import skimage.io as skio
path = "./LT05_CU_012007_20050515_20190108_C01_V01_SRCLOUDQA.tif"
# this works
with rasterio.open() as src:
    arr = src.read(path)
# this works
skio.imshow(path)
# this does not
skio.imread(path)
```
Full traceback
```python-traceback
/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/_plugins/matplotlib_plugin.py:75: UserWarning: Low image data range; displaying image with stretched contrast.
  warn("Low image data range; displaying image with "
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-0012c3ad129b> in <module>
      9 skio.imshow(cloud_qa.as_posix())
     10 
---> 11 skio.imread(cloud_qa.as_posix())

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/_plugins/tifffile_plugin.py in imread(fname, dtype, **kwargs)
     36     # read and return tiff as numpy array
     37     with TiffFile(fname, **kwargs_tiff) as tif:
---> 38         return tif.asarray(**kwargs)

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in asarray(self, key, series, memmap, tempdir)
   1505                                      colormapped=False, squeeze=False)
   1506         elif len(pages) == 1:
-> 1507             result = pages[0].asarray(memmap=memmap)
   1508         elif self.is_ome:
   1509             assert not self.is_indexed, "color mapping disabled for ome-tiff"

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in asarray(self, squeeze, colormapped, rgbonly, scale_mdgel, memmap, reopen, maxsize)
   2588                         tile = t.reshape(tile_shape)
   2589                     if self.predictor == 'horizontal':
-> 2590                         numpy.cumsum(tile, axis=-2, dtype=dtype, out=tile)
   2591                     elif self.predictor == 'float':
   2592                         raise NotImplementedError()

<__array_function__ internals> in cumsum(*args, **kwargs)

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/numpy/core/fromnumeric.py in cumsum(a, axis, dtype, out)
   2421 
   2422     """
-> 2423     return _wrapfunc(a, 'cumsum', axis=axis, dtype=dtype, out=out)
   2424 
   2425 

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: operand array with iterator write flag set is read-only
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python

3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
Linux-4.15.0-1056-azure-x86_64-with-debian-stretch-sid
scikit-image version: 0.15.0
numpy version: 1.17.1

```

**Comment by rbavery** [comment] 2019-09-16 22:15
Hi Juan! It turns out the error is because `imshow` uses `call_plugin` directly rather than the `skimage.io.imread` function. So it ends up using imageio to read in the tiff image, since there is no check for the tiff extension in `imshow`. So the problem is in the official `tifffile` package, since I tested this after `pip install tifffile`. I'm not able to test this after `pip install imagecodecs`, I keep getting gcc build errors related to `imagecodecs/opj_color.c:49:10: fatal error: lcms2.h: No such file or directory`

**Comment by cgohlke** [comment] 2019-09-17 12:55
> So the problem is in the official tifffile package, since I tested this after pip install tifffile

It doesn't look like. The traceback refers to `/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py` and the issue is probably due to a modification in the vendored code #3452.

**Comment by rbavery** [comment] 2019-10-03 18:53
ah, just saw this comment, my mistake. if skimage switches to not using the vendored tifffile maybe this will get solved in the process.

**Comment by rfezzani** [comment] 2020-04-04 16:39
Closing since `tifffile` is no more included in `skimage`. Feel free  to reopen if you wish ;-) Thank you again @rbavery for reporting

**Closed by rfezzani** 2020-04-04 16:39 UTC
Labels: type: bug
