### ISSUE TITLE
Bug in `skimage.transform.resize()`

### ISSUE THREAD

**Issue by fbudin69500** [scikit-image/scikit-image#3445] opened 2018-10-03 20:14 UTC
## Description
I resized one image on two different computers and got images that were slightly different (see below how to reproduce the problem).

In the Python notebook included in the small helper project to reproduce the problem, an image shows where there are differences between the images computed on the two different computers. The differences appear to be aligned on several lines. In the example that is provided, there are 7 lines on which these differences are. Note that if one changes the resampling parameters (output image size), the number of lines will vary (In my experiments, from 0 [no visible bug] to as many as 15). However, there always seem to be such a line pattern. The image differences are never randomly distributed in the output image.

## Way to reproduce
To reproduce the bug, one can use the following small project:
https://github.com/fbudin69500/debug_scikit_image_resize-

I used that project to generate the numpy arrays (images) that are included in the project. I ran the script on 2 different computers running on Ubuntu 18.04. I have scikit-image v0.14.1 installed on both
Relevant images are visible in the Python notebook that is included in the project.

On both computer, I am using Ubuntu 18.04 and Python 2.7.15rc1.

Idea
====
Because of the alignment of the differences, I am thinking that the problem might come from how the image is split in different regions while being processed.

**Comment by hmaarrfk** [comment] 2018-10-03 21:09
I'm trying to recreate your issue, but the ipython notebook doesn't seem to fully contain the issue.

Is there a way to recreate the issue in a single notebook?

```
from skimage.transform import resize
resize_debug = np.load('resize-debug.npy')
l = resize(resize_debug, [400,400], order=0)
t = ???
```

**Comment by fbudin69500** [comment] 2018-10-03 21:17
I created the Python notebook (`CompareImages.ipynb`) as a mean to visualize the results. Since the process has to be run on two different computers, it was easier for me to create a simple Python script to run manually in the terminal to generate the output image (`script-resize.py`).

So the way to recreate the issue is:
1) Run `script-resize.py` on different computers
2) Load the results in the Python notebook (`CompareImages.ipynb`)

Note that I have included the data files at each step:
* `resize-debug.npy` is `script-resize.py`  input
* `resized.npy` and `resized_2.npy` are the output of `script-resize.py` run on two different computers. These files are also the input of the Python notebook.

**Comment by fbudin69500** [comment] 2018-10-03 21:20
Note that I have try to generate an input image that only contained a limited amount of information, with just a couple rectangles, and the problem was not visible when using that image.

**Comment by hmaarrfk** [comment] 2018-10-03 21:44
I have a feeling that it is due to rounding errors in how the indices are chosen for the subsampling. This could be related to the specific versions of the underlying libraries that are installed on your system.

Maybe you can step through the code to find where things are different.

It could be related to `scipy.ndimage`

**Comment by fbudin69500** [comment] 2018-10-03 21:50
It could indeed be a bug in `scipy.ndimage`. On both machines I have the same version: 1.1.0, and also the same numpy version: 1.14.5

**Comment by hmaarrfk** [comment] 2018-10-03 21:51
pip or conda?

**Comment by fbudin69500** [comment] 2018-10-03 21:52
pip. Maybe I should create a docker image to enforce reproducibility.

**Comment by hmaarrfk** [comment] 2018-10-03 21:53
I mean, first step through the code, and find out which line is different exactly. you know from your output exactly which row/col indices are different

**Comment by jni** [comment] 2018-10-04 09:17
I think this is a duplicate of https://github.com/scikit-image/scikit-image/issues/2629. It appears to be caused by rounding errors depending on the underlying BLAS library. I don't know what the right fix is, but I'm unhappy with the one proposed [here](https://github.com/scikit-image/scikit-image/pull/2648#issuecomment-301671206). (Looks like I owe @stefanv a response from a year ago :joy:)

**Comment by fbudin69500** [comment] 2018-10-04 14:12
I just ran the notebook provided in #2629 on my two computers, both running Ubuntu 18.04, and I get the same result on both. So the problem I am experiencing is likely different. I haven't had time to debug both code step by step yet.

**Comment by jni** [comment] 2018-10-05 02:44
Since all of these things are about tiny numerical instabilities, they may well manifest in different test cases for different machine/OS/BLAS combinations. @fbudin69500 one idea would be to try the hacky fix in #2648 on your problem, and see whether you stop seeing the difference.

**Comment by sciunto** [comment] 2018-10-05 05:36
@jni At least, we could add a note in the docstring. 

@fbudin69500 Do the two computers have different architectures?

**Comment by fbudin69500** [comment] 2018-10-05 14:28
@jni Thanks for the tip. I compiled scikit-image at that specific PR (#2648) and it seems that it solves my issue (https://github.com/fbudin69500/debug_scikit_image_resize-/blob/resize_with_scikit_image_pr_2648/CompareImages.ipynb).

@sciunto : For reference, I added that information in the readme file in the debug project I created (https://github.com/fbudin69500/debug_scikit_image_resize-).

CPU information
===============

* CPU of computer generating `resized.npy` (lscpu)
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:            1
CPU MHz:             2423.717
CPU max MHz:         3400.0000
CPU min MHz:         2200.0000
BogoMIPS:            6786.62
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7,16-23
NUMA node1 CPU(s):   8-15,24-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
```

* CPU of computer generating `resized_2.npy` (lscpu)
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Stepping:            3
CPU MHz:             800.161
CPU max MHz:         3600.0000
CPU min MHz:         800.0000
BogoMIPS:            5424.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

**Comment by grlee77** [comment] 2022-02-28 22:22
I will link to the existing #2629 here as a similar issue and go ahead and close this one.

**Closed by grlee77** 2022-02-28 22:22 UTC
Labels: type: bug
