### ISSUE TITLE
skimage.feature.peak_local_max problem

### ISSUE THREAD

**Issue by loomcode** [scikit-image/scikit-image#4978] opened 2020-09-17 19:36 UTC
The peak_local_max function returns multiple points within the specified min_distance if it finds neighboring pixels of equal value.  This is counter to the min_distance definition.

**Comment by jni** [comment] 2020-09-18 02:57
@loomcode thanks for reporting! This is a duplicate of #2592 which is being addressed in #4760, so I'll close this. We are close to releasing 0.18 which we hope will include these fixes, so, hold please! 😊

**Closed by jni** 2020-09-18 02:57 UTC
