### ISSUE TITLE
Unable to install on Nvidia Xavier. Stuck at 100%.

### ISSUE THREAD

**Issue by zendevil** [scikit-image/scikit-image#4949] opened 2020-08-29 18:56 UTC
## Way to reproduce
```python
pip3 install scikit-image
```
on Nvidia Jetson Xavier

## Version information
```python
>>> 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
>>> Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'skimage'
>>> numpy version: 1.13.3
```

scikit-image installation stuck at 100%
```python


root@proto1:~/clotorch/resources# pip3 install scikit-image
The directory '/home/prikshet/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/prikshet/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scikit-image
  Downloading https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz (29.8MB)
    100% |████████████████████████████████| 29.8MB 27kB/s 


```

When cloning and running pip3 install -e . Stuck at Obtaining file://foo/scikit-image

**Comment by hmaarrfk** [comment] 2020-08-29 23:21
can you try

```
pip3 install scikit-image -vv
```

compilation takes time and I have a feeling it is taking time compiling things.

@sciunto was it you taking care of the labels? I would like a label to collate installation issues so that we may better track challenges users have getting started on that front.

**Comment by hmaarrfk** [comment] 2020-08-29 23:28
also, your numpy version is very old. you definitely need to satisfy https://github.com/scikit-image/scikit-image/blob/master/requirements/build.txt

I think below numpy 1.16, you will have a hard time on arm, but that is just my personal experience with that.

**Comment by sciunto** [comment] 2020-08-30 05:12
What do you need specifically? `type: installation` is not sufficient? @hmaarrfk

**Comment by zendevil** [comment] 2020-08-30 06:47
```

    /usr/local/lib/python3.6/dist-packages/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g_sngh2o/scipy/setup.py", line 583, in <module>
        setup_package()
      File "/tmp/pip-build-g_sngh2o/scipy/setup.py", line 579, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-g_sngh2o/scipy/setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
error
  Can't rollback scipy, nothing uninstalled.
Cleaning up...
  Removing source in /tmp/pip-build-g_sngh2o/scipy
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g_sngh2o/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-z1mly8zh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-g_sngh2o/scipy/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g_sngh2o/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-z1mly8zh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-g_sngh2o/scipy/
root@proto1:~# root@proto1:~# root@proto1:~#  python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.1'

```

**Comment by sciunto** [comment] 2020-08-30 06:52
Install liblapack from your package manager.

**Comment by zendevil** [comment] 2020-08-30 07:15
Did 
```
sudo apt-get install libatlas3-base
```

from 

https://askubuntu.com/questions/300542/liblapack-so-file

still getting 

     libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']

**Comment by sciunto** [comment] 2020-08-30 10:33
you likely need the dev files which are usually provided separately in on your OS. Anyway, it doesn't seems to be an issue for scikit-image.

**Comment by FirefoxMetzger** [comment] 2020-08-30 12:06
I second @sciunto . You are compiling C code during the installation process which means you don't just need the shared libraries (obtained via `libatlas-base`), but also the header files (obtained via `libatlas-base-dev`) so that the linker knows how to link against the libraries.

At the very least you will need 

```
sudo apt-get install libatlas3-base libatlas-base-dev
```

and depending on other bindings you might need the header files for lapack and blas, too. (`liblapack-dev` and `libblas-dev`).

**Comment by hmaarrfk** [comment] 2020-08-30 12:38
For what it's worth.co da forge just aren't through this compilation procedure.

Depending on your other dependencies, you might have some luck with conda and conda forge

**Comment by hmaarrfk** [comment] 2020-08-30 18:06
Here are the links to what I was talking about

1. Install miniforge: https://github.com/conda-forge/miniforge/ for aarch64
2. Then you should be OK to install scikit-image: https://github.com/conda-forge/scikit-image-feedstock

Putting my conda-forge contributor hat on: while we (conda-forge) don't don't have the full list of packages for aarch64 compiled, we have quite a few and we recently got scikit-image. If your stack ends there, then it will really help boost you in your installation procedure. If you also need packages that we haven't compiled yet, for example opencv, then you will have to work on a more complete solution for your particular application.

@FirefoxMetzger did give pointers in the right direction, So I think that will help.

**Comment by sciunto** [comment] 2020-09-03 05:43
As we do not have further replies and the issue is not related to scikit-image, I'm closing. If not solved, feel free to reopen.

**Closed by sciunto** 2020-09-03 05:43 UTC
Labels: type: failure arch specific, type: installation, type: support
