### ISSUE TITLE
Getting "ImportError: DLL load failed: The specified module could not be found."

### ISSUE THREAD

**Issue by prats0305** [scikit-image/scikit-image#4780] opened 2020-06-07 23:08 UTC
## Description

Tried to run script containing:
from skimage.filters import threshold_local
import numpy as np
import argparse
import cv2
import imutils

Getting below error:
from skimage.filters import threshold_local
  File "C:\Python\Python36\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Python\Python36\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Python\Python36\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be fou

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
Traceback (most recent call last):
  File "restart.py", line 4, in <module>
    import skimage; print("scikit-image version: {}".format(skimage.__version__))
  File "C:\Python\Python36\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Python\Python36\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Python\Python36\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.
```

Numpy Version is getting printed successfully
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.18.5

**Comment by prats0305** [comment] 2020-06-08 05:17
Note : I had Installed  scikit-image using command - pip install scikit-image.
The installation was successful.

**Comment by prats0305** [comment] 2020-06-08 05:37
`C:\Python\Python36\Scripts>pip uninstall scikit-image
Uninstalling scikit-image-0.17.2:
  Would remove:
    c:\python\python36\lib\site-packages\scikit_image-0.17.2.dist-info\*
    c:\python\python36\lib\site-packages\skimage\*
    c:\python\python36\scripts\skivi.exe
Proceed (y/n)? y
  Successfully uninstalled scikit-image-0.17.2

C:\Python\Python36\Scripts>pip install scikit-image
Collecting scikit-image
  Using cached https://files.pythonhosted.org/packages/09/e2/39fd2aad9858c764bc260acdf4bb63f8096415ee2b782cc2f7ea47a12c79/scikit_image-0.17.2-cp36-cp36m-win_amd64.whl
Requirement already satisfied: networkx>=2.0 in c:\python\python36\lib\site-packages (from scikit-image) (2.4)
Requirement already satisfied: scipy>=1.0.1 in c:\python\python36\lib\site-packages (from scikit-image) (1.4.1)
Requirement already satisfied: numpy>=1.15.1 in c:\python\python36\lib\site-packages (from scikit-image) (1.18.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\python\python36\lib\site-packages (from scikit-image) (3.2.1)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in c:\python\python36\lib\site-packages (from scikit-image) (7.1.2)
Requirement already satisfied: imageio>=2.3.0 in c:\python\python36\lib\site-packages (from scikit-image) (2.8.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\python\python36\lib\site-packages (from scikit-image) (1.1.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\python\python36\lib\site-packages (from scikit-image) (2020.6.3)
Requirement already satisfied: decorator>=4.3.0 in c:\python\python36\lib\site-packages (from networkx>=2.0->scikit-image) (4.4.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\python\python36\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\python\python36\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python\python36\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\python\python36\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (0.10.0)
Requirement already satisfied: six>=1.5 in c:\python\python36\lib\site-packages (from python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.15.0)
Installing collected packages: scikit-image
Successfully installed scikit-image-0.17.2
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python\Python36\Scripts>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Python\Python36\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Python\Python36\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.`

**Comment by emmanuelle** [comment] 2020-06-15 09:48
@jni @VolkerH this problem is with the new `map_array` code which uses C++ from Cython, which is something new for scikit-image. Do you have any idea of what may cause this issue? A missing library?

**Comment by jni** [comment] 2020-06-15 10:06
Oops, missed this, was on leave last week, sorry!

I'm not sure what could be causing it, no... It only uses C++ standard library functions, so they should be present somewhere I think! My only concern is that `unordered_map` was unavailable in some *very old* C++ compilers/stdlib, which might be what's happening, but I would find that hard to believe given it's a Python 3.6 distribution.

@prats0305 could you tell us how you installed your Python environment? Is it Anaconda or python.org or something else? That might give us a clue as to what is present.

In the meantime, though, you can get started by doing `pip install scikit-image==0.16`, since you don't appear to be using anything from the latest version. That version will not have this issue.

One thing I should say, @emmanuelle, is that the import refactor (importing only from private modules internally) should at least alleviate the problem, because we wouldn't be automatically importing things the user doesn't need. I might make that my focus for this week.

**Comment by VolkerH** [comment] 2020-06-15 11:44
Thanks for the mention, would have missed this otherwise. I also don't have a good idea what is happening there. 
There is the warning about the outdated `pip` version. I don't know much about the inner workings of installing wheels with `pip`  but is it conceivable that an older version of `pip` might install the DLL incorrectly ?

**Comment by hmaarrfk** [comment] 2020-06-15 12:44
One more question that might help jni:

Are you on windows 10 or 8 or other?

**Comment by prats0305** [comment] 2020-06-15 13:44
Hi,
To answer your questions:

- I installed python from python.org.
- I am using Windows 10 Home edition.

Thanks.

**Comment by cgohlke** [comment] 2020-06-15 15:46
```
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.
```

Very likely the C++ runtime library is missing. As a workaround, try to install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), or import matplotlib before skimage, or `python -m pip install msvc-runtime`.

Scikit-image could ship the required runtime DLLs next to the pyd file, similar to what matplotlib and Pandas are doing. See for example https://github.com/pandas-dev/pandas/issues/32857 or https://github.com/matplotlib/matplotlib/pull/5100

**Comment by jni** [comment] 2020-06-16 14:58
@cgohlke wow, thanks for chiming in!

I'm wondering whether we could add something like following line to our install-requires:

```
"msvc-runtime; sys.platform == 'win32'",
```
?

It feels a bit wrong for everyone to ship the same DLLs, rather than depend on the right package?

By the way, do you know whether conda environments provide these DLLs by default? ie is this only a problem with python.org Python?

**Comment by cgohlke** [comment] 2020-06-16 19:00
> |"msvc-runtime; sys.platform == 'win32'", |
> 
> ?

I think that should work in many cases. There are some issues:

1) Currently the msvc-runtime package installs a set of runtime DLLs in the sys.prefix and the Scripts folders only. That should cover most use cases (running python.exe, running executables from the Scripts folder, and virtual environments) but might fail when processes depending on the runtime DLLs are launched outside of sys.prefix or Scripts. 

2) pip is not able to replace DLL/PYD files that are in use. That leaves the possibility of broken installations when upgrading packages. In practice I have not run into this issue with the msvc-runtime package.

3) The msvc-runtime package is not widely used, tested, or supported. 

4) Using pip install/uninstall the msvc-runtime package might corrupt distributions other than the ones from Python.org.

5) I have been assured by a Microsoft employee that repackaging the Visual Studio runtime DLLs in this way is OK, even though it was my understanding (when I last looked at it years ago) that the license does not allow simple repackaging.

Ideally Microsoft would provide and maintain authoritative msvc/vs runtime packages on PyPI.

> It feels a bit wrong for everyone to ship the same DLLs, rather than 
> depend on the right package?

It does. But it is my understanding that pip/wheels are not really meant for this use case and that bundling dependency DLLs next to all PYD/DLL/executable files is the recommended/supported way for wheels on PyPI.

> By the way, do you know whether conda environments provide these DLLs by 
> default? ie is this only a problem with python.org Python?

I think it's only a problem with the Python.org distribution, which only includes the minimum C runtime DLL, not C++ or OpenMP. Conda has a vs2015_runtime package and I would expect other distributions/applications include a complete set of runtime DLLs. Maybe I'm mistaken...

**Comment by sciunto** [comment] 2020-09-01 08:53
I'm closing this issue. Please reopen if the problem persists.

**Comment by fakerbrother** [comment] 2020-12-24 05:47
> Oops, missed this, was on leave last week, sorry!
> 
> I'm not sure what could be causing it, no... It only uses C++ standard library functions, so they should be present somewhere I think! My only concern is that `unordered_map` was unavailable in some _very old_ C++ compilers/stdlib, which might be what's happening, but I would find that hard to believe given it's a Python 3.6 distribution.
> 
> @prats0305 could you tell us how you installed your Python environment? Is it Anaconda or python.org or something else? That might give us a clue as to what is present.
> 
> In the meantime, though, you can get started by doing `pip install scikit-image==0.16`, since you don't appear to be using anything from the latest version. That version will not have this issue.
> 
> One thing I should say, @emmanuelle, is that the import refactor (importing only from private modules internally) should at least alleviate the problem, because we wouldn't be automatically importing things the user doesn't need. I might make that my focus for this week.

This really help me, THX , :)

**Comment by jni** [comment] 2020-12-25 22:36
@fakerbrother 

> This really help me, THX , :)

Always great to hear! 😊 

@scikit-image/core I'm kinda thinking of reopening this. It's unclear what the best long-term fix is but I don't think we suitably addressed the issue, which is that scikit-image will be broken on some installations of Python. Any objections to keeping this open?

**Comment by patquem** [comment] 2021-01-08 15:55
Hello,
I meet this problem (and others) when trying to install scikit-image from pip install.
Please, have on look on this : https://github.com/dask/dask/issues/7045
Thanks,
Patrick

**Comment by jni** [comment] 2021-01-08 23:15
@patquem re your installation issues with 0.18, please see [this comment](https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644214783): you should be able to `pip install msvc-runtime` followed by `pip install scikit-image` and get the latest version.

However this will not fix the dask issue. I'll comment there.

**Comment by tb582** [comment] 2021-01-11 21:48
I ran `python -m pip install msvc-runtime` but still get the same error... 
`ImportError: DLL load failed while importing _remap: The specified module could not be found.`

**Comment by jni** [comment] 2021-01-14 04:35
Sorry to hear that @tb582! Very strange. Have you tried installing the Visual Studio C++ runtime as suggested in [this comment](https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644214783)?

**Comment by Zardoua-Yassir** [comment] 2021-01-26 20:38
I solved this exact issue on my computer. As pointed out by @emmanuelle , it's a missing library. I just installed the last version of Cython (currently Cython 0.29.21) and the error disappeared.

If this solution doesn't help, make sure to satisfy the following build requirements of **scikit-image 0.18.0**:
1) Cython version should be higher or equal to 0.29.21 but different from 0.29.18
2) Make sure to install _wheel_ package
3) Numpy version should be higher or equal to 1.16.5 but different from 1.18.0

I took these details from the Full requirements list section of this online doc:https://scikit-image.org/docs/stable/install.html
I hope this solves your issue!

**Comment by stefanv** [comment] 2021-01-27 00:12
Thank you @Zardoua-Yassir; we appreciate the write-up of your solution.

**Comment by patquem** [comment] 2021-01-27 10:56
Hello,

Thank you @Zardoua-Yassir for your proposal, but it doesn't work in my case.

I have created a virtual_env from python 3.7.7 following your recommendations (with numpy==1.19.0, Cython==0.29.21 and scikit-image==0.18.0)  and I get the same DLL error message as before.

Here are my 'pip list' resulting from my new virtual_env and the DLL error message that I obtain when importing scikit-image

Any idea of what 's wrong ?

Patrick 

ps : doing install with pip==20.3.3 or pip==21.0 return exactly the same things.

********

Package         Version
--------------- ---------
cycler          0.10.0
Cython          0.29.21
decorator       4.4.2
imageio         2.9.0
kiwisolver      1.3.1
matplotlib      3.3.3
networkx        2.5
numpy           1.19.0
Pillow          8.1.0
pip             20.3.3
pyparsing       2.4.7
python-dateutil 2.8.1
PyWavelets      1.1.1
scikit-image    0.18.0
scipy           1.6.0
setuptools      51.0.0
six             1.15.0
tifffile        2021.1.14
wheel           0.36.2

********

>>> import skimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\sw\envs3\env_skimage\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\dev\sw\envs3\env_skimage\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\dev\sw\envs3\env_skimage\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: Le module spécifié est introuvable.

**Comment by cowlinator** [comment] 2021-04-17 00:44
> you should be able to `pip install msvc-runtime` followed by `pip install scikit-image` and get the latest version.

@jni, if  `msvc-runtime` is a prerequisite, then why isn't it just included in the setup.py requirements like `numpy` and `pillow` are?

**Comment by jni** [comment] 2021-04-22 09:15
@cowlinator see [this comment](https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644953362). There were some issues with that solution which meant that we never took the decision to add it. I think probably we will go this route in the end, but the decision has to be made and is not 100% obviously the right solution.

**Comment by jni** [comment] 2021-04-22 09:57
I've added this to 0.19 so it gets looked at before our next release. @hmaarrfk @grlee77 any thoughts about adding this to the 0.18 branch also?

**Comment by cowlinator** [comment] 2021-05-21 23:53
I'm still having a problem with this.  I've tried all of these suggested workarounds:
1. pip installed latest version of `Wheel`
2. pip installed the last version of `Cython`, but not `0.29.18`
3. pip installed the latest version of `Numpy`, but not `1.18.0`
4. pip installed the latest version of `msvc-runtime`
5. pip installed the latest version of `matplotlib`, and import `matplotlib` before `skimage`

I am not able to revert `scikit-image` to `0.16`, since it fails (and might not be supported?) on `Python 3.9.`

It would be difficult for me to manually install `Microsoft Visual C++ Redistributable for Visual Studio`, since I am working in a Docker container and do not have access to modify the Docker Image.  Besides, shouldn't pip installing `msvc-runtime` be the same?

After attempting all of these workarounds, and uninstalling/reinstalling `scikit-image`, I still get the error
```
skimage\util\_map_array.py, line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by cgusb** [comment] 2021-06-30 17:58
> I am not able to revert `scikit-image` to `0.16`, since it fails (and might not be supported?) on `Python 3.9.`

I'm getting a similar error with `scikit-image 0.18.2` with `Python 3.9.5` (pip + Win 10) when I try to import `skimage.morphology`:
```
ImportError: DLL load failed while importing _rolling_ball_cy: The specified module could not be found.
```
@cowlinator I was able to work around the problem by reverting `scikit-image` to `0.18.0rc2` (This is the most recent version that eliminated the import error for me). Thought this might be helpful to put here, as it is a workaround that uses a more up-to-date version of `scikit-image` than `0.16`.

**Comment by stefanv** [comment] 2021-06-30 18:10
@cowlinator Thanks for identifying a more recently working version.  Just to confirm, did you try out all the versions listed [on PyPi](https://pypi.org/project/scikit-image/#history) after `0.18.0rc2`, and that was the only one that worked?

**Comment by cgusb** [comment] 2021-06-30 18:22
@stefanv Yes, I tried:  `0.18.0rc2, 0.18.0, 0.18.1, 0.18.2rc1, 0.18.2rc2, 0.18.2`
To be clear, this was to eliminate the `_rolling_ball_cy` ImportError I mentioned above, not the `_map_array` ImportError mentioned by @cowlinator. I'm not sure how closely related these issues are.

**Comment by HeToufani** [comment] 2021-08-11 10:51
Python 3.8+ no longer searches for DLL's on the path. Since this is an issue with building / environment this outside the scope of the project.

**Comment by hmaarrfk** [comment] 2021-08-11 12:34
I'm not so sure it is outside the scope of the project. The goal of the project is to make these algorithms available and usable.

I typically install everything with conda.

You are right to suspect that it is a path issue. however, with windows, it is sometimes easy to corrupt your path when you follow random guides on the internet. So that might be it.....

**Comment by grlee77** [comment] 2021-08-19 17:57
I was not able to reproduce the `_rolling_ball` import error when I tried on a Windows 10 system with Python 3.8.10. 

I created a clean Python 3.8 `virtualenv` installed via `pip install scikit-image`. This results in scikit-image 0.18.2 and its dependencies being installed from PyPI. No errors were observed on package import.

I am going to remove this from the 0.19 milestone, but have left the issue open. If there is any easy way to reproduce the error in a new environment, please let us know and we can take another look.

**Comment by cgohlke** [comment] 2021-08-19 22:13
This issue can only be reproduced on a Windows system without the "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" or Visual Studio >= 2015 installed.

One way to reliably reproduce this issue is in a [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview), a Windows 10 feature that needs to be enabled. Scripting the Sandbox is not straightforward but Python helps:

```Python
# test_skimage_import.py

import os


def test_skimage(
    pythonurl='https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe',
    test='_test_skimage',
):
    """Test scikit-image import in a Windows 10 Sandbox.

    1. write Python, Command, and Windows 10 Sandbox scripts to the current
       directory.
    2. run the Windows sandbox script, which runs the command script, which
       downloads and installs Python, pip installs scikit-image, and runs the
       Python script.
    3. patiently wait.
    4. open the log output in notepad.

    """
    pythonexe = pythonurl.rsplit('/', 1)[-1]
    testdir = rf'C:\Users\WDAGUtilityAccount\Desktop\{test}'
    logfile = f'{testdir}\{test}.txt'

    with open(test + '.wsb', 'w') as fh:
        fh.write(
            rf"""<!-- {test}.wsb -->
<Configuration>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>{os.path.dirname(__file__)}</HostFolder>
      <SandboxFolder>{testdir}</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>{testdir}\{test}.cmd</Command>
  </LogonCommand>
</Configuration>"""
        )

    with open(test + '.cmd', 'w') as fh:
        fh.write(
            rf""":: {test}.cmd
curl {pythonurl} --output {testdir}\{pythonexe} > {logfile} 2>&1
{testdir}\{pythonexe} /passive Include_tcltk=0 Include_test=0 Include_dev=0 ^
>> {logfile} 2>&1
py -m pip install scikit-image >> {logfile} 2>&1
::py -m pip install msvc_runtime >> {logfile} 2>&1
py {testdir}\{test}.py >> {logfile} 2>&1
start {logfile}
        """
        )

    with open(test + '.py', 'w') as fh:
        fh.write(
            f"""# {test}.py
import skimage
print('skimage version', skimage.__version__)
    """
        )

    os.system(test + '.wsb')


test_skimage()
```

The log file will end with:
```Python-traceback
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\_test_skimage\_test_skimage.py", line 2, in <module>
    import skimage
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed while importing _remap: The specified module could not be found.
```

Uncomment `::py -m pip install msvc_runtime` to make `import skimage` succeed.

I got two reports where installing the Microsoft Visual C++ runtime did not fix similar issues. It turned out that an existing installation of Visual Studio was corrupted and a repair install fixed the issue.

**Comment by cgusb** [comment] 2021-09-03 18:29
I was getting the `_rolling_ball_cy` import error on Windows 10 with `scikit-image` version 0.18.1 and I can confirm that installing [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019) (without making changes to my Python environment) and restarting my system removed the error.

I must have accidentally removed the C++ libraries, which would explain why my environment was working on my machine, then suddenly stopped working.

**Closed** 2021-10-18 07:32 UTC
Labels: type: support, type: installation
