### ISSUE TITLE
skimage.io.imshow produces wrong result in jupyter notebook

### ISSUE THREAD

**Issue by jaewooklee93** [scikit-image/scikit-image#3509] opened 2018-10-25 17:41 UTC
## Description
A very simple code below produces unrecognizable drawing at jupyter notebook run. It seems that color bar becomes very fat and it covers all the main figure so I can see nothing.

## Way to reproduce
- [x] Code example
```Python
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imshow

# for jupyter run
%matplotlib inline

img=np.array([[.1,0]],dtype=np.float32)
imshow(img)
# replacing the above line to the below removes error
# plt.imshow(img)
```

- [x] Relevant images (if any)
```
C:\Users\jaewooklee\AppData\Local\conda\conda\envs\venv\lib\
site-packages\skimage\io\_plugins\matplotlib_plugin.py:77: 
UserWarning: Low image data range; displaying image with stretched contrast.
  warn("Low image data range; displaying image with "
```
![download](https://user-images.githubusercontent.com/11328376/47518545-3d65b500-d8c6-11e8-9538-6b8cf6fcaaf8.png)
- [x] Operating system and version
* Reproduced at both Windows 10 / Ubuntu 16.02 LTS
* Jupyter notebook server : 5.7.0 
- [x] Python version: 3.6.6
- [x] scikit-image version (run `skimage.__version__`)
* scikit-image: 0.14.1
* matplotlib: 3.0.0
   * (The bug has been removed after downgrading matplotlib to 2.2.2)

**Comment by sciunto** [comment] 2018-11-22 14:16
I cannot reproduce this bug (either with matplotlib 3.0.0 or 3.0.2). @jaewooklee93 can you upgrade and check please?

**Comment by sciunto** [comment] 2018-11-24 16:55
I used a notebook as well.

**Comment by sciunto** [comment] 2018-11-24 16:56
Can you check with matplotlib 3.0.2 please?

**Comment by jaewooklee93** [comment] 2018-11-24 19:02
Okay, with matplotlib 3.0.2, this bug has gone.

![download](https://user-images.githubusercontent.com/11328376/48972003-6adc8480-f065-11e8-91f4-ffd71451cf8b.png)

It seems that matplotlib fixed their issue just a month ago at 3.0.1. [https://github.com/matplotlib/matplotlib/issues/12661/](https://github.com/matplotlib/matplotlib/issues/12661/)

**Comment by sciunto** [comment] 2018-11-24 20:41
Great! Thanks for testing. As matplotlib 3.0.0 is now blacklisted in scikit-image (will be in upcoming versions), we can consider this as fixed.

Feel free to reopen if not the case.

**Comment by s-mason** [comment] 2019-05-27 00:47
> I just tested my code just before and was able to reproduce this bug again. (at matplotlib 3.0.0)
> 
> [ipynb](https://github.com/jaewooklee93/bug_report/blob/master/bug_report.ipynb)
> 
> Maybe this bug is associated with Jupyter Notebook, so it seems to disappear when it runs on native Python.

i runs it on native Python, the problem also exists.

**Comment by jni** [comment] 2019-05-27 02:58
@s-mason which version of matplotlib are you using? You can check with `import matplotlib; print(matplotlib.__version__)`

**Comment by s-mason** [comment] 2019-05-29 12:51
> @s-mason which version of matplotlib are you using? You can check with `import matplotlib; print(matplotlib.__version__)`

3.1.0

**Comment by sciunto** [comment] 2019-05-29 19:50
I'm still not able to reproduce, but it is something we need to investigate. @scikit-image/core Is there anyone  who can reproduce this behavior with the notebook linked above?

**Comment by alexandrejaguar** [comment] 2019-05-29 20:27
@sciunto everything seems fine here. Matplotlib version: `'3.0.3'`

**Comment by alexdesiqueira** [comment] 2020-03-02 22:35
Tested again today, cannot reproduce. Matplotlib `3.1.3`.
Can you please try to update and reproduce @jaewooklee93? If not, I think it's safe to close this one @sciunto.

**Comment by jaewooklee93** [comment] 2020-03-12 02:04
I've tested again and both versions `3.1.0` `3.1.3` seem to make no problem at all.

**Comment by sciunto** [comment] 2020-03-12 06:30
Thanks. Let's close this issue.

**Closed by sciunto** 2020-03-12 06:30 UTC
Labels: action: monitor, type: bug
