### ISSUE TITLE
Memory error performing a binary_erosion

### ISSUE THREAD

**Issue by plooney** [scikit-image/scikit-image#954] opened 2014-03-22 20:47 UTC
Using the following image

http://ubuntuone.com/0unwk6BVwTn5q9zGJR54vq

It's a pickled numpy array. When I use values on the order of a few hundred I get a memory error

**Comment by jni** [comment] 2015-01-22 08:39
@plooney Could you post your test image somewhere?

**Comment by soupault** [comment] 2016-01-30 16:43
Ok. I guess this is the case...
I've taken random large image from the web (http://www.hawaiisummersalsafest.com/wp-content/uploads/2015/11/free-b.jpg (3750x5000x3)), then:

    import numpy as np
    import skimage
    from skimage import io, color, morphology

    img = io.imread('free-b.jpg')

    img_gray = skimage.color.rgb2gray(img)
    img_bin = img_gray.copy()
    img_bin[img_bin < 0.5] = 0
    img_bin[img_bin >= 0.5] = 1

    tmp = morphology.binary_erosion(img_bin, np.ones((300, 300), dtype=np.bool))

    ---------------------------------------------------------------------------
    MemoryError                               Traceback (most recent call last)
    <ipython-input-20-55b1b7efe510> in <module>()
    ----> 1 tmp = morphology.binary_erosion(img_bin, np.ones((300, 300)))

    /usr/lib/python3.5/site-packages/skimage/morphology/misc.py in func_out(image, selem, *args, **kwargs)
    35         if selem is None:
    36             selem = _default_selem(image.ndim)
    ---> 37         return func(image, selem=selem, *args, **kwargs)
    38 
    39     return func_out

    /usr/lib/python3.5/site-packages/skimage/morphology/binary.py in binary_erosion(image, selem, out)
    40     if out is None:
    41         out = np.empty(image.shape, dtype=np.bool)
    ---> 42     nd.binary_erosion(image, structure=selem, output=out)
    43     return out
    44 

    /usr/lib/python3.5/site-packages/scipy/ndimage/morphology.py in binary_erosion(input, structure, iterations, mask, output, border_value, origin, brute_force)
    373     """
        374     return _binary_erosion(input, structure, iterations, mask,
    --> 375                            output, border_value, origin, 0, brute_force)
        376 
        377 

    /usr/lib/python3.5/site-packages/scipy/ndimage/morphology.py in _binary_erosion(input, structure, iterations, mask, output, border_value, origin, invert, brute_force)
        244     if iterations == 1:
        245         _nd_image.binary_erosion(input, structure, mask, output,
    --> 246                                      border_value, origin, invert, cit, 0)
        247         return return_value
        248     elif cit and not brute_force:

    MemoryError: 

I suppose, the erosion kernel is too large.

I'd suggest to close the issue and discuss this behaviour with `numpy`/`scipy` devs.

**Comment by soupault** [comment] 2016-04-06 20:30
@ev-br Hi! Do you think if it is worth reporting to `scipy`?

**Comment by ev-br** [comment] 2016-04-07 11:07
Reporting it on the scipy tracker does no harm, I suppose. The blocker would be that someone actually looks into the `ndimage` sources and comes up with a fix. Is that you maybe? :-)

**Comment by soupault** [comment] 2016-04-07 15:21
Closing as __not a bug of `skimage`__.
For further discussion and proposals, please, use https://github.com/scipy/scipy/issues/6042 and https://github.com/scipy/scipy/issues/4878 .

**Closed by soupault** 2016-04-07 15:21 UTC
Labels: bug
