### ISSUE TITLE
Object has no attribute 'rgb2yiq' on Anaconda/Python 2.7

### ISSUE THREAD

**Issue by pankap** [scikit-image/scikit-image#2359] opened 2016-10-29 19:20 UTC
Hello and thanks for your great work. Here is the issue:

DESCRIPTION
Could not find the method rgb2yiq, when using scikit-image 0.12.3 inside an Anacoda/Python 2.7 environment on Windows 8.1 x64.

STEPS TO REPRODUCE
- Install Anaconda2-4.2.0-Windows-x86_64 (Python 2.7)
- Create a virtual environment and activate
- conda install scikit-image
- Python code: 

from skimage import color
from scipy import misc
img = misc.imread('SomeImage.jpg')
img_yiq=color.rgb2yiq(img)

AttributeError: 'module' object has no attribute 'rgb2yiq'

**Comment by soupault** [comment] 2016-10-29 21:00
@pankap thank you for your kind words! :)
YIQ colorspace convertion routines had been in in https://github.com/scikit-image/scikit-image/pull/2060 after the release of _0.12.3_. Therefore, at the moment, they are available in _0.13/dev_ version only.

Closing the issue as not a bug.

**Closed by soupault** 2016-10-29 21:00 UTC
