### ISSUE TITLE
Segfault in denoise bilateral

### ISSUE THREAD

**Issue by tsmithe** [scikit-image/scikit-image#1434] opened 2015-03-18 12:02 UTC
This fault occurs quite regularly, though I don't know what triggers it, using 0.11.2 and also git master. The backtrace goes as follows, but it's not particularly clear (at least to me), and I don't know how to build skimage with debugging information. But if there's anything I can do to help, please let me know, since my code rather depends on this segfault not happening!

```
#0  __pyx_pf_7skimage_11restoration_11_denoise_cy__denoise_bilateral (
    __pyx_v_image=0x7fffaf88acb0, __pyx_v_image@entry=0x7fffaf88a710, 
    __pyx_v_win_size=__pyx_v_win_size@entry=5, 
    __pyx_v_sigma_range=__pyx_v_sigma_range@entry=0x7ffff7f43ed0, 
    __pyx_v_sigma_spatial=__pyx_v_sigma_spatial@entry=3, 
    __pyx_v_bins=__pyx_v_bins@entry=10000, 
    __pyx_v_mode=__pyx_v_mode@entry=0x7ffff28c4970, __pyx_v_cval=<optimised out>, 
    __pyx_self=<optimised out>) at skimage/restoration/_denoise_cy.c:3061
#1  0x00007fffb29f3728 in __pyx_pw_7skimage_11restoration_11_denoise_cy_1_denoise_bilateral (__pyx_self=<optimised out>, __pyx_args=<optimised out>, 
    __pyx_kwds=<optimised out>) at skimage/restoration/_denoise_cy.c:2243
```

**Comment by tsmithe** [comment] 2015-03-18 12:07
In fact, I can isolate the failure to some combination like this:

```
frame = skimage.restoration.denoise_bilateral(frame, sigma_range=0.2, sigma_spatial=3)
frame = skimage.restoration.denoise_tv_chambolle(frame, weight=0.5, eps=1e-5, n_iter_max=500)
frame = skimage.restoration.denoise_bilateral(frame, sigma_range=0.2, sigma_spatial=3)
```

**Comment by tsmithe** [comment] 2015-03-18 12:07
(If I comment out the third line, the segfault goes away)

**Comment by tsmithe** [comment] 2015-03-18 12:15
My best guess is that at some point, the filter produces an invalid value, so I get a message like:

```
RuntimeWarning: invalid value encountered in less
  frame[frame<drop_level] = 0
```

Then, when I pass the array into the filter again, I get this segfault. If this hypothesis is true, then why is there an invalid value being produced, and why does it then cause a segfault?

**Comment by tsmithe** [comment] 2015-03-18 13:14
Yes, sometimes, some values of the array returned by denoise_bilateral are nan. What causes this, and what can I do about it? (I also feel that skimage should warn about it, and not fail so badly if nans are provided!)

**Comment by tsmithe** [comment] 2015-03-25 16:48
Hi -- has anyone got any ideas about this?

**Comment by jni** [comment] 2015-03-26 00:40
@tsmithe sorry about the silence! I actually have no idea about this, I'm hoping someone else in the team familiar with `denoise_bilateral` is able to figure this out. @ahojnnes? I certainly agree that nans shouldn't cause segfaults. =)

Incidentally, if indexing by a nan causes segfaulting (it would if we turn off bounds checks, which we do in many Cython functions), this may also be the cause of #1448 and #1390...

**Comment by JDWarner** [comment] 2015-03-26 00:59
I'm not sure this is an indexing issue in the function. That warning is a symptom, not the cause - it's getting passed _after_ nans are already present. The only way to trigger this error would be a call of the form `test[test < np.sqrt(-1)] = 0` or `test[test < np.nan] = 0` which does throw the error, but does NOT change any values of `test` to nan.

I'm not sure if that helps the investigation much. In any case, the fact that we're returning nans from a denoise function is broken...

**Comment by bewithaman** [comment] 2015-04-03 15:12
@tsmithe If you can give a test case to reproduce segfault, that would be helpful in debugging.

**Comment by fhs** [comment] 2015-04-03 17:29
Here's a reproducible segfault:
```
In [1]: from skimage.restoration import denoise_bilateral

In [2]: a = np.NaN + np.empty((500,500))

In [3]: denoise_bilateral(a)
Segmentation fault
```

**Comment by bewithaman** [comment] 2015-04-03 20:00
@fhs The function returned NaN's everywhere but I didn't got segfault. 
>>> skimage.__version__
'0.12dev'
>>> np.__version__
'1.8.2'

**Comment by fhs** [comment] 2015-04-03 20:18
@bewithaman I'm using skimage 0.12dev, numpy 1.9.2, python 2.7.9 and 3.4.3 on linux

**Comment by emmanuelle** [comment] 2015-05-09 09:51
I also get the segfault! Here is gdb's output

```
Program received signal SIGSEGV, Segmentation fault.
__pyx_pf_7skimage_11restoration_11_denoise_cy__denoise_bilateral (
    __pyx_v_image=<optimized out>, __pyx_v_image@entry=0x11d4e60, 
    __pyx_v_win_size=__pyx_v_win_size@entry=5, 
    __pyx_v_sigma_range=__pyx_v_sigma_range@entry=0x920190 <_Py_NoneStruct>, 
    __pyx_v_sigma_spatial=<optimized out>, 
    __pyx_v_bins=__pyx_v_bins@entry=10000, 
    __pyx_v_mode=__pyx_v_mode@entry=0x7ffff3e79e70, 
    __pyx_v_cval=<optimized out>, __pyx_self=<optimized out>)
    at skimage/restoration/_denoise_cy.c:3099
3099	          __pyx_v_weight = (__pyx_v_range_weight * __pyx_v_color_weight);

```

So I guess it's this line https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_denoise_cy.pyx#L131 that causes the segfault.

I'm also running python 2.7.

**Comment by stefanv** [comment] 2015-05-09 23:21
@emmanuelle I see the same thing, but I find that strange--why would it segfault on a double * double operation?

**Comment by ahojnnes** [comment] 2015-05-10 03:11
I suspect it’s something on this line: https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_denoise_cy.pyx#L129 <https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_denoise_cy.pyx#L129>

E.g. out of range values in the image, precision issue, etc.

**Comment by syedTabish** [comment] 2015-05-10 07:54
I guess the issue is in line https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_denoise_cy.pyx#L85.
from scipy doumentation of max  "NaN values are propagated, that is if at least one item is NaN, the corresponding max value will be NaN as well. To ignore NaN values (MATLAB behavior), please use nanmax."  replacing max by nanmax should resolve the issue

**Comment by stefanv** [comment] 2015-05-10 08:45
@ahojnnes That would make sense!

**Comment by ahojnnes** [comment] 2015-05-10 18:10
Should be fixed in #1504

**Comment by stefanv** [comment] 2015-05-10 23:11
Closed by #1504.

**Closed by stefanv** 2015-05-10 23:11 UTC

**Comment by dluzenst** [comment] 2015-09-29 14:47
@tsmithe "Yes, sometimes, some values of the array returned by denoise_bilateral are nan."

I am encountering this same issue. Applying np.nanmax instead of max to the result of denoise_bilateral seems to solve the problem, but perhaps the issue should be fixed in denoise_bilateral not to return nans?

I'm using :
scikit-image 0.11.3
numpy 1.9.3
python 2.7
spyder 2.3.6

Thanks!

**Comment by stefanv** [comment] 2015-09-30 05:13
@dluzenst Please open a new ticket with a minimal code snippet that reproduces your problem.

**Comment by JDWarner** [comment] 2015-09-30 05:45
@dluzenst, @stefanv - I believe the fix is in master but not shipped in a major version yet. @dluzenst is using 0.11.3. Before raising a new Issue, consider building from source which should fix the problem.

**Comment by stefanv** [comment] 2015-09-30 07:34
We should probably tag a new release.

**Comment by dluzenst** [comment] 2015-10-01 10:45
Thanks @stefanv @JDWarner!

Doing denoise_bilateral on the *same image* array returns "denoised" which *sometimes* contains nans. Then applying reconstruction causes python to segfault:

denoised = denoise_bilateral(image, sigma_range=1, sigma_spatial=15)
seed = np.copy(denoised)
seed[1:-1, 1:-1] = denoised.max()
filled = reconstruction(seed, denoised, method='erosion')

The workaround is to use:
    seed[1:-1, 1:-1] = np.nanmax(denoised)
