### ISSUE TITLE
Web gallery examples are by default showing dev version instead of 0.12.x

### ISSUE THREAD

**Issue by franktoffel** [scikit-image/scikit-image#2365] opened 2016-11-01 18:47 UTC
I don't know if this is on purpose, but the web gallery and documentation show by default the _dev_ version instead of the last stable release (_0.12.x_)

For example:
1. Start in http://scikit-image.org/ 
2. Click on gallery (menu)
3. Goes to: http://scikit-image.org/docs/dev/auto_examples/

I think this might be confusing for new users (like myself) and could be frustrating at the beginning.
See #2363 as an example

**Comment by soupault** [comment] 2016-11-01 19:43
@franktoffel actually, yes, it is by design. See the discussion in https://github.com/scikit-image/scikit-image-web/issues/22, https://github.com/scikit-image/scikit-image-web/issues/40.
/cc @stefanv

**Comment by soupault** [comment] 2016-12-25 21:36
I'm closing this as the current decision favours showing the `dev` version.
Please, follow the issues mentioned above.

**Closed by soupault** 2016-12-25 21:36 UTC
Labels: documentation
