### ISSUE TITLE
Rotate Accepts in range [0,128) and returns in range [0, 1.0]

### ISSUE THREAD

**Issue by N-McA** [scikit-image/scikit-image#2733] opened 2017-07-25 10:54 UTC
## Description
Rotate accepts input with RGB bytes and silently transforms it into floats in the range [0, 1].
I think either:
  Rotate and other transform methods that accept byte range values should warn when doing so, because the output format is changed.
Or
  Rotate and other transform methods that accept byte range values should return in the same format as the input.

If you guys can confirm which of these behaviors is preferred, or why the silent change is a feature and not a bug then I can either submit a pull request or go away.

```
from skimage.transform import rotate
import numpy as np

img = np.random.uniform(size=(10, 10)) * 128
img = img.astype('byte')
print(np.mean(img))
>> 68.8

img = rotate(img, 30)
print(np.mean(img))
>> 0.47
```

- [x] Python 3.5
- [x] skimage 0.13.0

**Comment by soupault** [comment] 2017-07-25 14:14
@N-McA most of the functions in `skimage` return or silently convert to&from float representation. This is an intended behaviour, and is preferred in order to produce accurate results. You can read more on this in http://scikit-image.org/docs/stable/user_guide/data_types.html .
`skimage` doesn't perform a lot of checks on inputs (otherwise, it would make many functions unreasonably slow (thanks to Python)), but there is an initiative to make things more trackable and explicit. Feel free to join the discussion in https://github.com/scikit-image/scikit-image/issues/2605 .
Closing for now.

**Closed by soupault** 2017-07-25 14:14 UTC

**Comment by soupault** [comment] 2017-07-25 14:16
P.S. In your case, you probably should also specify `preserve_range=True`.
