### ISSUE TITLE
 2022's calendar of community management

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#6165] opened 2022-01-06 21:27 UTC
This is our 2022's calendar of community management.

Here we set up a rotating duty to take a first look at all contributions (PRs and issues) from the community, label them and ping relevant reviewers.

Scripts for generating the reports are available [in this repository](https://github.com/scikit-image/boilerplate-utils).

Last year's calendar of community management is given at  #5604.

## jan/2022

* Week 1: @alexdesiqueira
* Week 2:
* Week 3: @mkcor
* Week 4: 
* Week 5: @alexdesiqueira

## feb/2022

* Week 6:
* Week 7:
* Week 8: @mkcor
* Week 9:

## mar/2022

* Week 10:
* Week 11:
* Week 12: 
* Week 13: @alexdesiqueira

## apr/2022

* Week 14:
* Week 15:
* Week 16:
* Week 17:

## may/2022

* Week 18:
* Week 19:
* Week 20:
* Week 21:
* Week 22:

## jun/2022

* Week 23:
* Week 24:
* Week 25:
* Week 26:

## jul/2022

* Week 27:
* Week 28:
* Week 29:
* Week 30:

## aug/2022

* Week 31:
* Week 32:
* Week 33: @lagru
* Week 34: @lagru
* Week 35: @alexdesiqueira

## sep/2022

* Week 36: @alexdesiqueira
* Week 37: @mkcor 
* Week 38: @lagru
* Week 39:

## oct/2022

* Week 40:
* Week 41:
* Week 42:
* Week 43:

## nov/2022

* **Week 44:**
* **Week 45:**
* **Week 46:**
* **Week 47:**
* **Week 48:**

## dec/2022

* **Week 49:**
* **Week 50:**
* **Week 51:**
* **Week 52:**

**Comment by rfezzani** [comment] 2022-01-06 23:11
Sorry @alexdesiqueira, I forgot to push the `Comment` boutton :facepalm:: I converted this issue to a Discussion as we want to keep Issues for proper bug reports :wink:

**Comment by alexdesiqueira** [comment] 2022-01-06 23:13
@rfezzani please see #6167 Riadh :slightly_smiling_face:

**Comment by mkcor** [comment] 2022-01-24 14:37
# 2022/1/17 - 2022/1/24

Hi, we are off to a great start of 2022, maybe resuming (monthly) community calls?! This conversation is happening on the [live chat](https://skimage.zulipchat.com/). Perhaps the other main topical conversations to have these days are on: a fix for stacklevel in deprecation warnings (#6183), an API decision (#5359), and a discussion about 'discussions' (#6167).

## New pull requests open last week

#6204 Changing occurrences of "neighbour" to EN-US spelling, "neighbor"
#6203 DOC: Minor cosmetic fixup to address UserWarning.
#6201 Removing references to git connection protocol
#6200 Improve writing for perimeter estimation example.
#6195 Adding CITATION.bib
#6193 Backport PR #6191 on branch v0.19.x (Fix issue6190 - inconsistent default parameters in pyramids.py)
#6191 Fix issue6190 - inconsistent default parameters in pyramids.py
#6189 added colocalization metrics
#6188 Avoid redundant computations during central moments calculation


## Closed pull requests (not merged)

#6146 allow to compute euler number along axis


## Merged pull requests

#6203 DOC: Minor cosmetic fixup to address UserWarning.
#6201 Removing references to git connection protocol
#6200 Improve writing for perimeter estimation example.
#6195 Adding CITATION.bib
#6193 Backport PR #6191 on branch v0.19.x (Fix issue6190 - inconsistent default parameters in pyramids.py)
#6191 Fix issue6190 - inconsistent default parameters in pyramids.py


## Older pull requests with new comments or commits

#6138 Allow variable stacklevel for deprecation warnings.
#6134 clarify the meaning of the weights term for TV denoising functions


## New issues

#6206 Propagate AffineTransform estimate return value in PiecewiseAffineTransform
#6205 Consistent ProjectiveTransform params value when estimate fails
#6202 Parameter name 'neighbourhood' uses non-US spelling.
#6199 Confusing example on perimeter measurements
#6196 Histogram matching looks broken
#6194 General help on the usage of restoration.richardson_lucy
#6192 Import cython module from skimage
#6190 Inconsistent default parameters for pyramid_reduce


## Older issues updated last week

#6187 hough_line_peaks() returning incorrect angle and distance arrays for certain line detections
#6165  2022's calendar of community management
#6104 roundtrip hed -> rgb -> hed is broken
#4078 morphology.reconstruction crashes python
#2429 2D image warping via thin-plate splines


## Closed issues

#6199 Confusing example on perimeter measurements
#6196 Histogram matching looks broken
#6194 General help on the usage of restoration.richardson_lucy
#6190 Inconsistent default parameters for pyramid_reduce
#6180 GitHub Deprecating git://, doc should be updated.

**Comment by mkcor** [comment] 2022-02-28 17:25
# 2022/2/21 - 2022/2/28

Hi, over the past week @grlee77 made some progress on issue triage, following the collective decision to deactivate GitHub Discussions (#6167). The major discussion to have now is about the branching strategy, as we release scikit-image v1.0 and now develop `skimage2` (#6262). This past week also, we were delighted to welcome first-time contributor @elena-pascal! :heart: Her PR #6265 is only a second core dev approval away from being merged! :tada:  


## New pull requests open last week

#6265 Fix balance in example code
#6263 Fix inpaint_biharmonic for images with Fortran-ordered memory layout
#6261 Ignore sparse matrix deprecation warning
#6258 Unify API on seed keyword for random seeds / generator


## Closed pull requests (not merged)

#6256 Update for NetworkX 2.7


## Merged pull requests

#6263 Fix inpaint_biharmonic for images with Fortran-ordered memory layout
#6261 Ignore sparse matrix deprecation warning
#6257 implement nD skimage.filters.farid (Farid & Simoncelli filter)


## Older pull requests with new comments or commits

#6255 Update skimage mailing addresses
#6171 add SUPPORT.md (helps point users from GitHub to appropriate support resources)
#6033 Add example of creating tools using HoloViz Panel and HoloViews
#5490 Update thresholding.py with Singh function 
#5349 Implement Fisher vectors in scikit-image
#5332 Threshold generalized histogram
#5323 Lddmm registration
#5301 Support variable number of channels in rag_mean_color
#5263 Add ellipsoid_coords function
#5226 Rectangle class for object-detection with bounding-boxes
#5026 Deconvolution with Gauss Prior
#4853 WIP: Add a boundary tracing algorithm
#4847 [WIP] Adding @eldad-a's ridge directed ring detector
#4734 Add Phansalkar local threshold algorithm
#4177 Line integral convolution
#4165 Add function to remove near objects in nd-image
#4121 Crofton perimeter and Euler number


## New issues

#6268 I have an image and I have generated contours for it using matplotlib.pyplot.contour. How do I save the part of the image within each contour as an individual image file?
#6267 skimage.viewer: _cascade module not found
#6266 warp returns all-NaN for cval=NaN and order>1
#6264 Bug in estimate_transform for ttype=piecewise_affine
#6262 repo branching for skimage 1.0, skimage2
#6260 Inpaint biharmonic with 3d image now fails
#6259 `skimage.graph.central_pixel` should be sped up


## Older issues updated last week

#6228 Implement Stroke Width Transform
#6167 Deactivate Github Discussions
#5501 label2rgb raises a wrong message when inputs are 3D
#5263 Add ellipsoid_coords function
#5226 Rectangle class for object-detection with bounding-boxes
#5112 Feature request: add voxel spacing to skimage.measure.regionprops
#5092 issue: centroid property of skimage.measure.regionprops is outside of regions
#5026 Deconvolution with Gauss Prior
#4988 Add link to API in website homepage
#4979 TypeError: unexpected keyword argument: img_num
#4975 Faster SLIC implementation
#4944 measure.regionprop fails to fill a circle, `filled_area` is wrong
#4940 Add a way to drop rows / columns of un-dividable 2D arrays using 'block_reduce'
#4915 rgb2gray should work on gray image
#4894 Algorithm to remove padding / find largest valid sub-image given a mask
#4876 Terminology: n_jobs vs num_workers vs ncpu etc.
#4869 `image` description in docstring: towards uniformity?
#4866 Speed up morphology.convex_hull_object using ndimage.bounding_box
#4858 Proposal: new feature for morphology.skeletonize
#4855 Proposal: speed up regionprops region finding
#4853 WIP: Add a boundary tracing algorithm
#4847 [WIP] Adding @eldad-a's ridge directed ring detector
#4832 Future of graph cuts
#4829 equalize_adapthist rescales intensities based on global min/max
#4824 Distance-based discrete interpolation in affine transformation
#4734 Add Phansalkar local threshold algorithm
#4177 Line integral convolution
#4165 Add function to remove near objects in nd-image
#4121 Crofton perimeter and Euler number
#3982 Alpha root filtering: new feature suggestion.
#3776 Image quality measure
#3590 WIP   NEW histogram backprojection
#3544 Affine Image Registration
#3531 Blue noise sampling
#3133 [WIP] First version of check_parallel function
#3057 New feature: convert bayer to rgb images
#2915 Color spaces C1C2C3 and MAXRGB added.
#2642 Add unsharp mask feature and gallery example
#2443 add threshold Wolf Phansalskar
#2429 2D image warping via thin-plate splines
#2411 Add histogram mapper to exposure module.
#2300 Add scattering transform
#2299 Implemented Kadir and Brady's Saliency detection
#2278 Add coordinate convertion routines to `skimage.util`
#2152 Add morlet filters
#2002 Polygon approximation
#1829 Kahan summation
#1557 Seeds segmentation
#1539 High Dynamic Range (HDR) imaging
#1425 Add steerable pyramid decomposition
#1414 Add hessian-laplace detector
#1104 Guided filter
#931 Add scanline algorithm for drawing polygons
#921 Shape contexts
#680 Phase unwrapping: Branch cut algorithm
#670 Texture synthesis implementation of Efros and Leung's algorithm


## Closed issues

#6268 I have an image and I have generated contours for it using matplotlib.pyplot.contour. How do I save the part of the image within each contour as an individual image file?
#6260 Inpaint biharmonic with 3d image now fails
#6226 Incorrect center normal calculated in marching_cubes_lewiner
#6104 roundtrip hed -> rgb -> hed is broken
#5089 filters.farid should be generalised to n-dimensions
#5019 MemoryError in computing Convex Hull of a large 3D image

**Comment by lagru** [comment] 2022-08-21 20:27
# 2022/8/14 - 2022/8/21

Hey, picking this up after these weekly updates have been dormant for a while. This week, we had three first-time contributors in #6472, #6470 and #6469. Welcome @lucas-johnson, @a-parida12, @cgusb! We've reached a (silent consensus) on how to document array-shapes in our docstrings (#2276 and #3031). Also there has been a discussion on our forum (https://discuss.scientific-python.org/t/405) on our more or less implicit rules for including new functionality prompted by this very cool new suggestion for our library #6462 (also first-time contribution from last week @fercer, welcome!). 

## New pull requests open last week

#6480 changed image1 to moving_image in tvl1 parameter docs
#6478 Update Ubuntu LTS version on Actions workflows
#6476 Use broadcast_to instead of as_strided to generate broadcasted arrays.
#6474 Fix broken link to skimage.filters.sobel.
#6472 Add `alpha` argument to `adapted_rand_error` 
#6470 Add multiscale structural similarity
#6469 Add solidification demo


## Closed pull requests (not merged)

none


## Merged pull requests

#6480 changed image1 to moving_image in tvl1 parameter docs
#6474 Fix broken link to skimage.filters.sobel.


## Older pull requests with new comments or commits

#6462 Add division of self overlapping polygons
#6460 Handle pending changes to `tifffile` defaults and avoid test warnings
#6458 Refactor occurences of `f = open(...)` using `with open(...) as f` instead
#6446 Rewrite the meijering, sato, and frangi ridge filters.
#6435 Use `lazy.attach_stub` for lazy imports, to accommodate type checkers and IDEs
#6429 add TYPE_CHECKING hints for lazy imports in data and filters


## New issues

#6479 `DocTestFailure` on `skimage.measure.fit.ransac`
#6477 rag_boundary depends on label ordering 
#6475 Shortest path routing in maritime raster
#6473 Time-series support for RAGs and hierarchical merging 
#6471 morphology.remove_small_objects do not worked as expect
#6468 Work array size computation failed for skimage 0.19.3 and scipy 1.8.1 on riscv64 (Debian)


## Older issues updated last week

#6456 phase_cross_correlation is no more correct in 0.19.3 (instead of 0.18.1)
#6451 One of hessian_matrix(use_gaussian_derivative=True/False) seems to be off by a factor of 2
#6165  2022's calendar of community management
#5194 Feature request: MS-SSIM calculation support in skimage.metrics
#5036 Discussion: deprecating (most of) skimage.io in favour of imageio
#3031 Use `plane, row, col` notation in all docstrings
#2616 WIP: document our guidelines/coding conventions
#2276 Use `plane, row, col` dimensions ordering as specified in the `skimage` conventions page
#904 Generalized distance transform.


## Closed issues

#6471 morphology.remove_small_objects do not worked as expect
#6466 Sigma value(s) for wavelet denoising
#6437 Multi Scale Structural Similarity Index

**Comment by lagru** [comment] 2022-08-28 21:29
# 2022/8/21 - 2022/8/28

This week we merged a good number of maintenance-focused PRs. We welcome @moi90 with a first-time contribution in #6492 that adds isotropic morpholocial operators. Everyone, please drop by in #6491 whether you see this as a good fit for our library! You might also be interested in our discussion on [Managing dormant pull requests in scikit-image](https://discuss.scientific-python.org/t/managing-dormant-pull-requests-in-scikit-image/442). And finally, @emmanuelle and me are giving a [tutorial](https://github.com/scikit-image/skimage-tutorials) next Tuesday at the EuroSciPy 2022.

## New pull requests open last week

#6493 Handle 2D labels in 3D images for convex hull calculation
#6492 Implement isotropic versions of binary morphologic operators
#6490 Use pyplot.get_cmap for compatiblity with matplotlib 3.3 to 3.6 in in show_rag
#6489 Radon/iradon: rotation center re-definition & user definition support
#6488 Document inclusion criteria for new functionality in core developer guide
#6487 Add multiscale structural similarity
#6484 Use context manager when possible
#6483 Use matplotlib.colormaps instead of deprecated cm.get_cmap in show_rag
#6481 Test nx 2.8.6 w/ mpl 3.6rc1


## Closed pull requests (not merged)

#6481 Test nx 2.8.6 w/ mpl 3.6rc1


## Merged pull requests

#6490 Use pyplot.get_cmap for compatiblity with matplotlib 3.3 to 3.6 in in show_rag
#6484 Use context manager when possible
#6483 Use matplotlib.colormaps instead of deprecated cm.get_cmap in show_rag
#6476 Use broadcast_to instead of as_strided to generate broadcasted arrays.
#6470 Add multiscale structural similarity
#6458 Refactor occurences of `f = open(...)` using `with open(...) as f` instead
#6453 No valueerror for underdetermined
#6272 add warning on non-integer image inputs to local_binary_pattern


## Older pull requests with new comments or commits

#6478 Update Ubuntu LTS version on Actions workflows
#6472 Add `alpha` argument to `adapted_rand_error`
#6469 Add solidification demo
#6462 Add division of self overlapping polygons
#6134 clarify the meaning of the weights term for TV denoising functions


## New issues

#6494 Unable to install conda environment for development
#6491 Isotropic versions of binary_dilation and binary_erosion
#6486 Address new matplotlib >= 3.5 dependency in skimage.future.graph.rag.show_rag
#6485 Are precision and recall results reversed in adapted_rand_error()?
#6482 PendingDeprecationWarning with Matplotlib 3.6rc1


## Older issues updated last week

#6475 Shortest path routing in maritime raster
#6473 Time-series support for RAGs and hierarchical merging
#6467 Nearest neighbor resize of integer array changes the unique integer values
#6311 broken CircleCI documentation artifact links
#6165  2022's calendar of community management
#4095 Regionprops memory usage
#3344 speedup label2rgb using scipy
#3120 Trying to accelerate slic


## Closed issues

#6486 Address new matplotlib >= 3.5 dependency in skimage.future.graph.rag.show_rag
#6482 PendingDeprecationWarning with Matplotlib 3.6rc1
#6452 Return False from LineModelND and CircleModel when inputs are underdetermined
#5060 pip install fails under Python 3.9 if numpy isn't already installed
#2563 Warning in local binary pattern if image dtype is not integer
#2522 Unexpected behavior of skimage.feature.local_binary_pattern

**Comment by mkcor** [comment] 2022-09-19 11:43
# 2022/9/11 - 2022/9/18

Hi, most issues opened last week were resolved promptly; Python 3.11 wheels (#6517) are coming up: On this occasion, a few @scikit-image/core members will meet next week, so that @grlee77 can pass on key knowledge about our release process (see #6519 also). A nice enhancement submitted by @dudulasry should be landing very soon: Fixing a bug while adding flexibility for the end-user, it's about finding the grid points inside of a polygon (#6515). The long-form gallery example initiated by @cgusb should be ready for review very shortly (#6469): This analysis of the solidification velocity of a metallic alloy sample resorts to several image processing techniques applied in various ways (2D, nD).

## New pull requests open last week

#6531 change the max value of poisson noise input from 2 ** n to 2 ** n - 1
#6530 V0.19.x
#6529 update setup.cfg field from license_file to license_files
#6528 make non-functional change to build.txt to fix cache issue on CircleCI
#6526 Add upper bound to setuptools in pyproject.toml
#6525 Use mask during rescaling in segmentation.slic and improve handling of error cases
#6524 Update noise.py
#6522 update plot_euler_number.py for maplotlib 3.6 compatibility
#6520 relax label name comparison in benchmarks.yaml
#6519 Add Python 3.11 tests for linux and MacOS
#6516 add spacing to segmentation.expand_labels
#6515 Add new flag to convex_hull_image and grid_points_in_poly


## Closed pull requests (not merged)

#6530 V0.19.x
#6524 Update noise.py


## Merged pull requests

#6528 make non-functional change to build.txt to fix cache issue on CircleCI
#6522 update plot_euler_number.py for maplotlib 3.6 compatibility
#6520 relax label name comparison in benchmarks.yaml
#6446 Rewrite the meijering, sato, and frangi ridge filters.


## Older pull requests with new comments or commits

#6509 Reduce ridge filters memory footprints
#6506 Add Github actions/stale to label "dormant" issues and PRs
#6504 GitHub Workflows security hardening
#6500 JupyterLite in documenation
#6492 Implement isotropic versions of binary morphologic operators
#6487 Add multiscale structural similarity
#6469 Add solidification demo
#5387 add iterations option to binary morphology operations


## New issues

#6527 bad package cache in CircleCI
#6523 imread returns different shape on different computers for  the same image
#6521 matplotlib 3.6.0 compatibility
#6518 "run-benchmarks" label is triggering workflow which is then skipped
#6517 Python 3.11 wheels


## Older issues updated last week

#6513 skeletonize_3d produces zero array for cubes with certain shapes
#6512 skeletonize 3D with different voxel size
#6510 `convex_hull_image` returns different results between 0.18.0 and 0.19.3
#6491 Isotropic versions of binary_dilation and binary_erosion
#6436 Various issues with ridge filters.
#5387 add iterations option to binary morphology operations
#4883 skimage.segmentation.slic crashes when passed NaNs


## Closed issues

#6527 bad package cache in CircleCI
#6521 matplotlib 3.6.0 compatibility
#6518 "run-benchmarks" label is triggering workflow which is then skipped
#6514 Status of nightly wheels
#6311 broken CircleCI documentation artifact links
#4468 Added implementation of SSIM max/min algorithm from paper
#3255 Add benchmarks for morphology.local_maxima

**Comment by lagru** [comment] 2022-09-27 21:24
# 2022/9/19 - 2022/9/25

This week work has started on #6536 to see whether SciPy's Meson-based build system could be a good fit for our library; in that light please feel free to checkout #6540 for a general discussion on options as well as pros and cons! If you've got a bit of spare time, there are a few very small PRs just 1 approval away from merge: #6539, #6533, #6529, #6526, #6504. 

(I'm trying out coding the open / closed / merged state with an emoji to make it more apparent which issues and PRs might still be useful to look at.)

## New pull requests open last week
🙌 #6539 Ignore codespell fixes with git blame
🤝 #6537 Apply codespell to fix common spelling mistakes
🙌 #6536 Add Meson-based build
🤝 #6535 Minor doc fix: add missing print statement in the `plot_segmentations.py` example
🤝 #6534 Fix wrong doc on connected pixels in flood
🙌 #6533 fix exclude_border for the case of multidim input

## Closed pull requests (not merged)
none

## Merged pull requests
🤝 #6537 Apply codespell to fix common spelling mistakes
🤝 #6535 Minor doc fix: add missing print statement in the `plot_segmentations.py` example
🤝 #6534 Fix wrong doc on connected pixels in flood
🤝 #6525 Use mask during rescaling in segmentation.slic and improve handling of error cases
🤝 #6515 Add new flag to convex_hull_image and grid_points_in_poly
🤝 #6509 Reduce ridge filters memory footprints
🤝 #6508 Clarify header pointing to notes for latest version released.
🤝 #6506 Add Github actions/stale to label "dormant" issues and PRs

## Older pull requests with new comments or commits
🙌 #6531 change the max value of poisson noise input from 2 ** n to 2 ** n - 1
🙌 #6529 update setup.cfg field from license_file to license_files
🙌 #6526 Add upper bound to setuptools in pyproject.toml
🙌 #6519 Add Python 3.11 tests for linux and MacOS
🙌 #6516 add spacing to segmentation.expand_labels
🙌 #6504 GitHub Workflows security hardening
🙌 #6469 Add solidification demo
🙌 #6462 Add division of self overlapping polygons

## New issues
🙌 #6541 Duplicates in circle_perimeter_aa have different intensity values
🙌 #6540 Remove reliance of scikit-image on distutils
🙌 #6538 incorrect # of sign changes in  _local_binary_pattern of _texture.pyx

## Older issues updated last week
🙌 #6523 imread returns different shape on different computers for  the same image
🙌 #6517 Python 3.11 wheels
🙌 #6512 skeletonize 3D with different voxel size
🙌 #6499 line-profiling scikit-image functions profiles only the decorator function
🙌 #6485 Are precision and recall results reversed in adapted_rand_error()?
🙌 #6465 skimage.measure._regionprops.RegionProperties is not serializable. RecursionError is thrown from __getattr__
🙌 #6459 gaussian filter produces pixels outside valid range 
🙌 #6165  2022's calendar of community management
🙌 #5379 clarify the meaning of the weights term for TV denoising functions
🙌 #5161 Performance regression in peak_local_max in version 0.18.0
🙌 #4146 Remove duplicates from perimeter functions in draw module

## Closed issues
🤝 #6510 `convex_hull_image` returns different results between 0.18.0 and 0.19.3
🤝 #6507 Sato filter memory usage with multiple sigmas
🤝 #6464 skimage segmentation flood docs
🤝 #4883 skimage.segmentation.slic crashes when passed NaNs

**Closed** 2023-03-26 15:19 UTC
Labels: :wrench: Maintenance, :speech_balloon: Discussion
