### ISSUE TITLE
threshold_multiotsu fails for array with 0

### ISSUE THREAD

**Issue by callum-jpg** [scikit-image/scikit-image#6324] opened 2022-04-07 20:28 UTC
## Description
For the input array below with 3 classes, one of which being 0, threshold_multiotsu with nbins=128 returns the error `The input image has only 2 different values. It cannot be thresholded in 3 classes.` However, increasing nbins to 180 or changing `arr[0] = 0.1` avoids this error.

## Way to reproduce
```
arr = np.asarray([0.0, 0.12570100514093369, 0.0007003172065461084])
skimage.filters.threshold_multiotsu(arr, nbins=128)
>>> ValueError: The input image has only 2 different values. It cannot be thresholded in 3 classes.
```

```
arr = np.asarray([0.0, 0.12570100514093369, 0.0007003172065461084])
skimage.filters.threshold_multiotsu(arr, nbins=180)
>>> array([0.00034917, 0.00104751])
```

## Version information
```python
Python 3.8.13
scikit-image==0.19.1
numpy==1.22.0
```

**Comment by jni** [comment] 2022-04-08 03:27
Interesting, thanks for the report @callum-jpg! What's happening here is that the number of different values is being counted *after* discretisation into bins, which makes sense because the binned data is what will be used when computing the multi-threshold.

To be honest, I wonder whether we should just call this expected behaviour, as I don't see a nice way to fix this in the general case (e.g. a big image with only 3 different values as above, two of which are very close). Perhaps we can improve the error message to something like, "After discretization into bins, the image only has 2 values, which cannot be separated into 3 classes. If there are more unique values before discretization, try increasing the number of bins."

Another idea would be to return the same value for the two thresholds, but that might be surprising also...

**Comment by rfezzani** [comment] 2022-05-06 07:43
> To be honest, I wonder whether we should just call this expected behaviour, as I don't see a nice way to fix this in the general case (e.g. a big image with only 3 different values as above, two of which are very close). Perhaps we can improve the error message to something like, "After discretization into bins, the image only has 2 values, which cannot be separated into 3 classes. If there are more unique values before discretization, try increasing the number of bins."

I agree with @jni, improving the error message is a good solution :wink:

**Comment by grlee77** [comment] 2022-05-06 19:15
>  (because right now we're only using up to 3-class Otsu) 

Out of curiosity, would more than 3 classes be of use if it were faster? I have a PR that makes 4-6 classes much more computationally feasible than with the current code: https://github.com/scikit-image/scikit-image/pull/5198#issue-795197255. Even for the 3-class case it looks like it i about 2x faster.

**Comment by alexdesiqueira** [comment] 2022-05-06 19:19
> Out of curiosity, would more than 3 classes be of use if it were faster? I have a PR that makes 4-6 classes much more computationally feasible than with the current code: https://github.com/scikit-image/scikit-image/pull/5198#issue-795197255. Even for the 3-class case it looks like it is about 2x faster.

@grlee77 _yes!_ :exploding_head: Not sure how I missed that one!

**Comment by rsenft1** [comment] 2022-05-06 19:19
> Out of curiosity, would more than 3 classes be of use if it were faster?

More speed would be great! For CellProfiler, the reason we aren't already using >3 class segmentation isn't speed but more so how to explain this to users and build interface around it. Currently our 3 class Otsu segmentation is used for foreground/background segmentation with the middle class assigned to either foreground or background by the user. More classes would be great but also becomes a little harder to explain to users and teach them how to use it.

**Comment by alexdesiqueira** [comment] 2022-05-06 19:27
> More classes would be great but also becomes a little harder to explain to users and teach them how to use it.

@rsenft1 I think it would be nice to present use cases in our documentation. (self-promotion :wink:) I have an example [here](https://www.nature.com/articles/s41597-022-01119-6):
![image](https://user-images.githubusercontent.com/5776022/167204649-f5149f6d-689f-49fb-89fb-6372683a8643.png)

**Closed** 2022-05-24 11:45 UTC
Labels: :bug: Bug, :eyes: action: needs decision, :thinking: Planning
