### ISSUE TITLE
Older tophat function under filters.rank.tophat?

### ISSUE THREAD

**Issue by pratapvardhan** [scikit-image/scikit-image#1784] opened 2015-11-15 14:57 UTC
[`skimage.filters.rank.tophat`](http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#tophat) - This filter computes the morphological opening of the image and then subtracts the result from the original image.

There is another implementation under [morphology](http://scikit-image.org/docs/dev/api/skimage.morphology.html) as

[`skimage.morphology.white_tophat`](http://scikit-image.org/docs/dev/api/skimage.morphology.html#white-tophat) - The white top hat of an image is defined as the image minus its morphological opening.

So, [`skimage.filters.rank.tophat`](http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#tophat) seems redundent?

Also, output of [`skimage.filters.rank.tophat`](http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#tophat) seems incorrect

``` python
from skimage.morphology import (square,
                                erosion, dilation, opening, closing,
                                white_tophat, black_tophat)
from skimage.filters.rank import tophat
bright_on_grey = np.array([[2, 3, 3, 3, 2],
                           [3, 4, 5, 4, 3],
                           [3, 5, 9, 5, 3],
                           [3, 4, 5, 4, 3],
                           [2, 3, 3, 3, 2]], dtype=np.uint8)

white_tophat(bright_on_grey, square(3))
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 5, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

tophat(bright_on_grey, square(3))
array([[2, 2, 2, 2, 2],
       [2, 5, 4, 5, 2],
       [2, 4, 0, 4, 2],
       [2, 5, 4, 5, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)
```

`white_tophat` matches with the definition of  "image minus its morphological opening"

``` python
( white_tophat(bright_on_grey, square(3)) == 
  bright_on_grey - opening(bright_on_grey, square(3)) ).all()
True
```

So, I guess, [`skimage.filters.rank.tophat`](http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#tophat) is buggy/defunct and usable version is [`skimage.morphology.white_tophat`](http://scikit-image.org/docs/dev/api/skimage.morphology.html#white-tophat)?

**Comment by stefanv** [comment] 2015-12-10 19:33
Are you sure ``white_tophat`` is broken?  This function is just a wrapper around ndimage functionality.

**Comment by pratapvardhan** [comment] 2015-12-10 20:27
@stefanv -- I meant `skimage.morphology.white_tophat` is working fine. However, the one under `rank` module `skimage.filters.rank.tophat` seems to give different output than morphology one.

**Comment by emmanuelle** [comment] 2015-12-10 20:40
you're completely right @pratapvardhan 

``skimage.filters.rank.tophat`` does not produce the expected result. 

I tried to look at the source code but I find it pretty hard to read the code of  ``filters.rank``

**Comment by emmanuelle** [comment] 2015-12-10 20:46
Another example

```
>>> a = np.zeros((5, 5), dtype=np.uint8)
>>> a[2, 2] = 1
>>> a
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
>>> tophat(a, square(3))
array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
>>> white_tophat(a)
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
```

**Comment by emmanuelle** [comment] 2015-12-10 21:14
Hum, I suspect that this line causes the problem
https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/rank/generic_cy.pyx#L320


It seems that it's actually the black tophat that is computed (the closing minus the original image).

However, it looks like ``ndimage.black_tophat`` is also buggy... Even the example from the docstring makes no sense
```
>>> dark_on_grey = np.array([[7, 6, 6, 6, 7],
...                          [6, 5, 4, 5, 6],
...                          [6, 4, 0, 4, 6],
...                          [6, 5, 4, 5, 6],
...                          [7, 6, 6, 6, 7]], dtype=np.uint8)
>>> black_tophat(dark_on_grey, square(3))
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 5, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
```

**Comment by emmanuelle** [comment] 2015-12-23 10:58
So, it seems that the implementation of ``filters.rank`` is incorrect. I would be in favor of removing the code of ``filters.rank.generic_cy``, deprecate ``filters.rank.tophat`` and call ``morphology.white_tophat`` instead. 

``morphology.white_tophat`` does not have a ``mask`` keyword argument, however, so this would slightly change the API. 

How does that sound?

**Comment by jni** [comment] 2015-12-23 13:02
@emmanuelle I agree with your path. Depending on the expected behaviour of `mask`, it might be straightforward to implement a masked version. (Indeed, even an `add_mask_argument` decorator to all functions!)

**Comment by ahojnnes** [comment] 2015-12-23 21:03
Both functions have different performance characteristics. -1 on removing the filters.rank function, but fixing it, if that is easy?

**Comment by emmanuelle** [comment] 2015-12-23 21:05
@ahojnnes could you please elaborate a little more on the different performance characteristics?

**Comment by emmanuelle** [comment] 2015-12-23 21:13
I don't know if it's easy to fix: a morphological closing has to be computed, and I'm not sure whether it can be computed as a single kernel (a dilation is then needed, and then an erosion). A kernel could be written for the dilation and another one for the erosion, though.

**Comment by rfezzani** [comment] 2020-02-20 13:30
Closing since #4423 deprecates `filters.rank.tophat` ;-)

**Closed by rfezzani** 2020-02-20 13:30 UTC
Labels: type: bug
