### ISSUE TITLE
Cannot import skimage after updating scipy to 0.17.0 version

### ISSUE THREAD

**Issue by xrzhou** [scikit-image/scikit-image#2074] opened 2016-05-06 19:20 UTC
## Description
In order the active contour function of scikit-image, I've updated scipy to 0.17.0 version. Then skimage cannot be imported successfully.

Python version: 2.7.6
Anaconda version: Anaconda2-4.0.0
scikit-image version: 0.12.3
OS: Ubuntu 14.04

## Relevant images
When running `from skimage import ***`, I got the following messages:

![image](https://cloud.githubusercontent.com/assets/8560857/15083542/aec9ebdc-1382-11e6-968d-c309c96bcbec.png)

![image](https://cloud.githubusercontent.com/assets/8560857/15083634/2448e03e-1383-11e6-9035-9decf39bb911.png)

**Comment by soupault** [comment] 2016-05-06 19:31
@xrzhou hi!
This doesn't seem like a `skimage` issue atm.

What is the version of your `numpy`?
What is the result of these imports? :
```
import numpy
import scipy
```

**Comment by xrzhou** [comment] 2016-05-06 21:08
Hi,

Thanks for reply.

The version of numpy is 1.11.0.
numpy and scipy can work well.

On Fri, May 6, 2016 at 12:31 PM, Egor Panfilov <notifications@github.com>
wrote:

> @xrzhou <https://github.com/xrzhou> hi!
> This doesn't seem like a skimage issue atm.
>
> What is the version of your numpy?
> What is the result of these imports? :
>
> import numpy
> import scipy
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/2074#issuecomment-217538000>
>



-- 
Xiran Zhou
GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences & Urban Planning
Arizona State University

**Comment by stefanv** [comment] 2016-05-07 21:34
The error is related to another library: skimage does not link to MKL.

Please set up a new, clean virtual environment and let us know if that
fails as well.

**Comment by soupault** [comment] 2016-05-15 18:51
@xrzhou Hi, have you succeed to check the behaviour under a new virtual environment?

**Comment by xrzhou** [comment] 2016-05-20 21:09
Hi Egor,

Sorry for replying late. After several checks, I find the  0.17.0 version
scipy cannot work well in anaconda environment.

When I imported scipy.io, scipy.misc, and other scipy modules, the kernel
of anaconda had died. But, 0.17.0 version scipy works well under the other
environment like VIM, pycharm, and pyscript.

Thanks.

On Sun, May 15, 2016 at 11:51 AM, Egor Panfilov <notifications@github.com>
wrote:

> @xrzhou <https://github.com/xrzhou> Hi, have you succeed to check the
> behaviour under a new virtual environment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/2074#issuecomment-219303415>
>



-- 
Xiran Zhou
GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences & Urban Planning
Arizona State University

**Comment by stefanv** [comment] 2016-05-21 01:21
How did you install scipy?  You should probably use conda in a conda
environment.

**Comment by soupault** [comment] 2016-05-21 22:28
@xrzhou just to clarify, you are saying that there are some issues with `scipy` in `jupyter`, but for other import methods/IDEs everything works fine, is that correct?

**Comment by xrzhou** [comment] 2016-05-25 23:40
Yeah. I've tried on three operation systems. These issues of installing
scipy 0.17.0 in jupyter didn't happen on Windows, but Unbuntu 14.4 and Mac
OS X El Capitan.

On Sat, May 21, 2016 at 3:28 PM, Egor Panfilov <notifications@github.com>
wrote:

> @xrzhou <https://github.com/xrzhou> just to clarify, you are saying that
> there are some issues with scipy in jupyter, but for other import
> methods/IDEs everything works fine, is that correct?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/2074#issuecomment-220803674>
>



-- 
Xiran Zhou
GeoDa Center for Geospatial Analysis and Computation
School of Geographical Sciences & Urban Planning
Arizona State University

**Comment by soupault** [comment] 2016-06-11 19:13
@xrzhou Sorry, I cannot help you with this more. I suggest you to file an issue on `scipy` bugtracker and ask people there to better investigate it.
Closing as not a bug of `skimage`, reopen if disagree.

**Closed by soupault** 2016-06-11 19:13 UTC
