### ISSUE TITLE
How to reconstruct a Binary Image in Sci-kit image ?

### ISSUE THREAD

**Issue by qiujian3328103** [scikit-image/scikit-image#2667] opened 2017-05-22 18:33 UTC
![figure_1](https://cloud.githubusercontent.com/assets/4641425/26323117/e081b0ee-3eea-11e7-953d-bcd992678663.png)

How to reconstruct a binary image from the SEM
 I am recently working a measure the size of polymer from the SEM image. By using the python sic-kit image I convert the original image into a binary image. However, the problem that I cannot solve is that some withe pixels inside the polymer. Does anything one know is there any function in python that can convert the pixels inside the polymer to a black pixel ?

`import numpy as np
from matplotlib import pyplot as plt, cm
from skimage import io
from skimage import img_as_float
from skimage.color import rgb2gray
from skimage import filters

raw_img = io.imread('../PythonImageProcess/SEMimg.png')
img = rgb2gray(raw_img) # very import to convert the image to 2d gray image array
print('original image size', raw_img.shape)
print('original image data type ', raw_img.dtype)

from skimage.exposure import rescale_intensity
img2 = rescale_intensity(img, in_range=(0, 1))

seed = np.copy(img)
seed[1:-1, 1:-1] = img.max()
mask = img

from skimage.morphology import reconstruction
filled = reconstruction(seed, mask, method='erosion')`

The original figure and the 

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by qiujian3328103** [comment] 2017-05-24 18:52
Does anyone know how to deal the problem?

**Comment by foloumi** [comment] 2017-05-24 19:44
I believe the issue is that you're assigning the maximum image value to
your mask; this is still a gray-scale value. To get just back and white
pixels, you need to threshold your image.

Hope this helps,

**Comment by soupault** [comment] 2017-06-18 16:42
@qiujian3328103 I'd double @\foloumi - for your case is more efficient to use thresholding methods (we have a lot of them, see http://scikit-image.org/docs/dev/auto_examples/xx_applications/plot_thresholding.html) optionally followed by morphology operations (such as `closing` http://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.closing).

Closing this as not an issue, but feel free to continue discussion here or on StackOverflow (using tag `scikit-image`).

**Closed by soupault** 2017-06-18 16:42 UTC
