### ISSUE TITLE
`draw.polygon2mask()`: pixel coordinates rounded with ceil() introduces a bottom-left bias in rasterized polygon

### ISSUE THREAD

**Issue by kvos** [scikit-image/scikit-image#7271] opened 2023-12-18 02:46 UTC
### Description:

When using the `draw.polygon2mask()` function to rasterise a given polygon, the following happens:
- the pixel coordinates (row, column) are given with decimals in many cases where the pixel resolution is coarse
- the coordinates with decimals get rounded with ceil() in the function `draw._polygon()`
- this introduces a small offset towards the bottom left of an image, as the row coordinates and column coordinates are rounded to the next integer value. See image below rasterising a polygon on a 30m/pixel Landsat tile.
![capture](https://github.com/scikit-image/scikit-image/assets/7217258/f29f6574-8d0f-4596-97f1-f861a09b75db)

As a user of this function, I would like to have equal coverage of the polygon boundary around the edge, would it be possible to use `floor()` for the higher row and lower column and `ceil` for the lower row and higher column? 

Thanks,
Kilian

**Comment by jni** [comment] 2023-12-18 07:32
Hmmm... Following the code it doesn't look like the issue is a shifting of the polygon coordinates:

1. First, they get passed unchanged to `draw.polygon`:

https://github.com/scikit-image/scikit-image/blob/09577eddf2ce0376b25b96291599af313adb1c2d/skimage/draw/_polygon2mask.py#L69-L71

2. Then they get passed unchanged to the Cython function:

https://github.com/scikit-image/scikit-image/blob/09577eddf2ce0376b25b96291599af313adb1c2d/skimage/draw/draw.py#L518

3. Here, the ceil is only to define the maximum coordinate for iteration:

https://github.com/scikit-image/scikit-image/blob/09577eddf2ce0376b25b96291599af313adb1c2d/skimage/draw/_draw.pyx#L224-L227

The coordinates themselves are not modified with a ceil, they are passed directly as a pointer:

https://github.com/scikit-image/scikit-image/blob/09577eddf2ce0376b25b96291599af313adb1c2d/skimage/draw/_draw.pyx#L235-L236

4. Then, each coordinate within the bounding box of the polygon is checked for inclusion in the polygon:

https://github.com/scikit-image/scikit-image/blob/09577eddf2ce0376b25b96291599af313adb1c2d/skimage/draw/_draw.pyx#L245

5. In that function, the coordinates are checked for inclusion directly — there are no ceils, rounds, or +/-0.5s anywhere.

... Could you share the code that generates the figure above? My suspicion is that your display software shifts pixels by 0.5 relative to scikit-image — in (most) scikit-image functions, integers represent the pixel center (see [this white paper](http://alvyray.com/Memos/CG/Microsoft/6_pixel.pdf) for a justification), but in many other software packages, integers are at the corners of pixels, and the centers are at 0.5.

Therefore, the workaround is to add 0.5 to your polygon coordinates when displaying them, or, subtract 0.5 before passing them to scikit-image.

I don't think that this is an issue with scikit-image, so I'm going to close the issue, but feel free to continue discussing — the decision is reversible. 😊 I hope the above helps! 🙏

**Closed by jni** 2023-12-18 07:32 UTC
Labels: :pray: Feature request

**Comment by kvos** [comment] 2023-12-18 21:57
thanks @jni for looking into this and the detailed response, it helps a lot. I think that you spotted the issue, it must have to do with the definition of the coordinate system, center of pixel vs top-left corner of pixel, that would explain the bottom-left shit! 

So the convention for scikit-image is 'Pixel-is-Point' (center of pixel), and not 'Pixel-is-Area' ? I will make sure my .tif files have that convention before reading them and passing them through the scikit-image functions.

**Comment by jni** [comment] 2023-12-18 22:35
> So the convention for scikit-image is 'Pixel-is-Point' (center of pixel), and not 'Pixel-is-Area' ?

The answer is "yes, but." 😅 That is the convention we've had for a while, but skimage is an old-ish library (14+ yo), developed by hundreds of contributors, so in some places I think the "pixel-is-area" convention still exists. But if and where it does, it's now considered a bug to be fixed! 😊
