### ISSUE TITLE
skimage.color.gray2rgb error, possible bug?

### ISSUE THREAD

**Issue by austinmw** [scikit-image/scikit-image#3065] opened 2018-05-09 03:01 UTC
I'm running the code:

    import numpy as np
    from glob import glob
    import skimage.color
    import skimage.io
    import skimage.transform
    
    imgs = glob('/home/name/data/typeA_data/train2018/*')
    print(len(imgs))    

    for n,i in enumerate(imgs):
        print(n, i)
        image = skimage.io.imread(i)
        if image.ndim != 3:
            print("    WARNING, id:", i.split("/")[-1])
            print("    ndim:", image.ndim) # says 1
            print("    np.squeeze(image).ndim:", np.squeeze(image).ndim) # says 1
            image = skimage.color.gray2rgb(image) # else: raise ValueError("Input image expected to be RGB, RGBA or gray.")

I'm getting the ValueError when `np.squeeze(image).ndim` is equal to 1, but when I actually look at the `skimage.color.gray2rgb` code it shows that this condition should only happen if `np.squeeze(image).ndim` is not equal to 1,2, or 3?:

    def gray2rgb(image, alpha=None):
        """Create an RGB representation of a gray-level image.
        Parameters
        ----------
        image : array_like
            Input image of shape ``(M[, N][, P])``.
        alpha : bool, optional
            Ensure that the output image has an alpha layer.  If None,
            alpha layers are passed through but not created.
        Returns
        -------
        rgb : ndarray
            RGB image of shape ``(M[, N][, P], 3)``.
        Raises
        ------
        ValueError
            If the input is not a 1-, 2- or 3-dimensional image.
        Notes
        -----
        If the input is a 1-dimensional image of shape ``(M, )``, the output
        will be shape ``(M, 3)``.
        """
        is_rgb = False
        is_alpha = False
        dims = np.squeeze(image).ndim
    
        if dims == 3:
            if image.shape[2] == 3:
                is_rgb = True
            elif image.shape[2] == 4:
                is_alpha = True
                is_rgb = True
    
        if is_rgb:
            if alpha is False:
                image = image[..., :3]
    
            elif alpha is True and is_alpha is False:
                alpha_layer = (np.ones_like(image[..., 0, np.newaxis]) *
                               dtype_limits(image, clip_negative=False)[1])
                image = np.concatenate((image, alpha_layer), axis=2)
    
            return image
    
        elif dims in (1, 2, 3):
            image = image[..., np.newaxis]
    
            if alpha:
                alpha_layer = (np.ones_like(image) * dtype_limits(image, clip_negative=False)[1])
                return np.concatenate(3 * (image,) + (alpha_layer,), axis=-1)
            else:
                return np.concatenate(3 * (image,), axis=-1)
    
        else:
            raise ValueError("Input image expected to be RGB, RGBA or gray.")

So does anybody know why it's bypassing the `elif dims in (1, 2, 3):` line when my `np.squeeze(image).ndim` printout says `dims` is 1?

**Comment by austinmw** [comment] 2018-05-09 10:57
Another person discovered that it looks like this function cannot correctly output large grayscale images

**Comment by soupault** [comment] 2018-05-09 11:42
@austinmw could you share the image on which the error is raised?

**Comment by jni** [comment] 2018-05-09 13:09
@austinmw from my reading of the code, you're right that it should not be raising that ValueError. Can you share (a) the full traceback of the error, and (b) the image that actually causes the error to be raised? Without a reproducible example it is very hard to debug. If you can't share that specific image, see whether you can make a random image of the same characteristics.

**Comment by austinmw** [comment] 2018-05-09 22:28
I believe it happens with any very large grayscale images. I didn't save the traceback so when I get back to my machine I'll rerun and post the full traceback and an image.

**Comment by emmanuelle** [comment] 2018-12-15 15:42
I could not reproduce the issue, so I'm thinking about closing it. When I tried to open a very large (10000x10000) image I got a warning from PIL, but it is a sensible one and only warning, not an error. 
```
>>> a = np.random.randint(0, 256, size=(10000, 10000), dtype=np.uint8)          
>>> io.imsave('tmp.png', a)                                                     
>>> img = io.imread('tmp.png')                                                  
/home/emma/.local/lib/python3.6/site-packages/PIL/Image.py:2575: DecompressionBombWarning: Image size (100000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning)
```

**Comment by sciunto** [comment] 2019-02-01 07:08
@austinmw Can you provide more information please? (like an image?)

Thank you!

**Comment by soupault** [comment] 2019-09-30 08:48
I cannot reproduce any one the issues here: neither the one related to `squeeze`, nor the one with `imread` (checked against different plugins).

I am closing the ticket due to the lack of details. Please, feel free to reopen if they are provided.

**Closed by soupault** 2019-09-30 08:48 UTC
Labels: status: needs info
