### ISSUE TITLE
transform.rescale loses data when nodata value is nan

### ISSUE THREAD

**Issue by jontwo** [scikit-image/scikit-image#3010] opened 2018-04-09 16:02 UTC
I'm trying to resample a raster using scikit-image 0.13.1 on python 2.7.4 (both Scientific Linux 7.4 and Windows 10). The nodata value is nan and in regions where the data is a narrow line, some or all of it is lost when resampling.

For example:
```
In [14]: import numpy as np
                                            
In [15]: from skimage import transform      
                                            
In [16]: arr=np.full((4,4),np.nan)

In [17]: arr[:,2]=3.

In [18]: arr
Out[18]:
array([[ nan,  nan,   3.,  nan],
       [ nan,  nan,   3.,  nan],
       [ nan,  nan,   3.,  nan],
       [ nan,  nan,   3.,  nan]])

In [19]: transform.rescale(arr,2,mode='symmetric',preserve_range=True)
Out[19]:
array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]])

```

Making the data area wider is an improvement, but I would expect the original data area to be maintained.

```
In [20]: arr[:,1]=3.

In [21]: arr
Out[21]:
array([[ nan,   3.,   3.,  nan],
       [ nan,   3.,   3.,  nan],
       [ nan,   3.,   3.,  nan],
       [ nan,   3.,   3.,  nan]])

In [22]: transform.rescale(arr,2,mode='symmetric',preserve_range=True)
Out[22]:
array([[ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan],
       [ nan,  nan,  nan,   3.,   3.,  nan,  nan,  nan]])
```

Using 0 as nodata keeps the shape better, but the values are reduced. The max value here has gone down from 3.0 to 2.2, which is no good.

```
In [23]: arr=np.full((4,4),0.)

In [24]: arr[:,2]=3.

In [25]: arr
Out[25]:
array([[ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  3.,  0.]])

In [26]: transform.rescale(arr,2,mode='symmetric',preserve_range=True)
Out[26]:
array([[ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.2,  2.2,  0.7,  0. ],
       [ 0. ,  0. ,  0. ,  0.8,  2.3,  2.2,  0.7,  0. ]])
```

**Comment by jni** [comment] 2018-04-10 02:01
@jontwo This is an unavoidable consequence of how rescaling works: by interpolation of values (meaning nearby values are averaged together in some way) (see [this Wikipedia entry](https://en.wikipedia.org/wiki/Bilinear_interpolation) for a simple example). I would argue that your second result is closest to what you actually want, but another option is to add `order=0` to the `rescale` call. This turns to nearest-neighbor interpolation and does not involve adding nearby values together, so it works:

```python
In [6]: transform.rescale(arr, 2, mode='symmetric', preserve_range=True, order=0)
Out[6]:
array([[ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan],
       [ nan,  nan,  nan,  nan,   3.,   3.,  nan,  nan]])
```

I'm going to close this as it's not a bug, but feel free to continue the discussion here.

**Closed by jni** 2018-04-10 02:01 UTC

**Comment by jontwo** [comment] 2018-04-10 12:16
@jni Thanks for the quick response - I'd imagined it might be unavoidable, as I tried a few other tools and got the same result. I was hoping it might be possible to add an option to allow these values to be calculated, but it looks like `order=0` might be what I need.
