### ISSUE TITLE
Installatation failure with setuptools 65

### ISSUE THREAD

**Issue by olebole** [scikit-image/scikit-image#6592] opened 2022-10-24 06:31 UTC
### Description:

As the Debian maintainer of skimage, I just received [Debian#1022461](https://bugs.debian.org/1022461) that the package cannot longer be built:
```
[…] python3.10 setup.py config 
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/setup.py", line 214, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 126, in setup
    dist = setup(**new_attr)
  File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1107, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 540, in _parse_command_opts
    raise DistutilsClassError(
distutils.errors.DistutilsClassError: command class <class 'numpy.distutils.command.config.config'> must subclass Command
```

I can reproduce this locally with Debian unstable (setuptools 0.65.5) and testing (setuptools 65.3.0)). I think this is because out setuptools package was recently updated (and [this page in the numpy docs](https://numpy.org/devdocs/reference/distutils_status_migration.html)),  however I am not sure.

(Setting the environment variable `SETUPTOOLS_USE_DISTUTILS=stdlib` resolves this for the moment)

### Version information:

```Shell
3.10.7 (main, Oct  1 2022, 04:31:04) [GCC 12.2.0]
Linux-5.19.0-2-amd64-x86_64-with-glibc2.35
scikit-image version: 0.19.3
numpy version: 1.21.5
setuptools 65.3.0
distutils 3.10.7
```

**Comment by hmaarrfk** [comment] 2022-10-24 10:33
I believe this issues is due to your particular combination of numpy + setuptools

There are some recent release notes that indicate that this might be the case:
https://github.com/numpy/numpy/releases/tag/v1.22.2

Can you please try updating your version of numpy?

**Comment by olebole** [comment] 2022-10-24 14:19
Numpy 1.23.2 is in Debian experimental; however taking this instead of a test doesn't work as well. This is not problematic for me, since the workaround with the `SETUPTOOLS_USE_DISTUTILS` does the job for the moment. So, if you think it is not a problem of skimage, please feel free to close the issue.
Numpy 1.23 however comes with the deprecation message

> `numpy.distutils` is deprecated since NumPy 1.23.0, as a result of the deprecation of `distutils` itself. It will be removed for Python >= 3.12. For older Python versions it will remain present. It is recommended to use `setuptools < 60.0` for those Python versions. For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 

which suggests the code in `setup.py` should be updated at some point.

**Comment by hmaarrfk** [comment] 2022-10-25 21:39
I think grlee is on it https://github.com/scikit-image/scikit-image/pull/6536

**Comment by stefanv** [comment] 2023-04-24 04:23
@olebole we've completely revamped the build system. Please let me know if you are still experiencing any issues.

**Comment by soupault** [comment] 2023-10-27 14:34
@olebole I am closing this for now, assuming the issue is no longer present. Please, reopen/comment otherwise.

**Closed by soupault** 2023-10-27 14:34 UTC
Labels: :bug: Bug
