### ISSUE TITLE
bbox_area returns the area of the whole input image, not the area of the bounding box of a labeled region

### ISSUE THREAD

**Issue by fraserwatson** [scikit-image/scikit-image#2831] opened 2017-10-10 20:09 UTC
## Description
When using the bbox_area method, the returned value is input_data.size instead of labeled_bounding_box.size.

## Way to reproduce
```python
from skimage import data, util
from skimage.measure import label
from skimage.measure import regionprops

img = util.img_as_ubyte(data.coins()) > 110
label_img = label(img, connectivity=img.ndim)
props = regionprops(label_img, intensity_image=data.coins())

print(props[86].bbox_area)
print(props[86].image.size
print(data.coins().size)
```

**Comment by soupault** [comment] 2017-10-10 20:13
Duplicate of https://github.com/scikit-image/scikit-image/issues/2634

**Closed by soupault** 2017-10-10 20:13 UTC
