### ISSUE TITLE
Documentation build failure with sphinx 2.4

### ISSUE THREAD

**Issue by olebole** [scikit-image/scikit-image#4603] opened 2020-04-20 20:29 UTC
## Description

On Debian, we just updated sphinx to 2.4, and this leads to a failure when installing the HTML documentation. This is reported in [Debian#955068](https://bugs.debian.org/955068):

```
[…]
> dh_sphinxdoc -XMathJax.js
> dh_sphinxdoc: error: debian/python-skimage-doc/usr/share/doc/python-skimage-doc/html/./../dev/_static/docversions.js is missing
```
The problems seems to me that `docversions.js` is located in `doc/source/_static/docversions.js`, but is referenced differently, https://github.com/scikit-image/scikit-image/blob/063d677b358c014817d86c781add19bc402b096d/doc/source/_templates/versions.html#L7

At least the javascript should somehow copied to the `dev` path?
This is skimage 0.16.2 and sphinx 2.4.

**Comment by hmaarrfk** [comment] 2020-04-21 04:23
did you try 2.4.4? it seems like you are on 2.4.3. Not sure if something important has been fixed in that version.

**Comment by sciunto** [comment] 2020-04-21 06:52
I can't reproduce with sphinx 2.4.3 and our master branch, which has the same file location.

**Comment by jni** [comment] 2020-04-21 08:42
@stefanv any idea what’s happening here?

**Comment by stefanv** [comment] 2020-04-21 11:04
The documentation refers to a file that is hosted on our website, in the development version of the documentation.  The reason we do that is so that even older versions of the docs still have an up to date version of our version list.

The Debian script sees that the file is not present in the local distribution and complains.  Changing this into an absolute URL should help: https://scikit-image.org/docs/dev/_static/docversions.js

If that is not acceptable, then I would patch the documentation to not use the javascript and not display links to various other versions of the docs in the sidebar.  I.e., just empty out the file `versions.html`.

**Comment by olebole** [comment] 2020-04-21 12:22
I think for us the best way is then to use an empty list. Debian is quite sensitive when it comes to the inclusion of javascript from an external source.
@stefanv Thank you for the explanation here. Since this will solve my problem, the issue could be closed.

**Comment by stefanv** [comment] 2020-04-21 13:37
Great, thanks for packaging scikit-image, @olebole!

**Closed by stefanv** 2020-04-21 13:37 UTC
