### ISSUE TITLE
Rank test fails (or too sensitive?) on 32-bit

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2528] opened 2017-02-20 23:56 UTC
```

======================================================================
FAIL: skimage.filters.rank.tests.test_rank.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/venv/local/lib/python2.7/site-packages/skimage/filters/rank/tests/test_rank.py", line 16, in test_all
    check_all()
  File "/venv/local/lib/python2.7/site-packages/skimage/_shared/testing.py", line 232, in inner
    result = func(*args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/skimage/filters/rank/tests/test_rank.py", line 83, in check_all
    rank.entropy(image, selem))
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 257, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 719, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 1.28%)
 x: array([[ 1.5849625 ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,...
 y: array([[ 1.5849625 ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,...
```

**Comment by soupault** [comment] 2017-03-09 19:20
Fails also on `assert_equal(refs["otsu"], rank.otsu(self.image, selem))`:
```
======================================================================
FAIL: skimage.filters.rank.tests.test_rank.check_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/io/skimage/filters/rank/tests/test_rank.py", line 85, in check_all
    rank.otsu(image, selem))
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 361, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 871, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 0.16%)
 x: array([[140,  37, 182, 108, 108, 112, 165, 116, 145,  98, 135, 156, 157,
         18,  22,  22,  22,   5,  15, 198, 204, 118, 118, 118,  93],
       [ 37, 112, 154, 139,  67, 106, 116, 145,   5,  62,  41,  28, 167,...
 y: array([[140,  37, 182, 108, 108, 112, 165, 116, 145,  98, 135, 156, 157,
         18,  22,  22,  22,   5,  15, 198, 204, 118, 118, 118,  93],
       [ 37, 112, 154, 139,  67, 106, 116, 145,   5,  62,  41,  28, 167,...

----------------------------------------------------------------------
Ran 1 test in 0.143s

FAILED (failures=1)
```

**Comment by soupault** [comment] 2017-03-09 19:41
`entropy` arrays have difference in 16th digits after decimal point.
`otsu` arrays have only 1 different element, but the discrepancy is significant (81 against 41)

See arrays in the attached zip. Compare via `diff`, `meld` or whatever tool you like. Numbers in the names indicate the value of `precision` parameter of https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html .


[arrays_rank.zip](https://github.com/scikit-image/scikit-image/files/832107/arrays_rank.zip)

**Comment by soupault** [comment] 2017-03-09 19:55
By the way, this is a duplicate of https://github.com/scikit-image/scikit-image/issues/1407 :D.

**Comment by soupault** [comment] 2017-03-09 19:56
And also of https://github.com/scikit-image/scikit-image/issues/2111 ...

**Comment by soupault** [comment] 2017-03-15 18:30
__entropy__. Most likely fails due to an insufficient precision in https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/rank/generic_cy.pyx#L366.

**Comment by jni** [comment] 2017-03-17 04:50
@stefanv If you have a machine I can test this on, I can work on it soonish. Please DM me details over Signal if so. ;)

**Comment by soupault** [comment] 2017-03-17 04:52
@jni see https://github.com/scikit-image/scikit-image/issues/2569. The solution from Matthew worked great for me.

**Comment by matthew-brett** [comment] 2018-06-12 13:38
Latest master, still failing : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/391261685#L1164

**Comment by hmaarrfk** [comment] 2018-10-23 04:02
Anyway, here is my attempt.
https://github.com/hmaarrfk/scikit-image/pull/9
Some refactoring has been done to the tests, just so I can see what is happening.

Anybody is free to cherry-pick the changes they want if they want to go ahead with the PR.

**Comment by hmaarrfk** [comment] 2018-10-23 14:48
So I finally got to the bottom of the OTSU failer. It can be summarized here:

https://gist.github.com/hmaarrfk/4afae1cfded1d78e44c9e4f58285d552
kinda a lengthy one so here is the TLDR:
It is a compiler dependent rounding error.
What can we do about it?
  * Not much. We can just force pixel [3, 5] of otsu to be 81, and add a note about it.
  * micro optimize the OTSU algorithm so that the compiler reliably converges to a consistent optimization.

In debugging this, I did the micro optimization for OTSU. It avoids 1 multiply, 1 add, and 1 Divide for each loop. (I hope I counted right). This brings the total ops to 5mul, 5add, 1div down from 6mul, 6add, 6div. 

This may or may not be a 20% speed up in OTSU, we would have to bench.

There are probably more small speedups to have in OTSU, though that might depend on compiler settings and we would need real benchmarks to see what happens. (eg, make all divisions multiplications)

With this micro optimization, both 64bit and 32bit linux return the same value for the pathological case. Both are different than the dumped coded "correct" results.

As a bonus, some of the adds and muls can now be done as integers :D, though i'm not convinced this is faster due to type casting

**Comment by hmaarrfk** [comment] 2018-10-23 15:34
So I have the fixes in the PR linked to it above, but I'll need some help getting the fixes through the review:

* [ ] PR https://github.com/scikit-image/scikit-image/pull/3501 about max_bin calculation is in flight. This one should be easy to pass?
* [ ] Refactor the tests to use parametrize so pinpoint the previous failers exactly.
* [ ] use allclose for entropy
* [ ] Hardcode the pathologically incorrect pixel for OTSU to the correct value.

Optimizations:
* [ ] Create a benchmark for `rank.entropy`
* [ ] Decide on how to optimize `rank.entropy` based on the benchmark
* [ ] Create a benchmark for `otsu`
* [ ] Decide on how to micro optimize otsu based on the benchmark

**Closed** 2018-10-28 12:43 UTC
Labels: type: bug, type: failure arch specific
