### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by joaquincasares** [scikit-image/scikit-image#1544] opened 2015-06-06 23:36 UTC
b6aa3584394e67478907f2d2cc22b7477d037f93 seems to have introduced a regression where pip installs break on `ImportError: No module named scipy`.

**Comment by blink1073** [comment] 2015-06-07 01:41
@joaquincasares, how are you installing exactly?  By using `pip install .` on a local clone of the repo?

**Comment by joaquincasares** [comment] 2015-06-08 15:12
Using pip install without a local clone. I just realized for Ubuntu I should use `apt-get`.

If that's the case, feel free to close out the issue. Thanks for looking into this!

**Comment by blink1073** [comment] 2015-06-08 15:23
@joaquincasares, `apt-get` will get you a fairly old version.  You can use `apt-get` to get the old version and its dependencies (including `scipy`), and then use `pip install scikit-image==0.11.3`.

**Comment by JDWarner** [comment] 2015-06-23 20:28
@joaquincasares I'm closing this, assuming no news is good news (and `pip install` seems to be working in the various CI builds, and my own systems). 

If you need more assistance, feel free to reopen.

**Closed by JDWarner** 2015-06-23 20:28 UTC

**Comment by ctheune** [comment] 2015-11-22 17:06
The issue is, that you can't "pip install scikit-image" in a fresh virtualenv (or god forbid you try to use buildout). You need to manually install scipy first because it's used during compilation. I think this needs to be a setup dependency like cython.

**Comment by blink1073** [comment] 2015-11-22 23:08
Hi @ctheune, this issue is fixed in the dev version and will be in the next release (hopefully soon).

**Comment by ctheune** [comment] 2015-11-23 08:19
Ah, sorry for the noise. I couldn't follow that in the discussion when it was closed. :)
