### ISSUE TITLE
SLIC very slow with win 10

### ISSUE THREAD

**Issue by kwiechen** [scikit-image/scikit-image#3026] opened 2018-04-23 18:54 UTC
## Description
SLIC is very slow with Winpython/Windows 10 but faster when using WSL/Windows 10

Winpython/Win10 log:
image size  1421x998 pixel
superpixel_size = 25 micrometer  72 pixel
Windows-10-10.0.16299-SP0
('64bit', 'WindowsPE')
Python  3.5.4
scikit-image version  0.13.1
SLIC elapsed time 29.36 s

WSL/Win10 log:
image size  1421x998 pixel
superpixel_size = 25 micrometer  72 pixel
Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
('64bit', 'ELF')
Python  3.5.2
scikit-image version  0.13.1
SLIC elapsed time 4.87 s

segments = slic(img_as_float(image), n_segments = numSegments, multichannel = True, 
convert2lab = True, slic_zero = True)

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [

 ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by soupault** [comment] 2018-04-24 09:50
I personally don't know how Winpython is implemented, so the only thing I'd suggest is to try to update it to the latest version (and also the corresponding `numpy` and `scipy` installations).

In my Linux environment I have the performances similar to your `WSL/Win10`.

@scikit-image/core do we officially support this distribution?

**Comment by cgohlke** [comment] 2018-04-27 18:29
I can reproduce the slowness on Windows. It is due to the use of the `pow` function in inner loops, e.g. at https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/_slic.pyx#L135. Probably gcc optimized those function call away while msvc does not, or it could depend on the Cython version used. Replacing `x**2` with `x*x` reduces slic runtime 10 times from 26s to 2.4s.

**Comment by cgohlke** [comment] 2018-04-27 19:08
Looks like [_quickshift_cython](https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/_quickshift_cy.pyx#L76) might suffer from the same problem.

**Comment by soupault** [comment] 2018-04-27 19:11
@cgohlke you might find this interesting also - https://github.com/scikit-image/scikit-image/issues/2657

**Comment by cgohlke** [comment] 2018-04-27 19:18
Any `**2` used in inner loops is a candidate for manual optimization. That includes radon_transform, hough_transform, quickshift, and denoising.

**Comment by JDWarner** [comment] 2018-04-27 20:38
Wow.  Unless there's any significant reason or performance issue with the alternative `x*x`, this one is a no-brainer.

**Comment by cgohlke** [comment] 2018-04-27 21:00
I'm currently checking if this fixes any of #2657 ...

**Comment by soupault** [comment] 2018-04-28 08:36
Closed via #3035 .

**Closed by soupault** 2018-04-28 08:36 UTC
Labels: status: needs decision, type: perfomance

**Comment by soupault** [comment] 2018-04-28 08:38
@cgohlke thank you very much to the investigation and the fix!

**Comment by kwiechen** [comment] 2018-04-29 09:12
Thank you very much for the SLIC/Win10 run-time optimization. Do you plan
to release v0.13.2 with this fix (and maybe with others like new parameter
anti_aliasing in transform.resize)?


2018-04-28 10:38 GMT+02:00 Egor Panfilov <notifications@github.com>:
