### ISSUE TITLE
Documentation: skimage.color ranges

### ISSUE THREAD

**Issue by daniilhayrapetyan** [scikit-image/scikit-image#4474] opened 2020-02-22 10:31 UTC
## Description

Sometimes it is difficult to guess the range of color space when using skimage.color. The problem is getting difficult because there is no standard, and different libraries suggest different ranges for the same color spaces.

For example LAB space in opencv and skimage have different ranges. It will be great to have the limit values documented.

**Comment by rfezzani** [comment] 2020-02-22 15:08
I agree, this could be an excellent addition.

**Comment by anjani30646** [comment] 2020-03-09 13:46
Hi, I would like to take up this issue.

**Comment by alishbashahid** [comment] 2020-03-12 18:38
Hi, I would like to document the limit values.

**Comment by jni** [comment] 2020-03-12 22:58
It turns out that this is a duplicate of #1185! Let's move the discussion there.

**Comment by jni** [comment] 2020-03-12 22:59
Also, look at the code snippet I submitted in #4506, as this would be a useful start to documenting all the color spaces.

**Closed** 2020-03-12 22:58 UTC
Labels: good first issue, type: documentation
