### ISSUE TITLE
Windows Build of 0.16.2 on python 3.6 seems to be incompatible with numpy 1.15.4

### ISSUE THREAD

**Issue by Borda** [scikit-image/scikit-image#4270] opened 2019-10-27 20:44 UTC
## Description

I have a problem while importing `skimage` filters on Windows and Python 3.6 
Somehow it passes with the same packages for Python 3.5. and 3.7 as you can see: https://ci.appveyor.com/project/Borda/birl/builds/28411883

## Version information
> python --version
Python 3.6.8
> pip --version
pip 19.3.1 from c:\python36-x64\lib\site-packages\pip (python 3.6)
> pip list
numpy== 1.15.4
scikit-image==0.16.2

## Output error message
```
c:\python36-x64\lib\site-packages\skimage\filters\__init__.py:11: in <module>
    from .thresholding import (threshold_local, threshold_otsu, threshold_yen,
c:\python36-x64\lib\site-packages\skimage\filters\thresholding.py:9: in <module>
    from ..transform import integral_image
c:\python36-x64\lib\site-packages\skimage\transform\__init__.py:2: in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
c:\python36-x64\lib\site-packages\skimage\transform\hough_transform.py:2: in <module>
    from ._hough_transform import (_hough_circle,
stringsource:105: in init skimage.transform._hough_transform
    ???
E   AttributeError: type object 'skimage.transform._hough_transform.array' has no attribute '__reduce_cython__'
```
complate fail log from Appveyor: https://ci.appveyor.com/project/Borda/birl/build/job/l9bxqshjqqon9eik

**Comment by Borda** [comment] 2019-10-27 20:51
can be similar to https://github.com/nltk/nltk/issues/2276 https://github.com/cython/cython/issues/1953

**Comment by hmaarrfk** [comment] 2019-10-27 21:25
Can you try to unpin numpy and scikit-image? what the bug you are hitting with scikit-image 0.16.2?

Is this related?
https://ci.appveyor.com/project/Borda/birl/builds/28411883/job/l9bxqshjqqon9eik#L313

**Comment by Borda** [comment] 2019-10-27 21:36
> Can you try to unpin numpy and scikit-image?

pls, what do you mean by "unpin"? :)

> what the bug you are hitting with scikit-image 0.16.2?

`AttributeError: type object 'skimage.transform._hough_transform.array' has no attribute '__reduce_cython__'`

> Is this related? https://ci.appveyor.com/project/Borda/birl/builds/28411883/job/l9bxqshjqqon9eik#L313

No idea what the `py36 run-test-pre: PYTHONHASHSEED='671'` is, I do not use any python seed...

**Comment by hmaarrfk** [comment] 2019-10-27 22:16
I meant two lines below it, it says "warning test command not found"
https://ci.appveyor.com/project/Borda/birl/builds/28411883/job/l9bxqshjqqon9eik#L315

Use newer numpy -- modern builds of scikit-image fixed the issue with numpy 1.16
https://github.com/Borda/BIRL/blob/master/requirements.txt#L1
Use newer scikit-image (which you seem to have done)
https://github.com/Borda/BIRL/blob/master/requirements.txt#L9

**Comment by Borda** [comment] 2019-10-27 22:29
ok, I will try... how can I implement [this](https://github.com/scikit-image/scikit-image/issues/3867#issuecomment-487332013) conditional package installation in requirements?

**Comment by hmaarrfk** [comment] 2019-10-27 22:36
basically you don't.

This is where distributions and semantic versionning come in to play
https://semver.org/

Generally, it should be safe to install newer patch versions of a software.
That means if people have 0.14.1, they should be able to install 0.14.2
Finally, distributors of software should be the ones that take care of these conflicts. pip is a particularly bad dependency solver, which is why Anaconda created conda.

Since that is a benchmarking suite, for your own sake, I would simply set the requirement to be 

`scikit-image >=0.14.2`

I think that fixes your issues right?

**Comment by hmaarrfk** [comment] 2019-10-27 22:39
>  Btw, should it be also updated here - requirements/default.txt#L1

I'm not sure what the issue is, but if you think it is important, can you open a new ticket so we can focus on it there?

**Comment by hmaarrfk** [comment] 2019-10-27 22:40
Oh i see, i'll boot up into windows in a bit and see if i can recreate.

Do you have a windows machine? can you provide instructions to recreate if possible?

**Comment by Borda** [comment] 2019-10-27 22:41
well obviously this combination `numpy== 1.15.4 ; scikit-image==0.16.2` crash for Python3.6

**Comment by hmaarrfk** [comment] 2019-10-27 22:42
I guess as downloaded from pypi. Not sure why, but if you could recreate locally, we can maybe try to understand why. Appveyor is hard to debug. Maybe provide the virtualenv instructions with the `pytest` command to trigger the bug?

**Comment by Borda** [comment] 2019-10-27 22:43
I am happy Linux user, this came from multi-OS testing, I was using Appveyor for this purpose

**Comment by Borda** [comment] 2019-10-27 22:44
> I guess as downloaded from pypi. Not sure why, but if you could recreate locally, we can maybe try to understand why. Appveyor is hard to debug. Maybe provide the virtualenv instructions with the `pytest` command to trigger the bug?

yes, from pypi...

**Comment by hmaarrfk** [comment] 2019-10-27 22:44
The only thing I Can think about is that the dependency didn't get pinned right for the python 3.6 build.

https://github.com/scikit-image/scikit-image-wheels/pull/26/files#diff-11c909939117928998b102a1fff7d363L22

I noticed this in a recent PR.

**Comment by hmaarrfk** [comment] 2019-10-27 22:45
Technically, we should have been able to build with 1.13 though, we just didn't want to test with it anymore and some python-only functions needed newer functionality.

**Comment by Borda** [comment] 2019-10-27 23:20
well, `numpy` upgrade solves the issue

**Comment by hmaarrfk** [comment] 2019-10-27 23:24
Right, but I feel like this should be a supported configuration.

I was able to reproduce with:

```
conda create --name py36 python=3.6 --yes
conda activate py36
python -m pip install scikit-image==0.16.2 numpy==1.15.4
python -c "import skimage.filters"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mark\Miniconda3\envs\py36\lib\site-packages\skimage\filters\__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "C:\Users\mark\Miniconda3\envs\py36\lib\site-packages\skimage\filters\edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "C:\Users\mark\Miniconda3\envs\py36\lib\site-packages\skimage\restoration\__init__.py", line 7, in <module>
    from ._denoise import (denoise_tv_chambolle, denoise_tv_bregman,
  File "C:\Users\mark\Miniconda3\envs\py36\lib\site-packages\skimage\restoration\_denoise.py", line 5, in <module>
    from ._denoise_cy import _denoise_bilateral, _denoise_tv_bregman
  File "__init__.pxd", line 918, in init skimage.restoration._denoise_cy
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

```
(py36) C:\Users\mark>pip list
Package          Version
---------------- ---------
certifi          2018.1.18
chardet          3.0.4
click            6.7
cycler           0.10.0
decorator        4.4.1
flake8           3.5.0
idna             2.6
imageio          2.6.1
kiwisolver       1.1.0
matplotlib       3.1.1
mccabe           0.6.1
networkx         2.4
numpy            1.15.2
pew              1.1.2
Pillow           6.2.1
pip              10.0.1
pipenv           9.0.3
pipsi            0.9
psutil           5.3.1
pycodestyle      2.3.1
pyflakes         1.6.0
pyparsing        2.4.2
python-dateutil  2.8.0
PyWavelets       1.1.1
requests         2.18.4
scikit-image     0.16.2
scipy            1.3.1
setuptools       41.4.0
six              1.12.0
urllib3          1.22
virtualenv       15.1.0
virtualenv-clone 0.2.6
wheel            0.33.6
wincertstore     0.2
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

<details> <summary> Python 3.7 works</summary>

```
(py37) C:\Users\mark>python -c "import skimage.filters"

(py37) C:\Users\mark>pip list
Package         Version
--------------- ---------
certifi         2019.9.11
cycler          0.10.0
decorator       4.4.1
imageio         2.6.1
kiwisolver      1.1.0
matplotlib      3.1.1
networkx        2.4
numpy           1.15.4
Pillow          6.2.1
pip             19.3.1
pyparsing       2.4.2
python-dateutil 2.8.0
PyWavelets      1.1.1
scikit-image    0.16.2
scipy           1.3.1
setuptools      41.4.0
six             1.12.0
wheel           0.33.6
wincertstore    0.2
```
</details>

@jni, maybe we should rebuild 0.16.2 with the updated numpy minimum version to 1.14.5 instead of 1.13.3???

**Comment by hmaarrfk** [comment] 2019-10-27 23:26
This seems to be https://github.com/scikit-image/scikit-image/issues/3655

I'm kinda not so interested to fix this because I see this as a corner case. Numpy doesn't really like supporting these kinda of builds (i.e. build with OLD numpy, but use newer numpy) but many people do it (conda and conda-forge are guilty of this).

**Comment by jni** [comment] 2019-10-27 23:48
@hmaarrfk there is no such thing as "rebuilding" with PyPI. It is append-only. So we would need to make a new release. And also, I'm not super interested in messing with our scikit-image-wheels repo myself. Perhaps @stefanv or @matthew-brett can provide some clarity about what's happening here?

Thanks for the sleuthing @hmaarrfk! You are always super quick at tracking down build issues which I find super tricky and frustrating. I am very grateful for this. 😊

**Comment by Borda** [comment] 2019-10-27 23:54
btw, just curious, you skipped `0.15` completely... ? https://github.com/scikit-image/scikit-image/tags

**Comment by hmaarrfk** [comment] 2019-10-27 23:57
we didn't exactly skip it, it seems that the combination of building with 1.13.3 and runnings with 1.15.4 doesn't entirely work.

Honestly, I want to see 1 more user complain, then I'll go through a release process of 0.16.3 ;)

**Comment by jni** [comment] 2019-10-27 23:59
Yes, as @hmaarrfk says, I want to get a bit better sense of how many people would be affected by this before closing.

No, we didn't skip 0.15, we just released a few 0.14.x point releases after 0.15.0, scroll down to the bottom of that page. =)

**Comment by hmaarrfk** [comment] 2019-10-28 00:06
I created https://github.com/scikit-image/scikit-image-wheels/pull/28
and https://github.com/scikit-image/scikit-image-wheels/pull/29

to attempt to help this in the future releases.

**Comment by spot92** [comment] 2019-11-24 04:55
pip install --upgrade scikit-image imageio numpy scipy

That fixes it.

**Comment by hmaarrfk** [comment] 2019-11-29 22:17
@jni, is it possible to delete a wheel from pypi and upload a new one?

**Comment by Borda** [comment] 2019-11-29 22:19
You can delete but not upload one with the same number

**Comment by hmaarrfk** [comment] 2019-11-29 22:20
hmm, slightly annoying

**Comment by matthew-brett** [comment] 2019-11-29 22:27
I think [build tags](https://github.com/MacPython/wiki/wiki/Build-Tags) may be want you want here ...

**Comment by hmaarrfk** [comment] 2019-11-29 22:54
Thanks! 

Do you know what I would have to do to for the same thing to occur for linux/mac??? multibuild is quite elaborate...
I don't need it now, but maybe eventually.

**Comment by hmaarrfk** [comment] 2019-12-01 03:57
@jni I guess we should try to upload the wheels back to pypi before closing this off

**Comment by Dwedit** [comment] 2020-08-12 17:49
I was trying to run a python program that depended on this package (https://github.com/movehand/raisr), and got the error `ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`, had to upgrade to Python 3.8, but then it worked.

**Comment by hmaarrfk** [comment] 2020-08-13 13:05
I'm curious why that is a value error. For me this manifests as a warning.

**Closed** 2021-10-18 14:34 UTC
Labels: type: failure arch specific
